/**
 * curriculum/ccna2/theory-c.ts — plain-language theory for the third part of CCNA 2, keyed by the lesson ids of
 * `ccna2/lessons.ts`: lessons 22-24 (access-layer security), 29-32 (static routing) and 33-34 (translation and fault
 * finding). `theory-a.ts` carries 01-11 and `theory-b.ts` 12-21; `theory.ts` merges the three. The wireless lessons
 * 25-28 arrive in W7 (ARCHITECTURE-P2 §7 W6 course, §11.1, §11.3).
 *
 * Same shape and subset as `curriculum/ccna1/theory-a.ts` and `theory-b.ts`: five fixed sections — the idea in one
 * breath, why it exists, how it actually works with a worked example, what trips people up, and what to type in
 * NetForge — markdown limited to headings, lists, emphasis, code and allowlisted links, no raw HTML, original wording
 * and no vendor names. Every backticked command is one the CLI grammar ships for the model the lesson names (the
 * NF-C2960 switch, the NF-2911 router, the NF-PC workstation), and every panel is a real dock or inspector tab.
 *
 * Addresses: a worked example sketches its own topology from the documentation and private ranges, so a build lab is
 * never answered by the lesson that opens it; a bullet under "See it in NetForge" is something the learner types in
 * the lesson's own lab, so it uses that lab's names and addresses. No lesson here prints an interface address or
 * default-gateway line, because none of those is a line its lab's reference solution types.
 *
 * What NetForge does not model is said plainly rather than implied: there are no attack tools (lesson 22 is concepts
 * only, spec §11.6), DHCP snooping and ARP inspection are named but not built, and equal-cost sharing is per
 * source-and-destination pair, never per packet ([S6], §4.1).
 *
 * ponytail: the same `md(...)` join as the CCNA 1 files, so a line of markdown is a line of source and a backtick
 * never needs escaping.
 */
import type { LessonTheoryMap } from '../../contracts/curriculum.js';

/** One lesson body from its lines (the labs build `instructions` the same way). */
const md = (...lines: string[]): string => lines.join('\n');

/** Lesson bodies 22-24 and 29-34. Keys must match ids in `ccna2/lessons.ts`. */
export const THEORY_C: LessonTheoryMap = {
  'ccna2-22-threats-at-layer-2': md(
    '## The idea in one breath',
    '',
    'A switch trusts every frame it hears. It believes the source address, agrees to whatever a neighbour proposes, and accepts a better root bridge from anyone. Each layer 2 attack abuses one of those beliefs; each defence in this module withdraws one.',
    '',
    '## Why it exists',
    '',
    'Firewalls inspect IP packets at the edge, but every desk port behind them is one cable away from anybody who walks in, and a layer 2 attack never reaches a router. Only the access switch is placed to notice, so its ports carry the defence.',
    '',
    '## How it actually works',
    '',
    '- **Address table flooding.** Frames from thousands of invented source addresses fill the address table. The switch can no longer learn genuine ones, so it floods their frames out of every port, the attacker\'s included. Port security caps the addresses one port may introduce.',
    '- **Spoofing and unknown devices.** Anyone can copy another machine\'s hardware address, or swap a desk computer for their own. Port security pins the addresses a port accepts and decides what happens to the rest.',
    '- **Switch spoofing.** A port left in a dynamic mode becomes a trunk if the far end asks, and a laptop that asks then receives every VLAN the trunk carries. A fixed mode with negotiation switched off closes it.',
    '- **Double tagging.** A host in a trunk\'s native VLAN sends a frame with two tags. The first switch sends native frames untagged, stripping the outer tag; the next delivers the frame into the inner tag\'s VLAN. It works one way only, and only while a host port sits in the native VLAN.',
    '- **Root takeover.** A rogue switch announcing priority 0 wins the spanning-tree election and pulls traffic across its own links. BPDU guard shuts a host port the moment a BPDU arrives; root guard refuses a better root where the root should never appear.',
    '',
    'A fake DHCP server and forged ARP replies are stopped by DHCP snooping and dynamic ARP inspection, which this course names but NetForge does not model.',
    '',
    '## What trips people up',
    '',
    '- A VLAN separates broadcast domains. On its own it does not stop a port negotiating a trunk.',
    '- None of this needs skill with cables, only a laptop and a forgotten port. That is why unused ports get shut.',
    '',
    '## See it in NetForge',
    '',
    'NetForge has no attack tools. On an **NF-C2960** it shows the state each defence protects:',
    '',
    '- `show mac address-table count` counts the addresses the switch has learned.',
    '- `show interfaces trunk` lists the ports trunking now; a desk port there is switch spoofing in waiting.',
    '- `show port-security` lists the secured ports and their violation counts.',
    '- `show spanning-tree root` names each VLAN\'s root; one you did not choose signals a takeover.',
  ),

  'ccna2-23-port-security': md(
    '## The idea in one breath',
    '',
    'Port security lets a switch port accept frames from a fixed number of source addresses. Below the limit a new address is learned; at the limit a new address is a violation, and you choose what a violation does.',
    '',
    '## Why it exists',
    '',
    'Most access ports have one device behind them for years. Accepting any number of addresses helps nobody but someone flooding the address table or swapping in their own machine; a limit turns that into an event the switch acts on.',
    '',
    '## How it actually works',
    '',
    'Port security needs a fixed mode, so the port is made an access port first:',
    '',
    '```',
    'interface FastEthernet0/1',
    ' switchport mode access',
    ' switchport port-security',
    ' switchport port-security maximum 1',
    ' switchport port-security violation shutdown',
    ' switchport port-security mac-address sticky',
    '```',
    '',
    'The maximum defaults to 1 and the mode to shutdown, so the middle two lines only restate the defaults. An address becomes secure in one of three ways:',
    '',
    '- **Static**: typed by hand, one line per address, such as `switchport port-security mac-address 00:1a:2b:3c:4d:5e`.',
    '- **Dynamic**: learned from traffic, and forgotten when the link goes down.',
    '- **Sticky**: learned from traffic and written into the running configuration as a line of its own, so it survives a link flap and, once saved, a reload.',
    '',
    'A frame from a new address on a port already at its maximum is a violation. **protect** drops it quietly. **restrict** drops it, counts it and logs it. **shutdown** drops it, counts it and **error-disables** the port: the link goes down and stays down.',
    '',
    'To bring the port back, remove the cause, then give it `shutdown` followed by `no shutdown`. `errdisable recovery cause psecure-violation` makes the switch retry by itself after an interval, but if the stranger is still there, the port shuts again.',
    '',
    '## What trips people up',
    '',
    '- Replacing a computer on a secured port. The old static or sticky address still fills the maximum, so the new machine violates with its first frame. Remove the old address before you recover the port.',
    '- Recovering before repairing. `no shutdown` alone walks straight back into the violation.',
    '- An address already secure on another port of the same VLAN is a violation here too.',
    '- A port still in a dynamic mode refuses `switchport port-security`.',
    '',
    '## See it in NetForge',
    '',
    'In the lab, SW1 is an **NF-C2960** with one port a stale address has already shut:',
    '',
    '- `show port-security interface FastEthernet0/3` gives the status, maximum, mode, violation count and last violating address.',
    '- `show interfaces status err-disabled` lists every error-disabled port with its cause.',
    '- `show port-security address` lists every secure address and its kind.',
    '- `show running-config` shows each configured or sticky address as a line under its port; the same line with `no` in front removes it.',
  ),

  'ccna2-24-hardening-switch-ports': md(
    '## The idea in one breath',
    '',
    'Every port nobody uses, every trunk that still negotiates and every native VLAN left on VLAN 1 is a door someone else can open. Hardening closes them before anyone tries.',
    '',
    '## Why it exists',
    '',
    'A switch arrives ready to work, not ready to be safe. Every port is enabled, in VLAN 1 and willing to become a trunk if asked, and every trunk carries untagged traffic in VLAN 1. That is right for a switch on a lab bench and wrong for one under a desk in a public building. The three habits below cost a few lines each and remove the attacks of the last two lessons at the root.',
    '',
    '## How it actually works',
    '',
    '**Shut what is not in use.** A disabled port carries nothing, whatever gets plugged into it. An interface range applies the same lines to many ports at once:',
    '',
    '```',
    'interface range FastEthernet0/4 - 24',
    ' shutdown',
    '```',
    '',
    'Many sites also move unused ports into a VLAN that nothing uses, so a port enabled by mistake still reaches nobody.',
    '',
    '**Move the native VLAN.** Native frames cross a trunk untagged, which is exactly what double tagging needs. Give the native VLAN a number no host port uses, at both ends of every trunk:',
    '',
    '```',
    'vlan 99',
    ' name NATIVE',
    'exit',
    'interface GigabitEthernet0/1',
    ' switchport trunk native vlan 99',
    '```',
    '',
    '**Stop negotiating.** Fix the mode of every port by hand: `switchport mode access` for a host port, `switchport mode trunk` for a link to another switch. Then `switchport nonegotiate` on the trunk stops it speaking the negotiation protocol at all, so nothing at the far end can talk it into or out of trunking.',
    '',
    '## What trips people up',
    '',
    '- Changing the native VLAN at one end only. The ends then disagree about where untagged frames belong, and spanning tree blocks the two native VLANs on that trunk as inconsistent, while the other VLANs keep crossing, until the other end matches.',
    '- `switchport nonegotiate` is refused on a port still in a dynamic mode: fix the mode first.',
    '- A shut port is not a spare port. When a new desk arrives, somebody has to enable it on purpose, and that is the point.',
    '',
    '## See it in NetForge',
    '',
    'The last tasks of the port-security lab harden its **NF-C2960** switches:',
    '',
    '- `show interfaces status` lists every port with its state; the unused ones should read `disabled`.',
    '- `show interfaces trunk` shows each trunk with its mode, whether it negotiates and its native VLAN. Run it on both switches and compare.',
    '- `show dtp interface GigabitEthernet0/1` says whether that port still negotiates.',
    '- `show vlan brief` confirms VLAN 99 exists on each switch.',
  ),

  'ccna2-29-how-a-router-chooses': md(
    '## The idea in one breath',
    '',
    'A router sends each packet by the most specific route that matches it. Distance only decides which of two sources may install the very same network, and a next hop is looked up until the router knows its way out.',
    '',
    '## Why it exists',
    '',
    'Routing tables overlap: a default route covers every address, a /16 a site, a /24 one LAN in it, a /32 one server. Almost any packet matches several, so the router needs a rule that always gives one answer, and another for two sources offering the same network.',
    '',
    '## How it actually works',
    '',
    '**Longest match.** R1 holds `0.0.0.0/0`, `10.1.0.0/16`, `10.1.5.0/24` and `10.1.5.100/32`, each through a different neighbour. A packet for `10.1.5.100` matches all four and follows the /32; `10.1.5.7` follows the /24, `10.1.9.9` the /16, and `172.16.0.1` only the default. The longer prefix is the more specific route, and it wins.',
    '',
    '**Administrative distance** ranks sources. A connected network has 0, a static route 1, a routing protocol such as OSPF 110, and a default route learned as a DHCP client 254. When two sources offer exactly the same prefix and length, the lower distance is installed and the other waits outside the table.',
    '',
    '**Recursive lookup.** A route naming only a next hop does not say which interface to use, so the router looks the next hop up like a destination: `10.0.0.2` matches the connected network of `GigabitEthernet0/1`, the way out. Had it matched another static route, the lookup would repeat. NetForge leaves a route whose next hop matches nothing out of the table until it becomes reachable.',
    '',
    '**Equal-cost paths.** Two routes to one prefix with the same distance are both installed and share the load. NetForge keeps up to four and picks one per source and destination pair, so a conversation always follows one path while different conversations spread out.',
    '',
    '## What trips people up',
    '',
    '- Comparing distance across prefixes. A /24 with distance 200 still beats a /16 with distance 1 for an address inside the /24: longest match comes first.',
    '- Expecting round robin. Sharing is per conversation, so one stream of pings never alternates.',
    '- Missing the local routes. Each interface address appears as its own /32 marked `L`, beside the connected network marked `C`.',
    '',
    '## See it in NetForge',
    '',
    'On an **NF-2911** router:',
    '',
    '- `show ip route` lists each route with its code, next hop or exit interface, and distance and metric; the line above the table names the default route.',
    '- `show ip route static` keeps only the routes you typed; each extra equal-cost path sits on an indented line below its route.',
    '- In the **Provenance** tab, the TTL decrement of a forwarded packet names the matching route as its cause.',
  ),

  'ccna2-30-static-route-forms': md(
    '## The idea in one breath',
    '',
    'A static route always names a destination and its mask. What follows says where to send the packet: the next router\'s address, the interface to leave by, or both. A mask of all ones makes the destination a single host.',
    '',
    '## Why it exists',
    '',
    'Each form fits a kind of link. A serial point-to-point link has one device at the far end, so the interface says everything. An Ethernet link may hold many neighbours, so the router must be told which one gets the packet. And sometimes you want a path to one machine without opening the network around it.',
    '',
    '## How it actually works',
    '',
    'R1, R2 and R3 serve `192.168.1.0/24`, `192.168.2.0/24` and `192.168.3.0/24`. R1 reaches R2 over Ethernet, where R2 is `10.0.0.2` and R1 `10.0.0.1`, and R3 over a serial link. The first two lines are on R1, the third on R2, the last on R3:',
    '',
    '```',
    'ip route 192.168.2.0 255.255.255.0 10.0.0.2',
    'ip route 192.168.3.0 255.255.255.0 Serial0/0/0',
    'ip route 192.168.1.0 255.255.255.0 GigabitEthernet0/0 10.0.0.1',
    'ip route 192.168.1.50 255.255.255.255 Serial0/0/0',
    '```',
    '',
    '- **Next hop**: the router looks the next hop up to find the exit interface, a recursive lookup. The everyday form; it works over any link.',
    '- **Exit interface**: no lookup; the destination counts as reachable straight out of that interface. It suits a point-to-point link; over Ethernet the router must ARP for every destination.',
    '- **Fully specified**: interface and next hop together. The right choice on a multi-access link: the way out is pinned and the neighbour is named.',
    '- **Host route**: a /32 matches one address, so R3 reaches the server `192.168.1.50` and nothing else behind R1.',
    '',
    '## What trips people up',
    '',
    '- A next hop is the neighbour\'s address on the shared link, never one of your own.',
    '- A route missing from the table is usually unusable rather than lost: its next hop is unreachable or its exit interface is down, while `show running-config` still lists it.',
    '- An exit-interface route over Ethernet needs the neighbour to answer ARP for other hosts. That proxy ARP is on by default on a router interface; `no ip proxy-arp` on the neighbour breaks the route.',
    '- Removing a route takes the whole line with `no` in front.',
    '',
    '## See it in NetForge',
    '',
    'The lab gives you three **NF-2911** routers and not one static route:',
    '',
    '- `show ip route static` shows each form: `via` and an address for a next hop, `out` and an interface for an exit interface, both for a fully specified route.',
    '- `show ip route` on R3 shows the host route as a /32 beside its connected networks.',
    '- `ping 10.1.0.100` from the **Command Prompt** of PC3, an **NF-PC**, proves the host route; a ping from PC3 to PC1 must still fail.',
  ),

  'ccna2-31-default-and-floating-routes': md(
    '## The idea in one breath',
    '',
    'A default route matches every destination, so a router sends whatever it cannot place anywhere else to one neighbour. A floating route is a second route to the same place with a worse distance: it stays out of the table until the better route disappears.',
    '',
    '## Why it exists',
    '',
    'A branch office usually has one way out. Listing every network of the company and the internet would never end; one line saying "anything else, that way" never goes stale. Many branches also keep a slower second link for when the main one fails, and its route is written in advance so nobody has to type it at night.',
    '',
    '## How it actually works',
    '',
    'The default route is a static route to network `0.0.0.0` with mask `0.0.0.0`. Its prefix length is zero, so it matches every address and loses to every other match, exactly as a last resort should.',
    '',
    'A floating route reuses the distance rule: of two routes to one prefix, only the lower distance is installed. Here the main link leads to `172.16.1.2`, a slow serial link to `172.16.2.2`, and the backup has distance 10:',
    '',
    '```',
    'ip route 0.0.0.0 0.0.0.0 172.16.1.2',
    'ip route 0.0.0.0 0.0.0.0 172.16.2.2 10',
    '```',
    '',
    'While the main route is usable, the table shows only it. Shut the main interface, or lose its link, and the next hop no longer sits on a connected network: the main route leaves the table, the floating route takes its place, and traffic moves. When the link returns, the main route pushes the backup out again.',
    '',
    '## What trips people up',
    '',
    '- Giving the backup the same distance as the main route. Both are then installed as equal-cost paths, and some conversations use the slow link all the time.',
    '- Expecting a floating route to notice every failure. A static route only leaves the table when the router can see the fault: its own interface down, or its next hop unreachable. A failure further away leaves the backup waiting.',
    '- Forgetting the way back. The router at the other end needs its own main and floating routes, or its replies keep going down the dead link.',
    '',
    '## See it in NetForge',
    '',
    'The lab joins two **NF-2911** routers with a fast Ethernet link and a slow serial one:',
    '',
    '- `show ip route` marks the default route `S*` and names it on the line above the table.',
    '- `show ip route static` shows only the routes in use; a floating route waits in `show running-config`.',
    '- `shutdown` on R1\'s `GigabitEthernet0/1`, then `show ip route` again: the serial routes have taken over. `no shutdown` brings the main routes back.',
    '- `ping 198.51.100.10` from PC1, an **NF-PC**, before and after the failure proves both paths.',
  ),

  'ccna2-32-ipv6-static-routes': md(
    '## The idea in one breath',
    '',
    'IPv6 static routes follow the IPv4 rules, written with a prefix length instead of a mask. The one new idea is the link-local next hop: an address that means something only on one link, so a route that uses it must also name the link.',
    '',
    '## Why it exists',
    '',
    'Most networks now run both address families side by side, each with a routing table of its own, and a router that routes IPv4 perfectly forwards no IPv6 until it is told to. Every IPv6-enabled interface has a link-local address whether or not it has a global one, which makes it a stable next hop: the neighbour\'s global prefix can be renumbered, its link-local address usually stays.',
    '',
    '## How it actually works',
    '',
    'A router forwards IPv6 only after `ipv6 unicast-routing`; without it, it also sends no router advertisements, so self-configuring hosts behind it get no global address. The route forms then mirror IPv4. Here a router reaches the LAN `2001:db8:3::/64` behind a neighbour whose transit address is `2001:db8:23::3` and whose link-local address is `fe80::3`:',
    '',
    '```',
    'ipv6 route 2001:db8:3::/64 2001:db8:23::3',
    'ipv6 route 2001:db8:3::/64 GigabitEthernet0/1 fe80::3',
    'ipv6 route ::/0 2001:db8:23::3',
    '```',
    '',
    'The first line names a global next hop. The second names a link-local next hop with its exit interface, a fully specified route and the usual form with link-local addresses. The third is the IPv6 default route, `::/0`. An exit interface alone suits a point-to-point link, as in IPv4.',
    '',
    'A link-local next hop needs its interface because every link has its own link-local range: a router with three links could have three neighbours all called `fe80::3`. Longest match and administrative distance work as in IPv4, and a distance at the end of the line makes a floating IPv6 route.',
    '',
    '## What trips people up',
    '',
    '- Forgetting `ipv6 unicast-routing`. The router keeps its addresses and answers pings, but forwards nothing.',
    '- A link-local next hop without its interface. NetForge stores the line but never installs the route.',
    '- Looking in the wrong table. `show ip route` holds only IPv4; IPv6 routes are in `show ipv6 route`.',
    '- Working IPv4 routes say nothing about IPv6: each family needs its own way there and back.',
    '',
    '## See it in NetForge',
    '',
    'In the lab, R1 and R2 are **NF-2911** routers and the hosts are **NF-PC** workstations:',
    '',
    '- `show ipv6 route` beside `show ip route` on each router: one table per family, static routes marked `S`.',
    '- `show ipv6 interface brief` lists each interface\'s link-local and global addresses; on the transit link R1 is `fe80::1` and R2 `fe80::2`.',
    '- `ipv6config` on PC2 prints the address it built from the advertisements.',
    '- `ping -6 2001:db8:12::2` from PC1 reaches R2 only once R2 has its route back to PC1\'s LAN.',
  ),

  'ccna2-33-address-translation': md(
    '## The idea in one breath',
    '',
    'A translating router rewrites the source of packets leaving the inside network and reverses the change on the replies, so a few public addresses serve a whole private office.',
    '',
    '## Why it exists',
    '',
    'IPv4 addresses ran short, so most networks number their hosts from the private ranges, which the internet does not route. The edge router swaps a private source for a public one and remembers the swap for the way back.',
    '',
    '## How it actually works',
    '',
    '**Inside local** is a host\'s real address and **inside global** the public one it appears as; **outside global** is the far host\'s real address and **outside local** how the inside sees it, the same unless the outside is translated too.',
    '',
    'Mark the sides first, `ip nat inside` on the LAN interface and `ip nat outside` on the provider link: only packets crossing between them are translated. Then choose a kind:',
    '',
    '```',
    'ip nat inside source static 192.168.1.200 203.0.113.5',
    'access-list 1 permit 192.168.1.0 0.0.0.127',
    'ip nat pool P 203.0.113.20 203.0.113.29 netmask 255.255.255.0',
    'ip nat inside source list 1 pool P',
    '```',
    '',
    '- **Static** ties one host to one public address for good. With the port forward below, it is the only kind that lets the outside start a conversation.',
    '- **Dynamic** lends each host the list matches a whole pool address while it talks, lowest free first.',
    '- **PAT** adds `overload`, to a pool or to the outside interface as in `ip nat inside source list 1 interface GigabitEthernet0/1 overload`, so many hosts share one address. It also moves the source port (a ping\'s query id) when that is taken. One inside socket keeps one public port for every destination.',
    '- **Port forwarding** is a static line for one protocol and port: TCP 8080 on the outside address leads to port 80 of an inside server.',
    '',
    'The access list only picks who is translated; it blocks nothing. Idle dynamic rows expire, static rows never do.',
    '',
    '## What trips people up',
    '',
    '- Swapping inside and outside. Nothing is translated, and replies to a private source never come back.',
    '- A wildcard is the inverse of the mask: a /26 is `0.0.0.63`, not `255.255.255.192`.',
    '- A pool without overload lends one address per host; the eleventh host of a ten-address pool is dropped.',
    '',
    '## See it in NetForge',
    '',
    'On the lab\'s edge router R1, an **NF-2911**:',
    '',
    '- `show ip nat translations` lists every row with its four addresses; `show ip nat translations verbose` adds its kind, rule and time left.',
    '- `clear ip nat translation *` removes the dynamic rows; static ones stay.',
    '- The **Tables** tab of R1\'s inspector opens with an **Address translation** grid, inside and outside by local and global; the **Provenance** tab names the rule behind every rewritten field.',
  ),

  'ccna2-34-finding-faults': md(
    '## The idea in one breath',
    '',
    'Choose a method before you touch anything, gather facts with it, and change one thing at a time. A method turns "nothing works" into a short list of places to look.',
    '',
    '## Why it exists',
    '',
    'A switched and routed network can fail at a port, a VLAN, a trunk, an address at either end of a link, or a route in either direction. Guessing among them is slow, and a fix you stumble into teaches nothing. The process never changes: define the problem, gather information, analyse it, rule causes out, propose the likeliest, test it, and write down what you found.',
    '',
    '## How it actually works',
    '',
    'Three orders of attack cover most faults:',
    '',
    '- **Bottom up**: start at the ports and climb through VLANs and trunks, then addresses, then routes. Slow on a big network, but nothing is skipped: the right choice when you have no idea where to begin.',
    '- **Top down**: start from the failing application and walk down; good when others on the same switch work, so the lower layers are fine.',
    '- **Divide and conquer**: start in the middle with a ping. If a host reaches its gateway, its port, VLAN and addressing are fine and the fault is higher; if not, it is lower.',
    '',
    'Two habits sharpen any of them. **Follow the path**: walk one failing packet hop by hop, asking at each device which port, VLAN and next hop it would take, and whether the reply would come back. **Compare**: a device set up like one that works shows the odd line out.',
    '',
    'Each symptom points at a layer. Two hosts on one switch that cannot reach each other point at a port or a VLAN, never at a route. A router that cannot ping its neighbour points at the addresses on that link. A router that knows no way there points at its routing table.',
    '',
    '## What trips people up',
    '',
    '- Changing several things at once: when it works again you cannot tell which change mattered.',
    '- Adding instead of repairing. A new route that hides a mistyped one leaves the real fault in place.',
    '- Forgetting the return path. Every test needs the reply to come home.',
    '',
    '## See it in NetForge',
    '',
    'The lab breaks one thing per layer across **NF-C2960** switches, **NF-2911** routers and **NF-PC** hosts:',
    '',
    '- Ports: `show interfaces status` and `show interfaces status err-disabled` on each switch.',
    '- Addresses: `show ip interface brief` on both routers. Do the two ends of each link share a subnet?',
    '- Routes: `show ip route`. Does each router know the other site\'s LAN, under the right network?',
    '- `tracert 192.168.20.100` from PC1 shows how far a packet gets; the **Events** tab records when a port was error-disabled and why.',
  ),
};
