/**
 * curriculum/ccna2/theory-a.ts — plain-language theory for the first part of CCNA 2 (lessons 01-11: switches, VLANs,
 * routing between VLANs), keyed by the lesson ids of `ccna2/lessons.ts`. `theory-b.ts` carries 12-21 and
 * `theory-c.ts` 22-24 and 29-34; `theory.ts` merges the three (ARCHITECTURE-P2 §7 W6 course, §11.1, §11.3).
 *
 * Same shape, voice and markdown subset as `curriculum/ccna1/theory-a.ts`: headings, lists, emphasis, code and fenced
 * code, links limited to `concept:subnetting`, `concept:ipv6` and https — the parser treats raw HTML as a security
 * boundary, so there is not an angle bracket in this file. All prose is original and names no vendor; protocol names
 * that are CCNA vocabulary (VTP, DTP) appear as names only.
 *
 * Every body has the same five sections — idea, why, how, trap, see it here — so a learner who has read one knows
 * where to look in all the others.
 *
 * Two rules the bodies keep, both pinned by `test/curriculum.ccna2.commands.test.ts`:
 * - every command in backticks parses in `GRAMMAR` on a model the lesson names: the models of its lab, or for a
 *   lesson without one the models listed for it in that test (01, 04: NF-C2960 and NF-PC; 03: plus NF-2911; 08: plus
 *   NF-IPPHONE), or a model the body names itself;
 * - every address line (`ip address …`, `ip default-gateway …`) printed for a lesson with a lab is a line of that lab's
 *   reference solution, so a learner who copies it passes the task. Prose therefore writes "address", never the
 *   lower-case command words, and a lab-less lesson prints no address lines at all.
 *
 * Items NetForge does not build stay theory, and each body says so where a learner could look for them: VTP (05), the
 * neighbour-discovery protocol that hands a phone its voice VLAN (08), and a remote-login client (02).
 *
 * ponytail: a `md(...)` join, as in CCNA 1, because the bodies are full of backticks and escaping them once per
 * inline code span would be noise.
 */
import type { LessonTheoryMap } from '../../contracts/curriculum.js';

/** One lesson body from its lines (the labs build `instructions` the same way). */
const md = (...lines: string[]): string => lines.join('\n');

export const THEORY_A: LessonTheoryMap = {
  'ccna2-01-how-a-switch-forwards': md(
    '## The idea in one breath',
    '',
    'A switch forwards from memory. It notes the port every sender lives on, sends each frame only where its destination lives, and forgets addresses that fall silent. On a switch with VLANs it keeps that memory once per VLAN, as if each VLAN had a switch of its own.',
    '',
    '## Why it exists',
    '',
    'Copying every frame to every port would work, and it is what a hub did: each conversation used every cable in the room. Remembering locations lets twenty conversations run at once on twenty ports. Keeping the memory per VLAN is what keeps VLANs apart: a frame of VLAN 10 only ever reaches ports that carry VLAN 10.',
    '',
    '## How it actually works',
    '',
    'An arriving frame first gets a VLAN: its port\'s access VLAN, or on a trunk its tag or the native VLAN. Then five rules apply.',
    '',
    '- **Learn.** The source address goes into the table with that VLAN and the arrival port.',
    '- **Forward.** A destination the table knows in the same VLAN leaves by that one port.',
    '- **Filter.** A destination that lives on the port the frame came in on goes nowhere; it has already arrived.',
    '- **Flood.** A broadcast, or a destination the table does not know yet, is copied to every other port that carries the VLAN, and to no port of any other VLAN.',
    '- **Age.** An entry that is not refreshed for five minutes is removed. Entries also go at once when their port goes down or moves to another VLAN, so a machine that moved is found again by the next flood.',
    '',
    'The key of the table is the VLAN and the address together, so one address can appear twice. A router serving two VLANs over one trunk uses the same hardware address in both, and the switch lists it once in VLAN 10 and once in VLAN 20, both against the trunk port.',
    '',
    '## What trips people up',
    '',
    'Expecting a frame for an unknown destination to reach the whole switch. It floods only inside its own VLAN, so a machine in the wrong VLAN never hears it, even on the next port. The empty table is not the fault; the VLAN is.',
    '',
    '## See it in NetForge',
    '',
    '- Cable two **NF-PC** workstations to an **NF-C2960**, give the new ports half a minute to start forwarding, ping from one to the other, then run `show mac address-table` on the switch.',
    '- `show mac address-table vlan 1` narrows the list to one VLAN, and `show mac address-table count` counts the entries.',
    '- `clear mac address-table dynamic` empties the table. Ping again and watch the first frame flood in the **Packets** tab.',
    '- The **Tables** tab shows the same table live, with its VLAN column.',
  ),

  'ccna2-02-managing-a-switch': md(
    '## The idea in one breath',
    '',
    'A switch forwards frames without an address of its own, but you cannot manage what you cannot reach. One address on a VLAN interface, plus a default gateway for its replies, lets you manage it from anywhere.',
    '',
    '## Why it exists',
    '',
    'Walking to every wiring closet with a console cable stops working after a handful of switches. A management address lets an administrator check and change any switch from a desk, and lets monitoring tools ask it how it is doing. Putting that address in a VLAN kept for management, rather than in VLAN 1 where every port starts, keeps ordinary users away from it.',
    '',
    '## How it actually works',
    '',
    'A layer 2 switch has no routed ports, so its address lives on a virtual interface named after a VLAN, `interface Vlan99`. That interface starts shut down, and it has a second condition: it only comes up while VLAN 99 exists and at least one port of VLAN 99 is up and forwarding. In the lab the switch takes `ip address 192.168.99.2 255.255.255.0` there, then `no shutdown`.',
    '',
    'That is enough for a technician on the same subnet. It is not enough for an administrator one router away: the request arrives, but the switch has no route for the reply, because a switch that does not route keeps no routing table. `ip default-gateway 192.168.99.1` fixes that. The switch uses the gateway only for traffic it sends itself; it never forwards anyone else\'s packets through it.',
    '',
    'Remote sessions arrive on the virtual terminal lines. `line vty 0 4` selects the first five, and `login local` makes them ask for a user name and password from the switch\'s own user list, which a username line in global configuration fills.',
    '',
    '## What trips people up',
    '',
    'Addressing the switch, pinging it from the same subnet, and calling the job done. The failure only shows from another subnet, and it looks like a fault on the router. The router is fine: the switch is a host without a gateway.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Manage a switch from another subnet** from the **Labs** tab.',
    '- On SW1: `interface Vlan99`, `ip address 192.168.99.2 255.255.255.0`, `no shutdown`, then `show ip interface brief`.',
    '- `ping 192.168.99.2` from TECH1 and then from ADMIN1. Add `ip default-gateway 192.168.99.1` on SW1 and try ADMIN1 again.',
    '- NetForge has no remote-login client yet: `show running-config` shows the line settings, and the pings prove the switch can be reached.',
  ),

  'ccna2-03-speed-duplex-and-cabling': md(
    '## The idea in one breath',
    '',
    'Before a copper link carries a frame, its two ends agree on a speed and on whether both may talk at once, and the right wire pairs have to face each other. Left alone, modern ports settle all of it. Forced by hand on one end only, they get it wrong.',
    '',
    '## Why it exists',
    '',
    'Ethernet has run at 10, 100 and 1000 Mb/s, on shared cable and on point-to-point cable, and all of those ports still meet in the same buildings. Autonegotiation lets two ends list what they can do and pick the best they share. Automatic crossover exists because what one end transmits must land on the pair the other end receives on, and nobody wants to remember which cable that takes.',
    '',
    '## How it actually works',
    '',
    'Each end advertises its speeds and duplex modes, and both take the fastest speed and full duplex when they share them. `speed 100` or `duplex full` on its own shortens the list a port advertises but keeps it negotiating. Set both and the port stops negotiating. The far end, still on auto, can measure the speed from the signal but cannot learn the duplex, so below 1 Gb/s it falls back to half duplex. One end now sends whenever it likes while the other backs off from what it takes for collisions: a **duplex mismatch**. Pin two ends to different speeds and the link never comes up at all.',
    '',
    'Cabling follows the same idea. A computer or router port transmits on one pair and a switch port on the other, so a straight-through cable joins a host to a switch, and two ports of the same kind need a crossover cable. A port with **automatic crossover** swaps its pairs itself and accepts either cable. In NetForge the ports of an NF-C2960 do; router and computer ports do not.',
    '',
    '## What trips people up',
    '',
    'Hard-coding one end "for stability". It creates the fault it was meant to prevent: the link stays up and small pings answer, while throughput collapses and error counters climb. Set both ends the same way, or leave both on auto.',
    '',
    '## See it in NetForge',
    '',
    '- `show interfaces status` on a switch lists the speed and duplex every port settled on.',
    '- Cable an **NF-2911** to a switch port, set `speed 100` and `duplex full` on the switch end only, and push traffic across. `show interfaces GigabitEthernet0/0` on the router, which fell back to half duplex, counts late collisions; `show interfaces FastEthernet0/1` on the switch counts short, damaged frames.',
    '- Draw a straight-through cable from a router to a workstation: NetForge refuses it and says why. A crossover cable works.',
  ),

  'ccna2-04-why-split-a-lan': md(
    '## The idea in one breath',
    '',
    'A VLAN cuts one physical switch into several logical ones. Ports in different VLANs behave as if they sat on different switches with no cable between them, even when they are neighbours on the same box.',
    '',
    '## Why it exists',
    '',
    'A flat network grows until its broadcasts reach every machine, every unknown frame floods everywhere, and any machine can reach any other with nothing in between. Giving each department its own switches would fix that, at the price of more hardware and a trip to the closet for every move. VLANs give the same separation in configuration: moving a desk to another department is one line on one port.',
    '',
    '## How it actually works',
    '',
    'A VLAN separates three things. **Broadcasts**: an ARP request or an address request from VLAN 10 is flooded only to ports that carry VLAN 10. **The address table**: the switch keeps its memory per VLAN and never forwards a frame into another VLAN. **The reach of a fault**: a machine that floods junk or carries a wrong address disturbs its own VLAN only.',
    '',
    'Because each VLAN is its own broadcast domain, it is also its own subnet. VLAN 10 might be `192.168.10.0/24` and VLAN 20 `192.168.20.0/24`, and traffic between them must be routed, which is where the next module picks up.',
    '',
    'Some things stay shared. The switch itself, its power and its processor serve every VLAN. A trunk carries several VLANs over one cable, so they share its capacity. And once a router joins two VLANs, they reach each other again at layer 3, on purpose.',
    '',
    'Every port starts in VLAN 1, the default VLAN. VLANs are also named by their job: a data VLAN for users, a management VLAN for the switches themselves, a voice VLAN for phones, and the native VLAN of a trunk.',
    '',
    '## What trips people up',
    '',
    'Treating a VLAN as a security boundary on its own. It separates layer 2 and nothing more: a router that joins two VLANs joins them completely unless something filters on the router, and a port left in the wrong VLAN quietly puts a machine inside another department.',
    '',
    '## See it in NetForge',
    '',
    '- Cable two **NF-PC** workstations in `192.168.1.0/24` to an **NF-C2960**, wait half a minute for the new ports to forward, and ping from one to the other. Then move one port with `switchport access vlan 20`: the ping stops, although no cable, address or mask changed.',
    '- `show vlan brief` lists every VLAN and its ports.',
    '- In the **View** menu, the **VLANs** overlay tints every port by its VLAN, and **Focus on VLAN** dims whatever does not carry the VLAN you pick.',
  ),

  'ccna2-05-access-ports-and-the-vlan-list': md(
    '## The idea in one breath',
    '',
    'A VLAN exists on a switch once it is in the switch\'s VLAN list, and a port belongs to it once the port is an access port of that VLAN. Everything else in this module builds on those two facts.',
    '',
    '## Why it exists',
    '',
    'A port needs a home before it carries anything, and the VLAN list gives each home a number and a name people can read. Across many switches the lists must agree, which is why a protocol was invented to copy them around, and why that protocol is best known for its accidents.',
    '',
    '## How it actually works',
    '',
    '`vlan 10` creates VLAN 10 and enters it, and `name SALES` labels it. Numbers 1 to 1005 are the normal range, 1006 to 4094 the extended range, and VLAN 1 and 1002 to 1005 are built in: they can be neither created nor removed. On a port, `switchport mode access` fixes the mode so it never becomes a trunk, and `switchport access vlan 10` picks the VLAN, creating it if it is missing. `interface range FastEthernet0/1 - 2` applies the same lines to several ports at once. A real switch keeps its VLAN list in a database file of its own; NetForge keeps it in the running configuration, one section per VLAN.',
    '',
    '**VTP** copies a VLAN list between the switches of one domain. A *server* changes the list and advertises it, a *client* takes what it hears, and a *transparent* switch keeps its own list and passes the adverts on; version 3 adds an *off* mode and lets only one primary server make changes. Every change raises a revision number, and servers and clients take any list with a higher number. Plug in a spare switch that has seen more changes and its old list can replace the VLAN list everywhere, stranding every port whose VLAN vanished. NetForge does not run VTP: each switch keeps its own list, like a transparent one.',
    '',
    '## What trips people up',
    '',
    'Deleting a VLAN before moving its ports. `no vlan 30` removes the VLAN but not the ports\' setting, so they stay in a VLAN that no longer exists and forward nothing until they get a new one.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Create VLANs and assign access ports**.',
    '- On SW1: `vlan 10`, `name SALES`, `exit`, and the same for VLAN 20 with `name STAFF`.',
    '- `interface range FastEthernet0/3 - 5`, `switchport mode access`, `switchport access vlan 20`, then `no vlan 30`.',
    '- `show vlan brief` lists each VLAN with its ports, and `show interfaces FastEthernet0/5 switchport` shows one port in detail.',
  ),

  'ccna2-06-trunks-and-tags': md(
    '## The idea in one breath',
    '',
    'A trunk is one link that carries many VLANs. Each frame on it wears a small tag naming its VLAN, so the far switch knows where the frame belongs. One VLAN, the native VLAN, crosses without a tag.',
    '',
    '## Why it exists',
    '',
    'Without trunks, stretching three VLANs across two switches takes three cables and an access port per VLAN at each end, and every new VLAN takes another pair. A trunk carries them all on one link, so adding a VLAN is a line of configuration. The same idea connects a switch to a router.',
    '',
    '## How it actually works',
    '',
    'The 802.1Q tag is four bytes inserted after the source address: a type value that marks the tag, three priority bits, one flag bit and a 12-bit VLAN number, which is where the 4094 usable VLANs come from. The sending switch adds the tag as the frame leaves on the trunk, the receiving switch reads it, and an access port removes it before the frame reaches a host. No host ever sees a tag.',
    '',
    '`switchport mode trunk` makes a port a static trunk. `switchport trunk native vlan 99` picks the VLAN that crosses untagged: a frame that arrives without a tag is placed in it, so both ends must agree. Switches running spanning tree notice when they do not: NetForge blocks both VLANs involved on that port and logs a native VLAN mismatch. A trunk carries every VLAN by default. `switchport trunk allowed vlan 10,20,99` replaces that with exactly the list typed, and `switchport trunk allowed vlan add 30` adds one VLAN to it.',
    '',
    '## What trips people up',
    '',
    '- Typing an allowed list without `add` when you meant to add one VLAN. The new list replaces the old one, and every VLAN left out stops crossing at once.',
    '- Testing the moment the trunk is up. Spanning tree runs on these switches, so a port that starts trunking listens and learns for 30 seconds before it forwards.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Build a trunk: native VLAN and allowed list**.',
    '- On both switches: `interface GigabitEthernet0/1`, `switchport mode trunk`, `switchport trunk native vlan 99`, `switchport trunk allowed vlan 10,20,99`.',
    '- `show interfaces trunk` lists the mode, the native VLAN and the VLANs allowed and forwarding on every trunk.',
    '- Ping PC3 from PC1, select an echo request and open the **Provenance** tab: SW1 pushed the VLAN 10 tag and SW2 popped it.',
  ),

  'ccna2-07-trunk-negotiation': md(
    '## The idea in one breath',
    '',
    'Two switch ports can talk each other into becoming a trunk. Whether they do depends on the mode at each end, and the safest ports are the ones that never ask and never answer.',
    '',
    '## Why it exists',
    '',
    'Negotiation was meant to save typing: plug two switches together and the link trunks by itself. The price is that anything able to speak the protocol, DTP, can ask a willing port for a trunk, and a trunk carries every VLAN. That is why careful networks switch negotiation off almost everywhere.',
    '',
    '## How it actually works',
    '',
    'A switch port has four modes. `switchport mode access` never trunks. `switchport mode trunk` always trunks and still sends negotiation messages. `switchport mode dynamic desirable` asks for a trunk. `switchport mode dynamic auto` waits to be asked, and it is the default. The outcome of any pair follows:',
    '',
    '- desirable facing desirable, auto or a trunk: **trunk**;',
    '- auto facing a trunk: **trunk**;',
    '- auto facing auto: **access**, because both wait and nobody asks;',
    '- access facing anything: **access** at that end. If the far end is a fixed trunk, the two ends disagree and the link carries traffic badly or not at all.',
    '',
    '`switchport nonegotiate` stops a port from sending or answering negotiation messages. It is accepted only on a port fixed as access or trunk, and a fixed trunk that does not negotiate must face another fixed trunk: a dynamic neighbour hears nothing and stays an access port.',
    '',
    'NetForge exchanges these messages in a format of its own, a port in auto never speaks first, and a trunk forms one exchange after the link comes up.',
    '',
    '## What trips people up',
    '',
    'Leaving user-facing ports at the default. A port in auto becomes a trunk the moment a device plugged into it asks for one, and whoever plugged it in now sees every VLAN. Fix every host port as access, and switch negotiation off on it.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Negotiate trunks, and refuse one** and predict each link before you look.',
    '- `show interfaces trunk` lists the ports that trunk; `show dtp interface FastEthernet0/24` shows a port\'s mode, where its negotiation stands and what the neighbour asked for.',
    '- Give SW1 `GigabitEthernet0/1` the line `switchport mode dynamic desirable` and watch the link to SW2 trunk. On `FastEthernet0/24`, `switchport mode access` followed by `switchport nonegotiate` shuts the visitor out.',
  ),

  'ccna2-08-voice-vlans': md(
    '## The idea in one breath',
    '',
    'A desk phone and the computer plugged in behind it share one switch port but not one VLAN. The phone tags its own traffic with a voice VLAN, while the computer\'s traffic stays untagged in the port\'s ordinary data VLAN.',
    '',
    '## Why it exists',
    '',
    'Offices had one cable per desk long before they had network phones, and pulling a second cable to every desk was never going to happen. Voice still needs things data does not: its own subnet and address pool, its own treatment when links are busy, and shelter from a computer\'s bursts of traffic. A second VLAN on the same port gives voice all of that on the cable already there.',
    '',
    '## How it actually works',
    '',
    'The phone holds a tiny switch with two ports, one to the wall and one for the computer. On the switch port, `switchport mode access` and `switchport access vlan 10` set the data VLAN as usual, and `switchport voice vlan 150` adds the voice VLAN. The port stays an access port, but it now accepts and sends frames tagged with VLAN 150 beside the untagged frames of VLAN 10. The phone tags its own frames with 150, and the priority bits of that tag let switches favour voice on a busy link. The computer\'s frames pass through the phone untouched and arrive untagged, in VLAN 10.',
    '',
    'Real phones usually learn their voice VLAN from the switch through a neighbour-discovery protocol that belongs to a later course. In NetForge you set it on the phone by hand: `voice vlan 150` at the phone\'s prompt, or the Voice VLAN field of its **IP configuration** app.',
    '',
    '## What trips people up',
    '',
    '- Forgetting the VLAN itself. The switch accepts `switchport voice vlan 150` before VLAN 150 exists, prints a note, and the phone\'s tagged frames are dropped until the VLAN is created.',
    '- Trunking the port for the phone\'s sake. A trunk carries every VLAN to the desk; an access port with a voice VLAN carries exactly two.',
    '',
    '## See it in NetForge',
    '',
    '- Cable an **NF-IPPHONE** to an **NF-C2960**, and an **NF-PC** to the phone\'s second port.',
    '- On the switch: `vlan 150`, `name VOICE`, then on the phone\'s port `switchport access vlan 10` and `switchport voice vlan 150`.',
    '- `show interfaces FastEthernet0/1 switchport` lists the access VLAN and the voice VLAN of the port.',
    '- Set `voice vlan 150` on the phone. Neither the phone nor the computer sends anything until it has an address, so give the phone an address in a voice subnet and the computer one in a data subnet with their **IP configuration** apps, and ping another address of its own subnet from each.',
    '- Capture in **NetScope** while they ping: the phone\'s frames carry a VLAN 150 tag, the computer\'s carry none. The tagged spanning-tree frames in the capture come from the switch, one per VLAN, not from the phone.',
  ),

  'ccna2-09-router-on-a-stick': md(
    '## The idea in one breath',
    '',
    'Hosts in different VLANs sit in different subnets, so only a router can join them. The router can have one port in each VLAN, or one port on a trunk with a subinterface per VLAN. The second way is called router-on-a-stick.',
    '',
    '## Why it exists',
    '',
    'The obvious method cables one router port to an access port of each VLAN and gives each router port the gateway address of its VLAN. It works, and it runs out of router ports after a few VLANs. One trunk to the router carries every VLAN on one cable, and the router splits it into logical interfaces, one per VLAN, with no extra hardware.',
    '',
    '## How it actually works',
    '',
    'On the switch, the port facing the router becomes a trunk with `switchport mode trunk`, and since a router does not negotiate trunks, `switchport nonegotiate` stops the switch asking. On the router the physical port only gets `no shutdown`; it carries no address. Each VLAN gets a subinterface, and its first line is the tag it answers to:',
    '',
    '```',
    'interface GigabitEthernet0/0.10',
    ' encapsulation dot1Q 10',
    ' ip address 192.168.10.1 255.255.255.0',
    '```',
    '',
    'The native VLAN arrives untagged, so its subinterface carries the extra keyword: `encapsulation dot1Q 99 native`. Each subinterface is the default gateway of its VLAN.',
    '',
    'A packet from VLAN 10 to VLAN 20 goes up the trunk tagged 10, loses the tag at the router, is routed with its TTL one lower, and comes back down the same cable tagged 20. That round trip is the limit of the method: all traffic between VLANs shares one link, in both directions.',
    '',
    '## What trips people up',
    '',
    '- Giving the address before the encapsulation. A subinterface without its tag belongs to no VLAN, and NetForge refuses the address until the encapsulation line is in.',
    '- Trusting the subinterface number. It is only a name; the router answers the VLAN of the encapsulation line.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Route between VLANs on a stick**.',
    '- On R1, add `interface GigabitEthernet0/0.20` with `encapsulation dot1Q 20` and `ip address 192.168.20.1 255.255.255.0`, then `interface GigabitEthernet0/0.99` with `encapsulation dot1Q 99 native` and `ip address 192.168.99.1 255.255.255.0`.',
    '- `show ip interface brief` lists each subinterface, and `show ip route` one connected network per VLAN.',
    '- Ping PC2 from PC1 and open the **Provenance** tab: the tag removed, the TTL lowered and the new tag added are all there.',
  ),

  'ccna2-10-multilayer-switching': md(
    '## The idea in one breath',
    '',
    'A multilayer switch is a switch with a router inside. Give each VLAN a VLAN interface holding its gateway address, switch routing on, and packets move between VLANs without leaving the box.',
    '',
    '## Why it exists',
    '',
    'Router-on-a-stick squeezes all traffic between VLANs through one cable and one router. A multilayer switch routes in the same hardware that switches, at the speed of its ports, and each VLAN interface costs nothing but a few lines. Most campus networks route between their VLANs this way.',
    '',
    '## How it actually works',
    '',
    '**VLAN interfaces.** `interface Vlan10` with `ip address 192.168.10.1 255.255.255.0` and `no shutdown` becomes the gateway of VLAN 10. It comes up only while VLAN 10 exists and one of its ports is up and forwarding.',
    '',
    '**Routing.** The switch answers for its own addresses from the start, but forwards between them only after `ip routing`. Many multilayer switches ship with routing off, and in a new NetForge world they start with `no ip routing`.',
    '',
    '**Routed ports.** `no switchport` turns a port into a router interface that belongs to no VLAN, the clean way to uplink to a router. It takes `ip address 10.0.0.1 255.255.255.252`, and a default route, `ip route 0.0.0.0 0.0.0.0 10.0.0.2`, sends everything else up that link.',
    '',
    'One more piece keeps address assignment working. A host asking for an address broadcasts, and a broadcast never crosses a routed interface. So each VLAN interface relays the requests of its own VLAN with `ip helper-address 10.0.0.2`, writing its own address into them so the server picks the pool of that VLAN. Lesson 18 comes back to this.',
    '',
    '## What trips people up',
    '',
    '- Forgetting `ip routing`. Every host pings its own gateway perfectly, the switch looks healthy, and nothing reaches the other VLAN.',
    '- A VLAN interface that stays down with an address and `no shutdown` on it: its VLAN does not exist on this switch, or none of its ports is up.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Route between VLANs on a multilayer switch**; MLS1 is an **NF-C3650-24**.',
    '- Build `interface Vlan20` with `ip address 192.168.20.1 255.255.255.0`, `ip helper-address 10.0.0.2` and `no shutdown`, then type `ip routing`.',
    '- On `GigabitEthernet1/0/24`: `no switchport`, then its address.',
    '- Set each PC to `ip address dhcp`, check the lease with `ipconfig`, and read `show ip route` on MLS1.',
  ),

  'ccna2-11-fixing-inter-vlan-routing': md(
    '## The idea in one breath',
    '',
    'A packet between two VLANs needs every step right: the access port, each trunk on the way, the gateway interface and the host itself. Fault finding means checking those steps in order instead of guessing.',
    '',
    '## Why it exists',
    '',
    'Inter-VLAN faults all look alike from the keyboard: a ping that fails. What differs is which pings fail. Reading that pattern first tells you where to look, and checking one step at a time stops you changing three things at once without learning which one mattered.',
    '',
    '## How it actually works',
    '',
    'Start from the symptom, then walk the path.',
    '',
    '- **A host reaches nobody, not even its own VLAN.** Its access port is probably in the wrong VLAN. `show vlan brief` lists the ports of each VLAN, and the address of the host tells you which VLAN its port belongs in.',
    '- **A host reaches its own switch but not its gateway, while a host of the same VLAN on another switch can.** A trunk on the way leaves that VLAN out. `show interfaces trunk` lists, at each end, the VLANs allowed, existing and forwarding; a VLAN missing at either end is missing.',
    '- **One VLAN reaches nobody outside itself.** Its gateway is down or wrong. `show ip interface brief` on the router lists every subinterface with its state, and `admin down` means someone typed `shutdown` there. On a multilayer switch, check the VLAN interface and `ip routing` instead.',
    '- **Nothing crosses at all.** The trunk to the router is not trunking, or the router\'s physical port is shut, which takes every subinterface down with it.',
    '',
    'Repair each fault on the device where it lies. Moving a host into the subnet of the wrong VLAN makes its ping work and leaves the fault in place.',
    '',
    '## What trips people up',
    '',
    '- Repairing an allowed list by retyping it. `switchport trunk allowed vlan add 30` adds one VLAN; the same line without `add` replaces the list and can cut off VLANs that were working.',
    '- Testing straight after a repair. A trunk that starts carrying a VLAN again spends 30 seconds listening and learning in it before it forwards.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Repair inter-VLAN routing** and read the three symptoms before you open a terminal.',
    '- `show vlan brief` and `show interfaces trunk` on both switches, `show ip interface brief` on R1.',
    '- `show interfaces FastEthernet0/1 switchport` shows the mode and VLAN of one port in detail.',
    '- After each repair, ping again from the hosts; **Check my work** grades the three faults one by one.',
  ),
};
