/**
 * curriculum/ccna2/theory-b.ts — plain-language theory for the second part of CCNA 2 (lessons 12-21: spanning tree,
 * EtherChannel, addressing services, gateway redundancy), keyed by the lesson ids of `ccna2/lessons.ts`. `theory-a.ts`
 * carries 01-11 and `theory-c.ts` 22-24 and 29-34; `theory.ts` merges the three.
 *
 * Same markdown subset, five sections and rules as `curriculum/ccna1/theory-a.ts` (ARCHITECTURE-P2 §11.1, §11.3):
 * headings, lists, emphasis, code and https links only, no raw markup, original wording, no vendor. Every backticked
 * command is one the learner can type in NetForge on the model the lesson names (`cli/grammar/*`), and every address
 * line printed for a lesson with a lab is a line of that lab's reference solution (`sim/scenarios/ccna2/*`), so the
 * learner never copies a line the lab would not accept.
 *
 * Content decisions (§8.5, §11.1, §11.4):
 * - The five spanning-tree lessons (12-16) each say that real switches run spanning tree by default and that a
 *   project saved before this course keeps "classic defaults" until File → "Use current defaults" (D2, §4.4).
 * - MST (lesson 15) and loop guard (lesson 16) are theory only, said so in the text, with no command printed: C2 and
 *   S5 are not built. PAgP (lesson 17, S3) and HSRP (lessons 20-21, S2) are built and are taught hands-on.
 * - Lesson 18 has no lab of its own; it is practised in lesson 10's lab and prints only lines of that lab.
 * - Lesson 21 prints the host line of its lab (`ip address <a> <mask> <virtual gateway>`), never the router
 *   addresses, which are in the lab's startup configuration rather than its solution.
 *
 * ponytail: the `md(...)` join of theory-a (a line of markdown is a line of source, no escaped backticks), and no
 * apostrophes in the prose, as in the CCNA 1 bodies, so every line stays a plain single-quoted string.
 */
import type { LessonTheoryMap } from '../../contracts/curriculum.js';

/** One lesson body from its lines (the labs build `instructions` the same way). */
const md = (...lines: string[]): string => lines.join('\n');

/** Lesson bodies 12-21. Keys match ids in `ccna2/lessons.ts`, in teaching order. */
export const THEORY_B: LessonTheoryMap = {
  'ccna2-12-what-a-loop-does': md(
    '## The idea in one breath',
    '',
    'Two switches joined by two cables have two paths between them, and a frame that can go round in a circle will. Nothing in an Ethernet header counts hops, so a looping frame never dies. Spanning tree switches off just enough ports to break the circles.',
    '',
    '## Why it exists',
    '',
    'With one path between each pair of switches, one cut cable takes a floor offline. A second uplink is the obvious fix, and it closes a loop. An IP packet carries a time-to-live that routers count down, so a routing loop dies out. A frame has no such field, so spare cables need a protocol that keeps them from forming a circle.',
    '',
    '## How it actually works',
    '',
    'Cable SW1, SW2 and SW3 in a triangle and let PC1 on SW1 send an ARP request, which is a broadcast. SW1 floods it out of both uplinks, and each copy is passed on round the triangle. A switch floods a broadcast out of every port but the one it arrived on, so the two copies circle forever in opposite directions and each new broadcast adds two more. The links fill up: a **broadcast storm**. The MAC table flaps too, as the address of PC1 keeps arriving on one port and then another, and a unicast frame for an unlearned machine is delivered more than once.',
    '',
    'Spanning tree prevents all of it. The switches exchange small messages called BPDUs, agree on one **root bridge**, and each keeps only its best path towards it. One port on the link that closes the circle is put into **blocking**: it hears BPDUs but drops every user frame. The loop is gone, the cable stays plugged in, and if an active link fails the blocked port takes over.',
    '',
    '## What trips people up',
    '',
    '- A blocked port is not a broken port. Its link stays up, and only spanning tree knows it is holding frames back.',
    '- A loop needs no third switch: one cable between two ports of one switch, or a small switch added under a desk, is enough.',
    '',
    '## See it in NetForge',
    '',
    '- Real switches run spanning tree out of the box, and so does every switch in a new NetForge project. A project saved before this course keeps **classic defaults**, with no spanning tree, until File → **Use current defaults**.',
    '- Cable three **NF-C2960** switches in a triangle, wait half a minute, and turn on View → Switching overlays → **Spanning tree**: the root wears a crown and the blocked port a cross.',
    '- `show spanning-tree` on each switch gives the same answer as text.',
    '- Ping between two **NF-PC** hosts and open the **Packets** tab: each broadcast crosses each forwarding link once.',
  ),

  'ccna2-13-electing-a-root': md(
    '## The idea in one breath',
    '',
    'Every spanning tree starts with an election: the switch with the lowest **bridge ID** becomes the root, and every other switch works out its best path towards it. Left alone, the winner is whichever switch has the lowest MAC address, an accident of manufacturing rather than a design.',
    '',
    '## Why it exists',
    '',
    'A loop-free tree has to be measured from somewhere. One shared reference point lets every switch reach its own decisions from the same facts, with no central controller, and a plain comparison of numbers always gives exactly one answer.',
    '',
    '## How it actually works',
    '',
    'A bridge ID is a **priority**, 32768 by default, followed by the MAC address of the switch, which breaks ties. The lowest value wins. Per-VLAN spanning tree runs one tree for each VLAN and adds the VLAN number to the priority, so an untouched switch shows 32778 in VLAN 10. When switches first meet, each claims to be the root; a switch that hears a lower bridge ID stops claiming and passes the better news on, and within seconds the whole VLAN agrees.',
    '',
    'The root should sit in the middle of the traffic, usually on a distribution switch, because every other switch forwards towards it. You move it by lowering a priority in steps of 4096, since the low part of the number is taken by the VLAN. `spanning-tree vlan 10 root primary` stores a priority that beats the current root: 24576, or 4096 below the root if that is already lower. `spanning-tree vlan 10 root secondary` stores 28672, which beats every untouched switch and so makes a backup root. `spanning-tree vlan 10 priority 24576` sets a number you choose.',
    '',
    '## What trips people up',
    '',
    '- A priority is set per VLAN. Moving the root of VLAN 10 does nothing for VLAN 20.',
    '- The shortcuts store a number once. A switch added later with a lower priority still wins.',
    '- A root with no backup is replaced by the next-lowest bridge ID, which is again decided by a MAC address while the priorities are untouched.',
    '',
    '## See it in NetForge',
    '',
    '- Real switches run spanning tree by default, and so does a new NetForge project; one saved before this course keeps **classic defaults** until File → **Use current defaults**.',
    '- The lab here puts three **NF-C2960** switches in a triangle where the access switch wins every election. Run `show spanning-tree vlan 10` on each one and find the root before you change anything.',
    '- `show spanning-tree root` lists the root of every VLAN in one table.',
    '- The View menu chooses which VLAN the **Spanning tree** overlay draws: switch between VLAN 10 and VLAN 20 and watch the crown move.',
  ),

  'ccna2-14-port-roles-states-and-timers': md(
    '## The idea in one breath',
    '',
    'Once the root is known, every port gets a **role**, what it is for, and a **state**, what it is doing now. In classic spanning tree a port about to forward first waits through two 15-second phases, so a freshly cabled port stays silent for half a minute.',
    '',
    '## Why it exists',
    '',
    'A switch hears only the BPDUs on its own ports, and news of a change takes time to travel. A port that forwarded at once might meet a switch that had not heard yet, and the loop would be back for a moment. The wait lets the news spread first.',
    '',
    '## How it actually works',
    '',
    'Each non-root switch picks one **root port**, the port with the lowest total cost to the root: a 1 Gb/s link costs 4 and 100 Mb/s costs 19. Each cable segment picks one **designated port**, the end with the lower cost to the root or, on a tie, on the switch with the lower bridge ID. Every port of the root is designated. A port left over is an **alternate** port, and it blocks.',
    '',
    'In a triangle rooted at SW1, both SW2 and SW3 use their direct link to SW1 as the root port. On the link between them both ends sit at cost 4, so the lower bridge ID decides: if that is SW2, its end is designated and the end on SW3 is the alternate.',
    '',
    '**Blocking** drops user frames but hears BPDUs. **Listening** (15 s, the forward delay) settles the role; **learning** (another 15 s) fills the MAC table without forwarding; then comes **forwarding**. The root sends BPDUs every 2 s, the hello time, and stored information expires after 20 s of silence, the max age. A failure on its own link costs a switch 30 s; one it only notices by silence, up to 50 s.',
    '',
    '## What trips people up',
    '',
    '- A port leading to a PC waits 30 s too: the switch cannot know only a host is behind it. That alone fails many first pings.',
    '- Cost is summed along the path: a slow direct link can lose to two fast hops.',
    '',
    '## See it in NetForge',
    '',
    '- Real switches run spanning tree by default, and so does a new NetForge project; one saved before this course keeps **classic defaults** until File → **Use current defaults**.',
    '- On an **NF-C2960**, `show spanning-tree` lists every port with its role, state and cost; `show spanning-tree interface GigabitEthernet0/2 detail` explains one.',
    '- `debug spanning-tree events` prints each change: cut a cable and watch the alternate port listen, learn and forward.',
    '- On the **Spanning tree** overlay, a draining bar under a port letter shows what is left of its phase.',
  ),

  'ccna2-15-rapid-spanning-tree': md(
    '## The idea in one breath',
    '',
    'Rapid spanning tree keeps the root, the costs and the roles of the classic version, but replaces most of the waiting with a quick handshake between neighbours. Where every switch speaks it, a failed link heals in about a second, not thirty to fifty.',
    '',
    '## Why it exists',
    '',
    'Half a minute of silence after every change is too long for a voice call or live video. The timers were a safe guess at how long news takes to spread; asking the neighbour is faster and just as safe.',
    '',
    '## How it actually works',
    '',
    'The rapid version (IEEE 802.1w, run per VLAN as Rapid PVST+) folds the states into three: **discarding**, **learning** and **forwarding**. Its **alternate** port is a spare path to the root, worked out in advance, that takes over the moment the root port fails. A **backup** role covers a second port of the same switch on one shared segment. Every switch sends its own BPDUs every 2 s, so a silent neighbour is noticed after three missed hellos instead of the 20 s max age.',
    '',
    'On a full-duplex link, a designated port that wants to forward sends a **proposal**. The neighbour briefly holds its own other designated ports so no loop can form, answers with an **agreement**, and both ends forward at once, rippling down the tree in a fraction of a second.',
    '',
    'It stays compatible: a rapid port that hears classic BPDUs falls back to the classic protocol on that one port, timers and all, so each link is only as fast as its older switch.',
    '',
    '**Multiple spanning tree** (MST, IEEE 802.1s) maps many VLANs onto a few instances, each with a root of its own; switches that share the mapping form a region, and two hundred VLANs need two trees instead of two hundred. NetForge teaches MST as theory only and does not simulate it.',
    '',
    '## What trips people up',
    '',
    '- A host port without PortFast still waits 30 s in rapid mode, because a PC never answers a proposal.',
    '- A port that fell back returns to the rapid protocol by itself as soon as the upgraded neighbour sends it a rapid BPDU. If none ever comes, for example because the old switch was unplugged rather than upgraded, `clear spanning-tree detected-protocols` makes the port check again (some switches never return on their own, which is why the command exists).',
    '',
    '## See it in NetForge',
    '',
    '- Real switches run spanning tree by default, and so does a new NetForge project; one saved before this course keeps **classic defaults** until File → **Use current defaults**.',
    '- In the lab here CORE1 is an **NF-C9300-48U**, which starts in rapid mode, and SW1 and SW2 are **NF-C2960** switches, which start in classic per-VLAN mode.',
    '- `show spanning-tree` on CORE1 marks each port that faces a classic neighbour.',
    '- `spanning-tree mode rapid-pvst` moves SW1 and SW2 to rapid mode; `clear spanning-tree detected-protocols` on CORE1 makes its ports test their neighbours again.',
  ),

  'ccna2-16-edge-ports-and-guards': md(
    '## The idea in one breath',
    '',
    'Spanning tree trusts every port. Three settings take some of that trust away: **PortFast** says only a host lives behind a port, **BPDU guard** shuts a port that hears a switch where none should be, and **root guard** stops a neighbour from ever becoming your root.',
    '',
    '## Why it exists',
    '',
    'Waiting 30 s on a port that leads to one PC protects nothing. Meanwhile the election believes any BPDU it hears, so a small switch plugged in under a desk, or a neighbouring switch with a lower priority, can pull the whole tree towards itself.',
    '',
    '## How it actually works',
    '',
    '`spanning-tree portfast` on an access port makes it an **edge port**: it forwards the moment the link comes up, and a PC that restarts never causes a topology change. It is only safe where hosts live, so pair it with `spanning-tree bpduguard enable`. BPDU guard turns the first BPDU a port receives into an **error-disabled** port: shut down, and down it stays until someone brings it back. Globally, `spanning-tree portfast default` makes every access port an edge port and `spanning-tree portfast bpduguard default` guards every edge port.',
    '',
    'Root guard belongs on the ports of your distribution switches that face places where a switch is welcome but a better root is not. With `spanning-tree guard root`, a **superior** BPDU on that port makes it root-inconsistent and blocks it. Unlike BPDU guard it heals by itself once the superior BPDUs stop.',
    '',
    '**Loop guard** is the third guard on the CCNA list. It watches root and alternate ports; if their BPDUs stop, say because a fibre lost one direction, it blocks the port instead of letting it turn designated and open a loop. NetForge teaches loop guard as theory only.',
    '',
    'An error-disabled port comes back with `shutdown` followed by `no shutdown`, or by itself after a delay once `errdisable recovery cause bpduguard` is set.',
    '',
    '## What trips people up',
    '',
    '- PortFast between two switches invites a loop. BPDU guard is what makes that mistake safe.',
    '- Root guard goes on the port the bad BPDU arrives on, not on the switch that sends it.',
    '- Bringing a port back before the offending switch is removed shuts it again at the next BPDU.',
    '',
    '## See it in NetForge',
    '',
    '- Real switches run spanning tree by default, and so does a new NetForge project; one saved before this course keeps **classic defaults** until File → **Use current defaults**.',
    '- In the lab here AS1 is an **NF-C2960** and DS1 an **NF-C9300-48U**.',
    '- `show interfaces status err-disabled` lists the ports a guard has shut, and `show errdisable recovery` which causes come back by themselves.',
    '- `show spanning-tree` on DS1 marks a root-inconsistent port.',
  ),

  'ccna2-17-bundling-links': md(
    '## The idea in one breath',
    '',
    'EtherChannel ties two to eight parallel cables between the same two switches into one logical link, a **port-channel**. Spanning tree sees a single port and blocks nothing, so every cable carries traffic, and losing one only moves its flows onto the others.',
    '',
    '## Why it exists',
    '',
    'A second cable between two switches should double the capacity and add a spare. Spanning tree sees a loop and blocks it instead, so you pay for two links and use one. A bundle fixes that: the switches treat the cables as one, so there is no loop to block and nothing to rebuild when a member fails.',
    '',
    '## How it actually works',
    '',
    'Both ends put their members in the same channel group and agree that they belong together. The standard way is **LACP** (IEEE 802.3ad): `channel-group 1 mode active` starts the negotiation and `channel-group 1 mode passive` only answers, so active with active or with passive forms a bundle and passive with passive never does. **PAgP** is an older protocol for the same job, with `channel-group 1 mode desirable` to start and `channel-group 1 mode auto` to answer. `channel-group 1 mode on` bundles with no negotiation and only works against another `on`.',
    '',
    'Every member must match the bundle: speed, duplex, access or trunk mode, native VLAN and allowed list. A member whose settings differ is **suspended** and carries nothing. A member that hears no partner runs **individual**, an ordinary port that spanning tree treats on its own. A healthy member is **bundled**.',
    '',
    'Traffic is not split packet by packet. The switch hashes fields of each frame, by default the source MAC address, and the result picks one member, so a conversation always uses one cable and its frames never arrive out of order. `port-channel load-balance src-dst-mac` mixes in both addresses, which spreads traffic better when many hosts talk to one gateway.',
    '',
    '```',
    'interface range GigabitEthernet0/1 - 2',
    ' switchport mode trunk',
    ' channel-group 1 mode active',
    '```',
    '',
    '## What trips people up',
    '',
    '- A bundle is not faster for one flow: a single file copy still runs at the speed of one member.',
    '- A setting typed on one member only makes it differ from the bundle, and it is suspended. Type it under the port-channel, which passes it to every member.',
    '- `on` at one end and LACP at the other never forms one bundle.',
    '',
    '## See it in NetForge',
    '',
    '- The lab here joins two **NF-C2960** switches with two cables; SW2 waits passively, and one of its members is set up wrongly.',
    '- `show etherchannel summary` shows each member as bundled, individual or suspended, and `show lacp neighbor` who answered on it.',
    '- `show spanning-tree` lists one `Port-channel1` instead of two ports.',
  ),

  'ccna2-18-dhcp-across-vlans': md(
    '## The idea in one breath',
    '',
    'A host with no address asks for one by broadcasting, and a broadcast never leaves its VLAN. When the DHCP server lives somewhere else, the gateway interface of the VLAN has to catch the request and carry it there, and every VLAN needs its own.',
    '',
    '## Why it exists',
    '',
    'Once a network is split into VLANs, each VLAN is a subnet of its own with its own gateway interface: a VLAN interface on a multilayer switch, or a subinterface on a router. Nobody wants a DHCP server in every VLAN; one central server keeps every lease and pool in one place. The relay is what lets that server reach subnets whose hosts cannot yet send anything but a broadcast.',
    '',
    '## How it actually works',
    '',
    'The line `ip helper-address 10.0.0.2` on a VLAN interface tells it to relay. When a Discover arrives from VLAN 10, the interface does three things:',
    '',
    '1. It turns the broadcast into an ordinary unicast packet addressed to the server, `10.0.0.2`.',
    '2. It writes its own address on that VLAN, `192.168.10.1`, into the relay agent field of the request.',
    '3. It routes the packet like any other traffic.',
    '',
    'The server reads the relay address and leases from the pool whose network contains it, so a request relayed by `192.168.10.1` gets an address from `192.168.10.0/24` and one relayed by `192.168.20.1` from `192.168.20.0/24`. The Offer goes back to the relay address, and the relay puts it on the VLAN where the client is waiting. Request and Acknowledge follow the same path.',
    '',
    'On a multilayer switch with VLAN 10 and VLAN 20:',
    '',
    '```',
    'interface Vlan10',
    ' ip address 192.168.10.1 255.255.255.0',
    ' ip helper-address 10.0.0.2',
    'interface Vlan20',
    ' ip address 192.168.20.1 255.255.255.0',
    ' ip helper-address 10.0.0.2',
    '```',
    '',
    '## What trips people up',
    '',
    '- One helper per VLAN interface. Forget it on Vlan20 and VLAN 20 gets no addresses while VLAN 10 works perfectly. A router with one subinterface per VLAN needs a helper on each subinterface for the same reason.',
    '- The server needs a route back to every relay address, or its Offers go nowhere.',
    '- The default router of each pool is the gateway interface of that VLAN, never the server.',
    '',
    '## See it in NetForge',
    '',
    '- This lesson is practised in the lab of lesson 10, on an **NF-C3650-24** multilayer switch and an **NF-2911** router that holds the pools.',
    '- On the router, `show ip dhcp binding` lists each lease with its pool: a host in VLAN 10 leases from pool SALES, one in VLAN 20 from pool STAFF.',
    '- On an **NF-PC**, `ip address dhcp` asks for a lease and `ipconfig` shows what arrived.',
    '- In **NetScope**, the summary of a relayed request names the relay address that stamped it.',
  ),

  'ccna2-19-slaac-and-dhcpv6': md(
    '## The idea in one breath',
    '',
    'An IPv6 host listens to its router before it asks anyone for anything. Two flags in the router advertisement tell it what to do: build its own address, build its own address and ask DHCPv6 for the rest, or ask DHCPv6 for the address as well.',
    '',
    '## Why it exists',
    '',
    'IPv6 was designed so that a host could configure itself with no server at all: the router announces the prefix and the host adds an interface ID of its own. That is **SLAAC**, and it is enough for many networks. But a host also needs a name server, and some organisations want to decide which address each machine holds and keep a record of it. DHCPv6 covers both, and the flags let the router say which part of the job it hands over.',
    '',
    '## How it actually works',
    '',
    'A router advertises only once IPv6 routing is on (`ipv6 unicast-routing`). Each advertisement carries the prefix, the link-local address of the router as the default gateway, and two flags:',
    '',
    '- **Neither flag**: SLAAC only.',
    '- **Other-configuration flag** (O): stateless DHCPv6. The host keeps its SLAAC address and sends an Information-Request for the name server and the domain. The server remembers nothing about it.',
    '- **Managed-configuration flag** (M): stateful DHCPv6. The host runs Solicit, Advertise, Request and Reply and leases an address, which the server records as a binding.',
    '',
    'Clients use UDP port 546 and servers 547, and a request goes to the all-DHCP-servers group `ff02::1:2`. For the office LAN of the lab, a stateless pool and the O flag:',
    '',
    '```',
    'ipv6 dhcp pool OFFICE',
    ' dns-server 2001:db8:a::53',
    ' domain-name lab.nf',
    'interface GigabitEthernet0/0',
    ' ipv6 dhcp server OFFICE',
    ' ipv6 nd other-config-flag',
    '```',
    '',
    'The lab LAN gets a pool with `address prefix 2001:db8:b::/64` and `ipv6 nd managed-config-flag` on its interface instead.',
    '',
    '## What trips people up',
    '',
    '- DHCPv6 never hands out a default gateway. Even a fully stateful host learns its gateway from the router advertisement.',
    '- The M flag does not stop SLAAC. While the prefix is still advertised for autoconfiguration, a stateful host keeps a SLAAC address beside its lease.',
    '- A host reads the flags only in the next advertisement it hears, so changing them on the router does not reach it at once.',
    '',
    '## See it in NetForge',
    '',
    '- The lab here is one **NF-2911** router and two **NF-PC** hosts.',
    '- On a PC, `ipv6config` shows every address with where it came from, and `adapter GigabitEthernet0 down` followed by `adapter GigabitEthernet0 up` makes it ask for a fresh advertisement.',
    '- On the router, `show ipv6 dhcp binding` lists the leases and `show ipv6 dhcp pool` the pools.',
  ),

  'ccna2-20-one-gateway-one-point-of-failure': md(
    '## The idea in one breath',
    '',
    'A host sends everything outside its subnet to one address, its default gateway. With two routers on the LAN the host still knows only one, so when that router fails the host is cut off, however healthy the other is.',
    '',
    '## Why it exists',
    '',
    'Hosts do not run routing protocols. They are given one gateway, by hand or by DHCP, and keep using it with the MAC address ARP taught them. Reconfiguring hundreds of hosts during an outage is not a plan. A **first-hop redundancy protocol** lets the gateway survive the loss of a router without the hosts noticing.',
    '',
    '## How it actually works',
    '',
    'Two or more routers on the LAN form a group and share a **virtual IP address**, which the hosts use as their gateway, and a matching **virtual MAC address**. One router is **active**: it answers ARP requests for the virtual address with the virtual MAC and forwards the traffic of the hosts. The others listen to its hello messages.',
    '',
    'When the hellos stop, the next router in line takes over the virtual IP and MAC and sends a gratuitous ARP from the virtual MAC, so the switches move that address to its port. The ARP entry each host holds for its gateway is still right, because the MAC address has not changed, only the router behind it. A few packets are lost; nothing on the hosts is touched.',
    '',
    'Three protocols do this job. **HSRP** has one active and one standby router. **VRRP** is the open standard and calls them master and backup; its virtual address may even be the real address of one of the routers. **GLBP** also shares the load by handing different hosts different virtual MACs.',
    '',
    '## What trips people up',
    '',
    '- Only the active router forwards for a group. Sites often run two groups and make each router active for one, so neither sits idle.',
    '- The protocol protects the gateway, not the uplink behind it: an active router that loses its uplink but stays up on the LAN keeps its role unless it watches that link.',
    '- A host set up with the real address of one router gets none of this.',
    '',
    '## See it in NetForge',
    '',
    '- The lab of the next lesson has two **NF-2911** routers and **NF-PC** hosts that still point at the real address of one router.',
    '- Before you change anything there, ping the server from PC1, use **Power off** on R1 and ping again: the replies stop for good. Power R1 back on before you start the lab.',
    '- `show standby brief` on each router shows which router is active in each group, and `arp -a` on a PC the gateway MAC it is holding on to.',
  ),

  'ccna2-21-hot-standby-gateways': md(
    '## The idea in one breath',
    '',
    'HSRP puts two routers into a **standby group** that shares a virtual gateway address. One is active and forwards, the other watches its hellos, and when the hellos stop it takes over the address without the hosts noticing.',
    '',
    '## Why it exists',
    '',
    'A gateway at the real address of a router fails with that router. HSRP fixes that with a few settings: a group number, a virtual address, a priority that chooses the active router, and preemption so the preferred router can take its role back.',
    '',
    '## How it actually works',
    '',
    'Every router in a group sends a hello every 3 s. A standby router that hears nothing from the active router for the hold time of 10 s takes over. When a group forms, the routers pass through **listen** and **speak** while they compare priorities: the highest becomes **active** and the next **standby**, and on a tie the highest interface address wins. The default priority is 100.',
    '',
    'Preemption is off by default. A router with a better priority that joins later, or comes back after a failure, stays standby behind the one already active, unless it may **preempt**: then it takes the role at once.',
    '',
    'There are two versions. Version 1 numbers groups from 0 to 255 and sends hellos to `224.0.0.2`; version 2 allows up to 4095 groups, sends to `224.0.0.102` and supports IPv6. The two never hear each other, so every router of a group must run the same one. The virtual MAC address is built from the group number, so each group has its own.',
    '',
    'In the lab, R2 is already alone in group 10. On R1:',
    '',
    '```',
    'interface GigabitEthernet0/0',
    ' standby version 2',
    ' standby 10 ip 192.168.10.1',
    ' standby 10 priority 110',
    ' standby 10 preempt',
    '```',
    '',
    'Then each host uses the virtual address as its gateway: `ip address 192.168.10.10 255.255.255.0 192.168.10.1` on PC1.',
    '',
    '## What trips people up',
    '',
    '- A higher priority alone does not move the active role. Without preemption the first router to become active keeps it.',
    '- Group number and version must match on every member, or each router believes it is alone. The virtual address must match too: routers that disagree on it still elect an active router, and the hosts lose their gateway whenever the active one answers for a different address.',
    '- The hosts must point at the virtual address, never at the address of one router.',
    '',
    '## See it in NetForge',
    '',
    '- The lab here has two **NF-2911** routers and two **NF-PC** hosts.',
    '- `show standby brief` lists each group with its state, priority and virtual address; `show standby` gives the detail, and `debug standby` prints each state change.',
    '- Ping the server from PC1. Run `copy running-config startup-config` on R1 first, because a power cut loses every line that was never saved. Then use **Power off** on R1 and keep pinging: after a few lost replies R2 answers. Power R1 back on and watch it take the active role back.',
  ),
};
