/**
 * curriculum/ccna1/theory-b.ts — the plain-language body of CCNA 1 lessons 17 to 31, keyed by lesson id.
 *
 * The second half of the arc: static routing, device access, the address and name services, the two transports,
 * the web, IPv6, wireless and fault finding. Lessons 1 to 16 live in `theory-a.ts`; `theory.ts` merges the two
 * halves into the `CCNA1_THEORY` map that `curriculum/index.ts` joins onto the lesson skeleton.
 *
 * Every body follows one shape — the idea in one breath, why it exists, how it actually works with a worked
 * example, what trips people up, and what to type in NetForge — so a reader who has read one knows where to look
 * in all the others. Commands are only ones the CLI grammar really ships (`cli/grammar/*`), and the worked
 * examples stay inside the documentation address space (`192.168.1.0/24`, `10.0.0.0/24`, `2001:db8::/32`).
 *
 * One rule about the last section: a bullet under "See it in NetForge" is something the learner TYPES, so it
 * must work in the lesson's own lab and therefore uses that lab's addresses, not the illustrative ones above it.
 *
 * Markdown subset only: headings, lists, emphasis, fenced code and links limited to `concept:subnetting` and
 * `concept:ipv6`. No raw HTML — the parser treats that as a security boundary. All prose is original and names no
 * vendor.
 *
 * ponytail: the bodies are line arrays joined by `body()`, the way the lab instructions are written, so a line of
 * markdown is a line of source — no escaped backticks, and a diff shows exactly the sentence that changed.
 */
import type { LessonTheoryMap } from '../../contracts/curriculum.js';

/** One lesson body: markdown lines, joined the way lab instructions are. */
function body(...lines: readonly string[]): string {
  return lines.join('\n');
}

/** Lesson bodies 17–31. Keys must match ids in `ccna1/lessons.ts`. */
export const THEORY_B: LessonTheoryMap = {
  'ccna1-17-static-routes': body(
    '## The idea in one breath',
    '',
    'A router forwards only to networks it has a route for. A static route is one of those routes, written by hand.',
    '',
    '## Why it exists',
    '',
    'A router works out on its own only the networks its own interfaces sit in. Everything further away is a blank, and a packet for a blank is dropped. In a small network with a few fixed links there is nothing to work out: you already know where each network is, so you say so. A route you typed never changes by itself, never fills the links with updates, and comes back the same after a restart.',
    '',
    '## How it actually works',
    '',
    'A static route names three things: the destination network, its mask, and the *next hop* — the neighbouring address that is one step closer.',
    '',
    'R1 carries the LAN `192.168.1.0/24` and one link to R2 on `10.0.0.0/24`, where R1 is `10.0.0.1` and R2 is `10.0.0.2`. R2 carries the LAN `192.168.2.0/24`. On R1 you write:',
    '',
    '```',
    'ip route 192.168.2.0 255.255.255.0 10.0.0.2',
    '```',
    '',
    'Read it as a sentence: for anything in `192.168.2.0/24`, hand the packet to `10.0.0.2`. R1 does not care what happens after that. R2 makes its own decision, and it needs the mirror route:',
    '',
    '```',
    'ip route 192.168.1.0 255.255.255.0 10.0.0.1',
    '```',
    '',
    '## What trips people up',
    '',
    '- The next hop is an address on a neighbour. It is not the destination network and not your own interface.',
    '- Traffic goes both ways. A request that arrives perfectly still fails if the reply has nowhere to go, and a missing return route is half of all "the ping does not work" moments.',
    '- A longer chain needs a route on *every* router in it, including the ones in the middle that own neither end.',
    '',
    '## See it in NetForge',
    '',
    '- `show ip route` lists what a router knows. Networks it is attached to are marked `C`, the ones you typed `S`.',
    '- Add a route with `ip route`, and remove a wrong one with `no ip route` and the same three values.',
    '- Ping from each end: one direction working and the other not points straight at a missing route.',
    '- The lab on this lesson gives you three routers in a chain with no static routes at all, and grades each router separately before it grades the end-to-end ping.',
  ),

  'ccna1-18-device-access-and-passwords': body(
    '## The idea in one breath',
    '',
    'A device out of the box has no name, no password and no notice. Giving it all three is the first configuration, not the last.',
    '',
    '## Why it exists',
    '',
    'Configuration is power: whoever reaches privileged mode can change addresses, routes and ports. A rack of unnamed devices also invites the worst mistake in the job, which is typing a correct command into the wrong box. So the first minutes of setup do four things: a name you can read in the prompt, a secret in front of privileged mode, a password on the way in, and a notice that says the machine is not public. A switch gets a fifth: an address, so you can manage it without walking to it.',
    '',
    '## How it actually works',
    '',
    'Privileged mode is guarded by a stored secret. The device keeps a scrambled form and compares against it, so it can never print the secret back to you. The way in is a *line*: the console line is the socket on the front of the box. Giving a line a password does nothing until you also tell the line to ask for it.',
    '',
    'A plain switch does not route, so its management address lives on a virtual interface, and that interface starts switched off.',
    '',
    '```',
    'hostname LAB-ACCESS1',
    'enable secret quiet-harbour-77',
    'banner motd Study network: authorised use only',
    'line con 0',
    ' password copper-lantern-5',
    ' login',
    'exit',
    'interface Vlan1',
    ' ip address 192.168.50.2 255.255.255.0',
    ' no shutdown',
    'exit',
    'ip default-gateway 192.168.50.1',
    '```',
    '',
    '## What trips people up',
    '',
    '- The password form and the secret form look interchangeable. Only the secret is stored scrambled; prefer it.',
    '- A password on a line is ignored until that line is told to log users in.',
    '- A management address does not make a switch route anything. It exists so the switch itself can be reached, and it needs a default gateway to answer anyone outside its own subnet.',
    '- The virtual interface starts administratively down. An address alone does not wake it.',
    '',
    '## See it in NetForge',
    '',
    '- `show running-config` shows the name, the notice and the line settings, and shows the secret only in its stored form.',
    '- `show ip interface brief` says whether the management interface is up.',
    '- Ping the switch from a workstation: a switch that answers is a switch you can manage.',
    '- The lab here hands you a bare switch and grades the name, the secret, the console login, the notice and the management address one by one.',
  ),

  'ccna1-19-dhcp': body(
    '## The idea in one breath',
    '',
    'Instead of typing an address into every machine, a host asks the network for one and is lent it for a while.',
    '',
    '## Why it exists',
    '',
    'Typed addresses do not scale and they collide. Thirty laptops mean thirty chances to reuse `192.168.1.10`, and the second machine to use it breaks the first. A lending service keeps the list, hands out what is free and takes it back when the time is up. It also carries the rest of the settings, so a host that finds a network finds a way out of it too.',
    '',
    '## How it actually works',
    '',
    'Four messages, always in the same order. The host has no address yet, so it starts by shouting to the whole segment.',
    '',
    '1. *Discover* — the host asks whether any server is listening.',
    '2. *Offer* — a server proposes a free address from its pool.',
    '3. *Request* — the host says out loud which offer it takes, so any other server knows its own offer is free again.',
    '4. *Acknowledge* — the server writes the binding down and confirms.',
    '',
    'The answer carries the mask, the default gateway and usually a name server: almost everything a host needs. A router that carries `192.168.1.1/24` can lend on that LAN:',
    '',
    '```',
    'ip dhcp excluded-address 192.168.1.1 192.168.1.10',
    'ip dhcp pool LAN15',
    ' network 192.168.1.0 255.255.255.0',
    ' default-router 192.168.1.1',
    ' domain-name lab.nf',
    '```',
    '',
    'The exclusion comes first and sits outside the pool. Without it the pool would happily lend `192.168.1.1` to a laptop, and two machines would answer to the router address.',
    '',
    'A lease has a lifetime. Part way through it the host asks to keep the address, which is why a machine usually gets the same one back.',
    '',
    '## What trips people up',
    '',
    '- Exclusions are global lines, not pool lines.',
    '- The pool network has to match the network on the interface, or the server has nothing to hand out on that segment.',
    '- A host with no address is not always broken. A server with an empty or wrong pool simply says nothing, and the host keeps asking.',
    '',
    '## See it in NetForge',
    '',
    '- On a host: `ip address dhcp`, then `ipconfig /all` for the address, the gateway, the lease length and the name servers.',
    '- On the router: `show ip dhcp binding` for who holds what, and `show ip dhcp pool LAN15` for the pool itself.',
    '- Watch the four messages in NetScope, or step through them one at a time in simulation mode.',
    '- The lab attached here starts with two hosts that have no address at all.',
  ),

  'ccna1-20-dhcp-across-a-router': body(
    '## The idea in one breath',
    '',
    'A request for an address is a broadcast, and a router does not forward broadcasts. A relay carries the request across for it.',
    '',
    '## Why it exists',
    '',
    'An organisation keeps one address server, not one per floor. But the client that needs an address has no address yet, so it can only shout at its own segment, and that shout stops at the first router. Either every subnet gets its own server, or the router is told to pick the request up and carry it. The second is cheaper and keeps every lease in one place.',
    '',
    '## How it actually works',
    '',
    'The host broadcasts as usual. The interface it shouted at is configured to help, so instead of dropping the broadcast the router repackages the request as an ordinary packet addressed to the server, and stamps into it the address of the interface the request arrived on.',
    '',
    'That stamp is the whole trick. The server never sees the branch segment and could not guess which network the client is in, so it reads the stamped address and picks the pool that contains it.',
    '',
    'The branch interface carries `192.168.1.1` and the server is reachable at `10.0.0.2`:',
    '',
    '```',
    'interface GigabitEthernet0/0',
    ' ip helper-address 10.0.0.2',
    '```',
    '',
    'On the central router the pool is an ordinary one for `192.168.1.0/24` with default gateway `192.168.1.1`. That server is not in that network and never will be. The reply travels back to the relay, which puts it on the segment where the client is waiting.',
    '',
    '## What trips people up',
    '',
    '- The helper line goes on the interface facing the *clients*, not the one facing the server.',
    '- Routing between the two routers has to work first. A relayed request is ordinary traffic, and so is the answer.',
    '- The default gateway in the pool is the branch router, never the server.',
    '',
    '## See it in NetForge',
    '',
    '- `ip helper-address` on the client-facing interface, then `show running-config` to check where it landed.',
    '- `show ip dhcp binding` on the central router lists the bindings, each one recording the relay address that carried it.',
    '- `ipconfig /all` on a branch host shows an address from a network the server does not touch.',
    '- The lab here puts two hosts in a branch subnet and the pool on a router one link away.',
  ),

  'ccna1-21-dns': body(
    '## The idea in one breath',
    '',
    'People remember names and packets need addresses. A name service is the lookup between the two.',
    '',
    '## Why it exists',
    '',
    'Nobody types `192.168.1.60` twice a day, and nobody should have to. Names are also a layer of freedom: change the machine behind `files.lab.nf` and everyone follows the name to the new address without being told. Without the lookup, every address change would mean editing every client.',
    '',
    '## How it actually works',
    '',
    'A name is read right to left, from the widest part to the narrowest: `files.lab.nf` is the machine `files` inside `lab` inside `nf`.',
    '',
    'A client keeps the address of a name server. Before it opens anything it asks that server a question — what is the address for `files.lab.nf`? — and the server answers from its records. Only then does the real traffic start. The lookup itself is small: one question, one answer.',
    '',
    'A record has a name, a type and a value. The common type maps a name to an IPv4 address; another maps a name to an IPv6 address; another makes one name an alias for a second. On a server at `192.168.1.53`:',
    '',
    '```',
    'service dns on',
    'service dns record www.lab.nf A 192.168.1.53 3600',
    'service dns record files.lab.nf A 192.168.1.60 3600',
    '```',
    '',
    'The last number is how long other machines may keep the answer before asking again. On the client, one line is enough:',
    '',
    '```',
    'ip dns 192.168.1.53',
    '```',
    '',
    '## What trips people up',
    '',
    '- A client that knows no name server resolves nothing, even while the address works perfectly. "The address answers, the name does not" is the signature of that fault.',
    '- Keeping answers is helpful until you change a record. An old answer lives on until its time runs out.',
    '- A failed lookup looks exactly like a dead server. Test the address first, then the name, and the answer takes seconds.',
    '',
    '## See it in NetForge',
    '',
    '- `nslookup files.lab.nf` on a host asks the question and prints the answer.',
    '- `ping www.lab.nf` does the lookup and the reachability test in one go.',
    '- `show hosts` lists the names a device knows.',
    '- In NetScope the question and the answer show up as two small messages before any real traffic.',
    '- The lab here has two servers answering at their addresses and no names published at all.',
  ),

  'ccna1-22-tcp-and-udp': body(
    '## The idea in one breath',
    '',
    'Two ways to carry data between programs: one that checks everything arrived, and one that simply sends.',
    '',
    '## Why it exists',
    '',
    'The layer below gets a packet to a machine. It says nothing about *which program* on that machine, and promises nothing about arrival or order. The transport layer adds both. Some programs need the promise. Others would rather not pay for it, because the cost is measured in round trips.',
    '',
    '## How it actually works',
    '',
    'Both transports put a source port and a destination port in front of the data. The destination port says which service; the source port is a number the client picks so it can match answers to its own questions. An address plus a port is the address of a service: `192.168.1.80` port `80`.',
    '',
    'The careful transport opens a connection first, with a three-message handshake. It numbers the bytes, acknowledges what arrived, sends again what did not, and slows down when the path struggles. Web pages and file transfers use it.',
    '',
    'The light transport has no handshake, no acknowledgements and no ordering — a few bytes of header and away it goes. Name lookups and address leases use it, because they are one small question and one small answer, and asking again is cheaper than keeping a connection alive.',
    '',
    'So a host at `192.168.1.10` may hold one careful connection to `192.168.1.80` port `80` and, at the same moment, fire a light request at a name server on port `53`, with nothing shared between them but the adapter.',
    '',
    '## What trips people up',
    '',
    '- *Reliable* does not mean *fast*. The checks cost time; the light transport wins on short exchanges.',
    '- The light transport is not careless by accident. Whatever checking is needed happens in the program above it.',
    '- Sockets are bound to a port on an address, so one machine can run many services at once as long as their ports differ.',
    '',
    '## See it in NetForge',
    '',
    '- `netstat -a` on a host or a server lists the sockets it has open; on a router, `show ip sockets` does the same job.',
    '- Fetch a page from the browser app and watch the capture: three small messages before a single byte of page.',
    '- Ask for a name or an address lease and watch the same capture: no handshake at all.',
    '- Simulation mode steps through the handshake one message at a time, which is the clearest way to see it.',
  ),

  'ccna1-23-http-and-the-web': body(
    '## The idea in one breath',
    '',
    'A page is a file that a browser asks for by name, over a connection, and that a server hands back with a short status.',
    '',
    '## Why it exists',
    '',
    'Everything under the browser already existed: addresses, routing, a reliable transport, a name service. What was missing was an agreement about how to *ask* — how to name the thing you want and how to say what happened. The request and the status line are that agreement, and they are deliberately simple enough to read with your own eyes.',
    '',
    '## How it actually works',
    '',
    'Three steps, each of which you have already met on its own.',
    '',
    '1. The name: the browser asks its name server for the address behind `www.lab.nf`.',
    '2. The connection: it opens a reliable connection to that address on the web port, `80`.',
    '3. The exchange: it asks for a path, `/index.html`, and the server answers with a status, a few headers and the body.',
    '',
    'The status is the part worth reading. A number in the 200s means here it is. The 300s mean it moved. The 400s mean the request was wrong — the famous one is `404`, meaning there is no such path. The 500s mean the server itself broke. On a server at `192.168.1.80`:',
    '',
    '```',
    'service http on',
    'service http page /index.html This page is served by the practice web server.',
    'service dns on',
    'service dns record www.lab.nf A 192.168.1.80 3600',
    '```',
    '',
    'A client that knows that name server can now ask for `www.lab.nf/index.html` and get the text back.',
    '',
    '## What trips people up',
    '',
    '- Three systems have to work: the name, the transport and the service. A page that does not load could be any of them, and testing in that order takes seconds.',
    '- The path is part of the request, not part of the name. A right name with a wrong path gives `404`, which actually proves the first two steps worked.',
    '- A server listens whether or not any page has been published on it.',
    '',
    '## See it in NetForge',
    '',
    '- `service http on` plus a page path; `netstat -a` on the server then shows the socket listening on port `80`.',
    '- Open the browser app on a workstation and type the full address.',
    '- In NetScope, follow the stream to read the request and the reply as plain text.',
    '- The lab here has you publish the page and the name, and then fetch it from the workstation.',
  ),

  'ccna1-24-why-ipv6': body(
    '## The idea in one breath',
    '',
    'IPv6 does the same job as IPv4 with a far larger address, written in hexadecimal instead of decimal.',
    '',
    '## Why it exists',
    '',
    'Thirty-two bits give about four billion addresses, which sounded generous when there were a few thousand machines and does not now. Every trick that stretched the old space — borrowing bits, sharing one public address between a whole office — added a rule to remember and a thing to break. A 128-bit address ends the shortage instead of managing it, and the newer header drops fields that nobody used.',
    '',
    '## How it actually works',
    '',
    'An address is eight groups of four hexadecimal digits, separated by colons. Two shortenings make it readable: leading zeros inside a group may be dropped, and *one* run of all-zero groups may be replaced by `::`.',
    '',
    '```',
    '2001:0db8:0000:0000:0000:0000:0000:0001',
    '2001:db8::1',
    '```',
    '',
    'Those are the same address. Only one `::` is allowed, because a second one would be ambiguous: nothing would say how many zero groups belong to each.',
    '',
    'A normal unicast address splits in a familiar way. With the usual 64-bit prefix, `2001:db8:1::/64` is the network and the last 64 bits identify the interface, so `2001:db8:1::10` is one host on that network. Every interface also carries a *link-local* address beginning `fe80::`, which works only on its own segment; hosts use it to talk locally and to reach their router.',
    '',
    'The [IPv6 view](concept:ipv6) shortens and expands addresses until the arithmetic is automatic.',
    '',
    '## What trips people up',
    '',
    '- A group is 16 bits, not 8. `2001:db8::` is not a dressed-up `192.168`.',
    '- A second `::` is not extra compression, it is invalid.',
    '- Link-local addresses turn up everywhere and look like a mistake. They are not: they are how an interface talks before anything else is configured.',
    '',
    '## See it in NetForge',
    '',
    '- `show ipv6 interface brief` on a router lists both addresses of each interface: the link-local one and the global one.',
    '- `ipv6config` on a host prints the same for its adapters.',
    '- `ping -6 2001:db8:1::1` tests an address once one exists.',
    '- The [IPv6 view](concept:ipv6) also builds interface identifiers and names the address types.',
  ),

  'ccna1-25-ipv6-without-a-server': body(
    '## The idea in one breath',
    '',
    'Tell a router which prefix lives on a segment, and every host on it builds its own full address.',
    '',
    '## Why it exists',
    '',
    'With addresses this plentiful, handing them out one at a time from a central list is work nobody needs. It is enough to announce which network this segment is, and let each host add the part that identifies itself. The result is a network where a host you have never seen plugs in and is addressed and routed within a second or two, with no server involved.',
    '',
    '## How it actually works',
    '',
    'A router that forwards IPv6 announces itself on each of its segments. The announcement carries the prefix in use and says, in effect, *I am a router*. A host that hears it does three things: it takes the prefix and adds its own 64-bit interface part, giving a global address; it records the sender as its default router; and it checks that no neighbour already holds the address it just built. A host that has just woken asks for an announcement rather than waiting for the next one.',
    '',
    'On R1, the segment `2001:db8:1::/64`:',
    '',
    '```',
    'ipv6 unicast-routing',
    'interface GigabitEthernet0/0',
    ' ipv6 address 2001:db8:1::1/64',
    ' no shutdown',
    '```',
    '',
    'Each host is told to autoconfigure, and ends up with three things: a link-local address starting `fe80::`, a global address inside `2001:db8:1::/64`, and a default route pointing at the router.',
    '',
    '## What trips people up',
    '',
    '- The global forwarding line is not optional. Without it the router keeps its prefixes to itself and the hosts get nothing.',
    '- The default router is recorded as a *link-local* address, not the global one. That looks wrong and is correct.',
    '- Announcements are periodic, so after configuring the router there can be a wait before a host is addressed. Give it a moment before declaring failure.',
    '',
    '## See it in NetForge',
    '',
    '- `ipv6 unicast-routing` on the router, `ipv6 address 2001:db8:1::1/64` on the interface, `ipv6 autoconfig` on the host.',
    '- `ipv6config` on the host shows all three results at once.',
    '- `show ipv6 neighbors` and `show ipv6 route` on the router.',
    '- `ping -6` across the router, using the address the far host built for itself.',
    '- The lab here gives you two segments, one router and not a single address anywhere.',
  ),

  'ccna1-26-how-wireless-works': body(
    '## The idea in one breath',
    '',
    'The same frames as a cable, carried on radio, where everyone shares the air and has to take turns.',
    '',
    '## Why it exists',
    '',
    'A cable is a private medium between two ends, which is why it is fast and quiet. Radio buys mobility with the opposite property: one shared medium, open to everyone in range, including the neighbours. Almost everything odd about wireless follows from that trade.',
    '',
    '## How it actually works',
    '',
    'An access point announces a network name on a *channel*, a slice of the radio spectrum. Clients either listen for those announcements or ask for them, and so build a list of what is in range. Joining has two halves: the client associates with the access point, then proves it knows the passphrase. Only then are its frames carried.',
    '',
    'Because the medium is shared and a radio cannot listen while it transmits, wireless *avoids* collisions rather than detecting them. A station waits for a quiet moment, waits a further random slice of time, then sends, and expects the receiver to acknowledge each frame.',
    '',
    'Two costs follow. Channels overlap, so two nearby access points on overlapping channels slow each other down although neither is faulty. And distance weakens the signal, so a station further away falls back to a slower, sturdier rate.',
    '',
    'Personal security uses one passphrase shared by everyone who joins, from which each station derives the keys that encrypt its own traffic.',
    '',
    '## What trips people up',
    '',
    '- Bars of signal are not speed. A strong signal on a crowded channel can be slower than a weaker one on a quiet channel.',
    '- The name, the security mode and the passphrase must all match. One wrong of the three fails the join with exactly the same unhelpful symptom.',
    '- A client that has joined still has no address. Joining the radio and being addressed are two separate steps.',
    '',
    '## See it in NetForge',
    '',
    '- `show wireless` on an access point lists the network name, the security mode and the channel.',
    '- `wifi list` on a laptop shows the networks in range with their signal.',
    '- `wifi connect HOMELAB key sunny-harbour-41` joins one, and `wifi disconnect` leaves it.',
    '- Drag a laptop further from the access point on the canvas and watch the signal fall.',
    '- The Wi-Fi app on the laptop desktop shows the same information in a window.',
  ),

  'ccna1-27-set-up-a-wireless-network': body(
    '## The idea in one breath',
    '',
    'Three lines on a radio create a protected network. The client then joins it, and asks for an address separately.',
    '',
    '## Why it exists',
    '',
    'Home and small-office kit hides this behind a setup page with two boxes, which is fine until something breaks. Typing the same settings as configuration shows what the boxes actually do: announce a name, choose how to protect the traffic, and lend addresses to whoever joins.',
    '',
    '## How it actually works',
    '',
    'On the radio interface you set the name it announces, the security mode, and the passphrase that mode uses.',
    '',
    '```',
    'interface Wlan0',
    ' ssid HOMELAB',
    ' security wpa2-psk',
    ' passphrase sunny-harbour-41',
    '```',
    '',
    'A home router joins its radio and its cabled ports into one local network, so a wireless client ends up in the same subnet as the machine plugged into the back of it. That is why a single pool serves both sides:',
    '',
    '```',
    'ip dhcp excluded-address 192.168.1.1 192.168.1.20',
    'ip dhcp pool HOME',
    ' network 192.168.1.0 255.255.255.0',
    ' default-router 192.168.1.1',
    '```',
    '',
    'On the client the two steps are separate, and the second one names the adapter:',
    '',
    '```',
    'wifi connect HOMELAB key sunny-harbour-41',
    'ip address dhcp Wlan0',
    '```',
    '',
    '## What trips people up',
    '',
    '- A client that joined but has no address looks exactly like one that never joined. Check the association first, then the lease.',
    '- A laptop has more than one adapter, so the lease has to be asked for on the wireless one.',
    '- Keeping the router address out of the pool matters here as much as anywhere else.',
    '',
    '## See it in NetForge',
    '',
    '- `show wireless` on the home router, and `wifi list` on the laptop before joining.',
    '- `ipconfig /all` on the laptop for the address, the gateway and the lease.',
    '- Ping the cabled host from the laptop: one answer proves the two halves are one network.',
    '- The Wi-Fi app and the IP configuration app on the laptop desktop do the same without typing.',
    '- The lab here starts with a silent radio and a laptop across the room.',
  ),

  'ccna1-28-traceroute': body(
    '## The idea in one breath',
    '',
    'Send packets allowed to travel one hop, then two, then three, and collect the complaint each router sends back.',
    '',
    '## Why it exists',
    '',
    'A ping answers one question: did anything come back. When nothing does, it says nothing about *where* the journey ended, and a network with four routers in it has four places to look. A trace turns one unhelpful silence into a list of addresses, and the list usually names the faulty device.',
    '',
    '## How it actually works',
    '',
    'Every packet carries a hop budget, and each router that forwards it takes one off. A router that takes the last one throws the packet away and sends a small complaint back — and that complaint carries the address of the router that sent it.',
    '',
    'A trace abuses this on purpose. Send with a budget of one, and the first router complains: that is hop one. Send with two, and the second complains. Keep going until the destination itself answers, and the collected complaints are the path.',
    '',
    'From a host at `192.168.1.10` tracing `10.0.0.10`, a healthy trace lists the gateway, then each router in turn, then the destination. Two broken shapes are worth learning by sight. A trace that reaches hop three and then times out for every hop after it means the path stops there. A trace that lists two addresses alternating, over and over, is a loop: each of those two routers believes the other is closer, and the packet bounces until its budget is spent.',
    '',
    '## What trips people up',
    '',
    '- A hop that does not answer is not necessarily a dead hop. A router may forward perfectly and still decline to complain.',
    '- A trace shows the path *out*. The replies may come back a different way.',
    '- A loop is a routing mistake, not a cable fault, and the two repeated addresses name the two routers that disagree.',
    '',
    '## See it in NetForge',
    '',
    '- `tracert 10.0.0.10` from a host, or `traceroute 10.0.0.10` from a router.',
    '- `show ip route` on the last router that answered is usually where the mistake lives.',
    '- Replace a wrong next hop with `no ip route` and then the correct `ip route`.',
    '- The lab here has a chain of three routers, one of which sends the far network back where it came from; the trace shows the bouncing before you fix it.',
  ),

  'ccna1-29-a-method-for-troubleshooting': body(
    '## The idea in one breath',
    '',
    'Work upward from the cable, test one thing at a time, and let every test cut the remaining possibilities in half.',
    '',
    '## Why it exists',
    '',
    'Guessing is expensive. It changes several things at once, fixes the network by accident and teaches you nothing, so the same fault costs the same hour next month. A method is slower for the first two minutes and faster for everything after that, and it ends with a sentence you can tell somebody else.',
    '',
    '## How it actually works',
    '',
    'The layers give you the order, because everything above depends on what is below.',
    '',
    '1. Is the link up? A disabled or unplugged port carries nothing, and nothing above it can work.',
    '2. Does the local segment work? Ping a neighbour in the same subnet. One test covers the cable, the switch, the address and the mask.',
    '3. Can you leave the subnet? Ping the gateway, then something beyond it. A gateway that answers and a beyond that does not is a routing question, not an addressing one.',
    '4. Do names work? If the address answers and the name does not, the fault is in the name service and nothing below it is broken.',
    '5. Is the service running? A listening socket that is not there explains a refused connection.',
    '',
    'Change one thing at a time, and undo a change that did not help. Record what you *observed*, not what you assume: "the host reaches `192.168.1.1` but not `10.0.0.10`" is a fact, while "routing is broken" is a guess wearing a confident voice.',
    '',
    '## What trips people up',
    '',
    '- Starting at the top. Testing names and services before the link wastes the most time of any habit in this job.',
    '- Trusting the configuration over the behaviour. Read what the device reports, not what you meant to type.',
    '- Forgetting the return path. Half the traffic in any test is the answer coming home.',
    '',
    '## See it in NetForge',
    '',
    '- `show ip interface brief` and `show interfaces status` settle the link question in one screen.',
    '- `ping` first, `tracert` second, in that order and not the other way round.',
    '- `ipconfig /all` on a host shows address, mask, gateway and name servers together.',
    '- `show ip route` on a router, `netstat -a` on a server.',
    '- The two fault-finding labs that follow boot broken on purpose. Work the order rather than reading the answer.',
  ),

  'ccna1-30-addressing-faults': body(
    '## The idea in one breath',
    '',
    'An address is only half an identity. The mask decides which neighbours a host thinks are local, and the gateway decides where everything else goes.',
    '',
    '## Why it exists',
    '',
    'These two faults are common because they are invisible. Every address involved looks perfectly reasonable, nothing is unplugged, no light is off, and the symptom is a ping that fails. Learning the two signatures turns an afternoon of cable-swapping into a minute of reading.',
    '',
    '## How it actually works',
    '',
    'For every packet, a host compares the destination with its own network, worked out from its address and its mask. A match means deliver on this segment. No match means hand it to the gateway.',
    '',
    'A wrong mask: PC1 holds `192.168.1.10/24` and PC2 holds `192.168.1.80/26`, both on one cable. PC1 treats the whole of `192.168.1.0/24` as local. PC2, with the longer mask, believes its network runs from `192.168.1.64` to `192.168.1.127`, so it decides `192.168.1.10` is somewhere else and hands those packets to a gateway that is not listening. The cable is fine. The two hosts simply disagree about where the boundary falls.',
    '',
    'A wrong gateway: PC1 points at `192.168.1.9` while the router is at `192.168.1.1`. Everything local works, which is the confusing part, and everything remote fails silently, because the host is faithfully sending to a machine that is not there.',
    '',
    'The [subnetting view](concept:subnetting) is the quickest way to see where a mask puts a boundary.',
    '',
    '## What trips people up',
    '',
    '- Addresses that look alike are not alike. Always read the mask with the address.',
    '- A wrong gateway passes every local test. "Local works, remote fails" is its signature.',
    '- A gateway has to sit inside the network the host believes it is in, or the host cannot even reach it to ask.',
    '',
    '## See it in NetForge',
    '',
    '- `ipconfig` on each host shows address, mask and gateway together. Compare them; do not assume.',
    '- Ping a neighbour first, then the gateway, then something beyond it.',
    '- Repair from the host shell in one line: `ip address 192.168.30.80 255.255.255.0 192.168.30.1` for the wrong mask, `ip address 192.168.30.10 255.255.255.0 192.168.30.1` for the wrong gateway.',
    '- The lab here has one host with a wrong mask and one with a wrong gateway, and grades the local ping and the remote one separately.',
  ),

  'ccna1-31-link-faults': body(
    '## The idea in one breath',
    '',
    'A switched-off port never comes up. A port pinned to fixed settings comes up and works badly. Different faults, different symptoms.',
    '',
    '## Why it exists',
    '',
    'The second of those is the reason this lesson exists. A link that is completely dead is annoying but honest. A link that is up, lit and quietly losing traffic sends people looking at cables, servers and applications for hours, because everything they check reports success.',
    '',
    '## How it actually works',
    '',
    'Two ends of a copper link agree on speed and duplex before carrying data. If both negotiate, they pick the best they share, normally full duplex. If both are pinned to the same values, that works too. If one is pinned and the other negotiates, the negotiating end hears nothing to negotiate with: it guesses the speed from the signal and falls back to half duplex. The link comes up, and then behaves badly — late collisions, errors, and throughput far below what the port claims.',
    '',
    'A disabled port is simpler and more brutal: no link at all, whatever the cable does. The give-away is the port state, which says it was switched off rather than that nothing is plugged in.',
    '',
    'The repair is to enable the dead port, and to return the pinned one to automatic so both ends negotiate again:',
    '',
    '```',
    'interface FastEthernet0/2',
    ' no shutdown',
    'exit',
    'interface FastEthernet0/1',
    ' duplex auto',
    ' speed auto',
    '```',
    '',
    '## What trips people up',
    '',
    '- Automatic speed alone is not enough. Duplex is a separate setting, and one of each is exactly the mismatch.',
    '- A mismatch is not a broken cable. The link is up and the light is on, which points the search in the wrong direction.',
    '- Check the far end too: what the host settled on tells you what the switch offered it.',
    '',
    '## See it in NetForge',
    '',
    '- `show interfaces status` lists every port with its state, duplex and speed on one screen.',
    '- `show interfaces FastEthernet0/1` prints the negotiated duplex and speed of one port, with its error counters.',
    '- Bring a port back with `no shutdown`, and a pinned port back with `duplex auto` and `speed auto`.',
    '- The lab here boots with one disabled port and one pinned port, and grades both repairs and the ping that proves them.',
  ),
};
