/**
 * curriculum/ccna1/theory-a.ts — plain-language theory for the first half of CCNA 1 (lessons 01…16), keyed by the
 * lesson ids of `ccna1/lessons.ts`. `theory-b.ts` carries 17…31 and `curriculum/index.ts` merges the two maps.
 *
 * Every body is markdown in the subset the labs already use (headings, lists, emphasis, code, and links limited to
 * `concept:subnetting`, `concept:ipv6` and https) — the parser treats raw HTML as a security boundary, so there is
 * not an angle bracket in this file. All prose is original, names no vendor, and only promises commands and views
 * that exist: every CLI line below is in `cli/grammar/*` and every panel name is a dock tab or a desktop app.
 *
 * The five sections are the same in every lesson — idea, why, how, trap, see it here — so a learner who has read
 * one knows where to look in all the others, and so the UI can style them without parsing prose.
 *
 * ponytail: a `md(...)` join instead of template literals, because the bodies are full of backticks and escaping
 * them once per inline code span would be noise; and no per-lesson helper for the headings, because a heading that
 * is spelled out is a heading you can search for.
 */
import type { LessonTheoryMap } from '../../contracts/curriculum.js';

/** One lesson body from its lines (the labs build `instructions` the same way). */
const md = (...lines: string[]): string => lines.join('\n');

export const THEORY_A: LessonTheoryMap = {
  'ccna1-01-what-is-a-network': md(
    '## The idea in one breath',
    '',
    'A network is a set of machines that have agreed on how to reach each other. The agreement is the hard part. A cable only carries electricity; every rule about who may speak, what shape a message takes and where it is headed had to be decided in advance by both ends.',
    '',
    '## Why it exists',
    '',
    'Before networks, moving a file meant carrying a disk down the corridor. Two people editing one document meant one of them waiting. Every printer needed an owner sitting next to it. The moment two machines could pass bytes to each other, all of that became a request and an answer — and shared drives, chat, video calls and the web are the same trick at a larger size.',
    '',
    '## How it actually works',
    '',
    'Any network, however big, has four parts. **End devices** are the machines people use: a workstation, a phone, a server. **Intermediary devices** are the boxes in between that forward traffic: switches and routers. **Media** are the cables and radio links the bits travel through. **Protocols** are the written rules everyone follows. A small office is two workstations at `192.168.1.10` and `192.168.1.11`, a switch between them, two copper cables, and the Ethernet and IPv4 rules that let one address a message to the other. Take away any of the four and nothing moves: a cable with no rules is noise, and rules with no cable are theory.',
    '',
    '## What trips people up',
    '',
    'People picture the network as the cables. It is not. The cable is replaceable — copper, glass, radio, the message does not care. What makes a network is the agreement about addresses and formats, which is why a design you can draw on paper can be built out of almost any parts.',
    '',
    '## See it in NetForge',
    '',
    '- Drag two **NF-PC** workstations and one **NF-C2960** switch out of the palette and cable them together.',
    '- Open the **Terminal** on one workstation and run `ipconfig /all` to see everything that machine knows about itself.',
    '- Run a `ping` and open the **Packets** tab: the agreement turns into actual frames on actual cables.',
  ),

  'ccna1-02-hosts-and-media': md(
    '## The idea in one breath',
    '',
    'Some devices on a network are the reason it exists: the machines people type on and the servers they ask for things. Everything else is there to carry traffic between them. The medium is whatever the bits physically travel through.',
    '',
    '## Why it exists',
    '',
    'Early office networks ran every machine onto one shared cable. It worked until it did not. A single bad connector took the whole floor down, and traffic from one desk travelled down every wire in the room. Separating the machines that produce traffic from the boxes that move it gave us networks that can be repaired one piece at a time, and conversations that stay on the two ports they belong to.',
    '',
    '## How it actually works',
    '',
    'A **host** is anything that is a source or a destination: workstation, laptop, phone, server. It has an address and it starts conversations. An **intermediary device** never starts one — it takes a frame in at one port and puts it out another. That is a switch, a router, or the wireless box in a home. Media come in three flavours: copper is cheap and good for about a hundred metres per run but picks up electrical noise; fibre is glass, goes far and ignores interference; radio needs no cable at all but shares the air with everyone nearby. In a small network `192.168.1.0/24` runs on copper from the workstations to the switch, the uplink out of the building might be fibre, and the visitors sit on radio.',
    '',
    '## What trips people up',
    '',
    '"The cable is plugged in, so the link is fine." A copper run that is too long, crushed or badly terminated will still light the link and still lose frames. Distance and quality are part of the rules of the medium, not decoration.',
    '',
    '## See it in NetForge',
    '',
    '- The palette groups devices the same way: computers, switches, routers, wireless.',
    '- Click any device and read its ports in the inspector — each one says what it is, copper Ethernet, serial, console or radio.',
    '- `show ip interface brief` on a switch or router lists every interface with its address and whether the link is up.',
  ),

  'ccna1-03-the-layered-model': md(
    '## The idea in one breath',
    '',
    'A message on a network is wrapped like a parcel inside a parcel. Each layer of software adds its own label at the front, does one job and hands the result down. At the far end, each layer reads its own label off the front and hands the rest up.',
    '',
    '## Why it exists',
    '',
    'Without layers, every program would have to know about cables. Moving an office from copper to radio would mean rewriting the mail program. Splitting the work means the people who design cable and the people who write chat apps never have to meet: as long as each layer keeps its promise to the one above it, either side can be replaced on its own.',
    '',
    '## How it actually works',
    '',
    'Four layers explain everything in this course. The **application** layer is the message itself. The **transport** layer adds a port number so the far machine knows which program the message is for. The **internet** layer adds source and destination IP addresses, which mean something across any number of networks. The **link** layer adds the hardware addresses of the two ends of this one cable and puts the bits on the wire. A page request from `192.168.1.10` to a server at `10.0.0.50` leaves as the request text, wrapped in a transport header naming port 80, wrapped in an IP header saying `192.168.1.10` to `10.0.0.50`, wrapped in a frame header naming this workstation and the router on this segment. The router throws the frame away, leaves the IP header alone and writes a fresh frame for the next cable.',
    '',
    '## What trips people up',
    '',
    'Assuming all the addresses change at every hop. The IP addresses stay the same from end to end. The frame addresses are rewritten at every single hop, because they only ever describe one cable.',
    '',
    '## See it in NetForge',
    '',
    '- Run a `ping`, open **NetScope** and select one packet: the detail tree shows frame, IP and ICMP as separate layers you can expand.',
    '- Selecting a header highlights exactly its bytes in the hex pane, so you can see where one label ends and the next begins.',
  ),

  'ccna1-04-the-device-command-line': md(
    '## The idea in one breath',
    '',
    'A switch or a router has no screen. You talk to it by typing lines into a text prompt, and the prompt itself tells you where you are and what you are allowed to do from there.',
    '',
    '## Why it exists',
    '',
    'A box configured by clicking through menus can only be configured by a person standing in front of it. A box whose settings are lines of text can be read, compared with last week, saved, reviewed before a change, and pasted into a replacement after a failure. The whole configuration is a text file you can print and hand to someone.',
    '',
    '## How it actually works',
    '',
    'There are three places you can be. **User mode** lets you look at a few things. `enable` takes you to **privileged mode**, where every `show` command works. `configure terminal` takes you to **global configuration**, where what you type changes the device instead of reporting on it — `hostname LAB-SW1`, for example. Naming a port with `interface GigabitEthernet0/0` drops you one level deeper, into interface configuration, where `ip address 192.168.1.1 255.255.255.0` and `no shutdown` apply to that port alone. `exit` steps back one level, `end` jumps out entirely, and `show running-config` prints everything the device is doing right now. Most settings are undone by typing `no` in front of the line that made them.',
    '',
    '## What trips people up',
    '',
    'Typing a configuration command in the wrong mode and reading the rejection as "that command does not exist". It usually does exist, one level up or one level down. Read the prompt before you read the error message.',
    '',
    '## See it in NetForge',
    '',
    '- Open the **Terminal** on a switch and press `?` at any point: it lists what is valid right here, right now.',
    '- Walk `enable`, `configure terminal`, `hostname LAB-SW1`, `end`, `show running-config` and watch the prompt change at each step.',
    '- `show history` reprints what you have typed in this session.',
  ),

  'ccna1-05-ethernet-frames-and-mac-addresses': md(
    '## The idea in one breath',
    '',
    'On one cable segment, machines do not find each other by IP address. Every network adapter is born with a hardware address, and the frame — the wrapper that actually travels on the wire — carries one of those at each end.',
    '',
    '## Why it exists',
    '',
    'The link layer has to work before anything else can. A machine nobody has configured yet still needs to be addressable, or you could never configure it. Burning a unique number into every adapter at the factory gives every machine a name from the second it is powered on, with no setup of any kind.',
    '',
    '## How it actually works',
    '',
    'A hardware address is six bytes, written as twelve hex digits such as `00:1A:2B:3C:4D:5E`. The first half identifies the maker of the adapter and the second half is a serial number from that maker, so no two are alike. A frame begins with the destination hardware address, then the source, then a type field saying what is inside (IPv4, IPv6, ARP), then the payload, then a checksum that lets the receiver throw away a frame that arrived damaged. When `192.168.1.10` sends to `192.168.1.20` on one segment, the IP header names those two and the frame header names their two adapters. The address of all ones, `FF:FF:FF:FF:FF:FF`, means everybody on this segment, and everybody processes it.',
    '',
    '## What trips people up',
    '',
    'Expecting a hardware address to survive the journey. It does not. It is meaningful only on the one segment it was written for, and the first router replaces both of them. Hunting for a machine three networks away by its hardware address will never work.',
    '',
    '## See it in NetForge',
    '',
    '- Capture a `ping` in **NetScope** and read the first two fields of any frame.',
    '- `arp -a` on a workstation lists the hardware addresses it has learned for its neighbours.',
    '- `show mac address-table` on a switch lists every hardware address it has seen and the port it came in on.',
  ),

  'ccna1-06-switches-and-the-mac-table': md(
    '## The idea in one breath',
    '',
    'A switch starts knowing nothing. Every frame that arrives teaches it where one more machine lives, because the frame carries the address of the sender and the switch can see which port it came in on. After a few seconds of traffic it can deliver instead of shout.',
    '',
    '## Why it exists',
    '',
    'The device a switch replaced was a hub, and a hub copied every frame to every port. That spent the capacity of every cable on traffic nobody wanted and let every machine read every conversation. A switch that remembers where machines are sends each frame down one cable, so twenty conversations can run at once on twenty ports.',
    '',
    '## How it actually works',
    '',
    'Two rules, applied to every frame. **Learn:** write down the source address and the port it arrived on. **Forward:** look up the destination address. If it is in the table, send the frame out that one port. If it is not — or if it is the all-ones broadcast address — flood it out of every port except the one it came from. The reply then teaches the switch where the other machine is, so the second frame of a conversation is already delivered precisely. Entries are forgotten after a few minutes of silence, which is what lets you move a workstation to a different port without breaking it. With PC1 at `192.168.1.10` on `FastEthernet0/1` and PC2 at `192.168.1.20` on `FastEthernet0/2`, the first frame floods and everything after it does not.',
    '',
    '## What trips people up',
    '',
    'Believing a switch reads IP addresses. It never looks past the frame header. It will happily carry frames between two machines whose addresses put them in different subnets — the frames arrive and the hosts discard them, and the switch was never the problem.',
    '',
    '## See it in NetForge',
    '',
    '- Load the **Build a switched LAN** lab, ping across it, then run `show mac address-table` on the switch.',
    '- `clear mac address-table dynamic` empties the table. Ping again and watch the first frame flood in the **Packets** tab.',
    '- The **Tables** tab shows the same table updating live while traffic runs.',
  ),

  'ccna1-07-speed-duplex-and-autonegotiation': md(
    '## The idea in one breath',
    '',
    'The two ends of a copper link must agree on two things before it works: how fast they will run, and whether both may talk at the same time. Left alone they settle it in a fraction of a second. Forced by hand on one end only, they get it wrong and stay wrong.',
    '',
    '## Why it exists',
    '',
    'Old shared cable could carry one signal at a time, so adapters followed a rule: listen first, and if two of you start together, stop, wait a random moment and try again. Modern point-to-point copper has a separate pair for each direction and needs none of that. Since both generations had to live in the same building, adapters learned to ask each other what they can do.',
    '',
    '## How it actually works',
    '',
    'Autonegotiation is a short exchange when the link comes up: each end signals the speeds and duplex modes it supports, and both pick the best that appears on both lists. **Full duplex** means both directions at once, no collisions, and the listen-first rule switched off. **Half duplex** means one direction at a time with that rule still running. The failure that matters is the mismatch. Pin one end with `speed 100` and `duplex full` and leave the other on auto: the auto end hears no capability signal, falls back to half duplex, and now one end is checking for collisions while the other never stops sending. The link stays up. Small pings still answer. Throughput collapses and error counters climb.',
    '',
    '## What trips people up',
    '',
    'Reading a lit link as proof of a healthy link. A duplex mismatch keeps the light on. The symptom is slowness and rising errors rather than an outage, which is exactly why this fault can survive for months.',
    '',
    '## See it in NetForge',
    '',
    '- `show interfaces status` on a switch lists the speed and duplex every port settled on.',
    '- Pin one end in interface configuration with `speed 100` and `duplex full`, leave the other on auto, then push traffic across it.',
    '- `show interfaces` counts late collisions on the auto end, which settled on half duplex, and short, damaged frames on the pinned full-duplex end. That pair of counters is the signature.',
  ),

  'ccna1-08-what-an-ipv4-address-is': md(
    '## The idea in one breath',
    '',
    'An IPv4 address is two pieces of information in one number: which network the machine is on, and which machine it is on that network. The mask is what tells you where the split falls.',
    '',
    '## Why it exists',
    '',
    'Hardware addresses are unique but unsorted. Nothing about one tells you where the machine is, so a router would have to keep a list of every adapter on earth. Splitting the address into a network part and a host part lets a router keep one line for a whole network and forward by that line alone.',
    '',
    '## How it actually works',
    '',
    'An address is four bytes, written as four numbers from 0 to 255: `192.168.1.10`. The mask marks the network part with ones, starting from the left. `255.255.255.0`, written `/24` for short, means the first three bytes are the network and the last byte is the host. So `192.168.1.10/24` is host number 10 on network `192.168.1.0`. Two addresses in that range are spoken for: all host bits zero (`192.168.1.0`) names the network itself, and all host bits one (`192.168.1.255`) means everyone on it. That leaves `192.168.1.1` to `192.168.1.254` for machines, 254 of them. Move the mask and the split moves with it: `10.0.0.5/8` is a host on network `10.0.0.0`, one of sixteen million.',
    '',
    '## What trips people up',
    '',
    'Deciding two machines are neighbours because their addresses look alike. `192.168.1.10/24` and `192.168.2.10/24` differ by one digit and sit on different networks; they cannot talk without a router in between. The mask decides, never the resemblance.',
    '',
    '## See it in NetForge',
    '',
    '- Set an address from a workstation shell with `ip address 192.168.1.10 255.255.255.0`.',
    '- `ipconfig /all` shows what the host accepted, mask included.',
    '- Open the [subnetting view](concept:subnetting), type an address and a mask, and watch the boundary move.',
  ),

  'ccna1-09-binary-masks-and-subnet-boundaries': md(
    '## The idea in one breath',
    '',
    'Every address question — where does this subnet start, where does it end, is that machine a neighbour — is answered by lining the address up against the mask in binary. The decimal form is only a friendlier way of writing the same 32 bits.',
    '',
    '## Why it exists',
    '',
    'A router does no arithmetic on `255.255.255.192`. It does one bitwise operation and is done. Once you see the boundary the way the machine sees it, the odd-looking numbers stop being arbitrary and you can check a plan in your head instead of trusting a calculator.',
    '',
    '## How it actually works',
    '',
    'Each byte is eight bits worth 128, 64, 32, 16, 8, 4, 2 and 1. So 192 is 128 plus 64, which is `11000000`. A mask is always ones and then zeros, never mixed. Take `192.168.1.200` with mask `255.255.255.192`, which is `/26`. The last byte of the address is `11001000` and the last byte of the mask is `11000000`. Keep the address bits where the mask has ones and zero the rest: `11000000`, which is 192. The network address is `192.168.1.192`. Set every host bit to one instead and you get `11111111`, so the broadcast address is `192.168.1.255`. Everything between is usable: `.193` through `.254`. Six host bits give 64 addresses, minus the network and the broadcast, so 62 machines.',
    '',
    '## What trips people up',
    '',
    'Counting the addresses and forgetting to subtract two. A `/26` holds 64 addresses but only 62 machines, because the first and the last are reserved. The same slip puts a host on `.192` and leaves you wondering why nothing ever answers it.',
    '',
    '## See it in NetForge',
    '',
    '- The [subnetting view](concept:subnetting) has a **Bits and mask** pane that draws the 32 bits with the boundary where the ones stop.',
    '- Give one workstation `192.168.1.200 255.255.255.192` and another `192.168.1.100` with the same mask. The ping fails, and the binary told you why before you typed it.',
  ),

  'ccna1-10-build-a-small-lan': md(
    '## The idea in one breath',
    '',
    'Two workstations, one switch, two addresses in the same network. This is the smallest thing that deserves the name, and everything later in the course is this with more boxes around it.',
    '',
    '## Why it exists',
    '',
    'Every fault you will ever chase begins by asking whether the simple case works. If two machines on one switch cannot reach each other, nothing about routers or name servers matters yet. Being able to build the simple case from nothing, quickly, is what makes the complicated ones tractable.',
    '',
    '## How it actually works',
    '',
    'Three decisions, in this order. **The subnet:** pick one network for the segment and use it for both machines. In the lab that is `192.168.10.0/24`, so PC1 takes `.11`, PC2 takes `.12`, and both carry mask `255.255.255.0`. **The switch:** it needs no address at all to forward frames, so naming it is purely for you — the prompt then says which box you are typing on. **The proof:** one ping, then the tables that ping filled in. No gateway is set anywhere, and none is needed: both addresses are in one subnet, so each host delivers straight to the other.',
    '',
    '## What trips people up',
    '',
    'Reaching for a default gateway because the lab feels unfinished without one. A gateway is consulted only for a destination outside the subnet the host is already in. Adding one here changes nothing at all, and expecting the ping to fail without one is the misconception worth killing early.',
    '',
    '## See it in NetForge',
    '',
    '- Open the **Labs** tab and load **Build a switched LAN**. The topology is already cabled.',
    '- In each workstation shell: `ip address 192.168.10.11 255.255.255.0` and `ip address 192.168.10.12 255.255.255.0`.',
    '- On the switch: `enable`, `configure terminal`, `hostname LAB-SW1`.',
    '- `ping 192.168.10.12` from PC1, then `arp -a` on the host and `show mac address-table` on the switch.',
    '- Press **Check my work** in the lab panel to grade the tasks.',
  ),

  'ccna1-11-arp': md(
    '## The idea in one breath',
    '',
    'A host knows the IP address it wants to reach, but the frame needs a hardware address. ARP is the short shouted question that closes the gap: who holds this address? The owner answers, and the frame can finally be built.',
    '',
    '## Why it exists',
    '',
    'Nothing connects the two kinds of address. A hardware address is set at the factory; an IP address is handed out by a person or a server long afterwards. There is no formula from one to the other, so the only way to learn the pairing is to ask on the segment and let the owner speak for itself.',
    '',
    '## How it actually works',
    '',
    'PC1 at `192.168.1.10` wants to send to `192.168.1.20`. It checks its own cache first. If the answer is not there it broadcasts a request — destination hardware address all ones — carrying the question "who has `192.168.1.20`". Every machine on the segment receives it, and only the owner replies, directly to PC1, with its hardware address. PC1 stores the pair for a few minutes and sends the real frame. Because the request already carried the pairing for PC1 itself, the answering host learns PC1 at the same time, for free. If the destination is outside the subnet, the host asks for the hardware address of the gateway instead and sends the frame there, while the IP header still names the far machine.',
    '',
    '## What trips people up',
    '',
    'Seeing a cache entry for the gateway and concluding that the far-away destination is somehow known. The cache only ever holds neighbours on this segment. A packet crossing three routers involves four separate ARP conversations, one per segment, and none of them mentions the other three.',
    '',
    '## See it in NetForge',
    '',
    '- `arp -a` on a workstation prints its cache; `show arp` does the same on a switch or router.',
    '- On a switch or router, `clear arp-cache` empties it, so the next ping has to start from nothing; a host has no such command and its entries age out on their own after about 20 minutes.',
    '- Capture in **NetScope** and type `arp` in the filter bar to see the request and the reply as two frames.',
  ),

  'ccna1-12-ping-and-icmp': md(
    '## The idea in one breath',
    '',
    'Ping sends a small message that asks the far machine to send it straight back, and times the round trip. An answer proves a two-way path. The silence, or the complaint that comes instead, is a clue about where the path broke.',
    '',
    '## Why it exists',
    '',
    'IP itself reports nothing. A packet that cannot be delivered would simply vanish, leaving no way to tell a cut cable from a wrong address. A companion protocol for control messages gives the network a voice: it can say no route, too many hops, or nothing is listening here.',
    '',
    '## How it actually works',
    '',
    '`ping 192.168.1.20` builds an echo request, hands it to IP and starts a timer. The far host builds an echo reply with the same identifier and sends it back. Replies with times mean both directions work. What arrives instead is the interesting part. **Silence** usually means the request left and nothing answered: a wrong address, a down link, or a host that never received it. **Destination unreachable** from a router means the packet got that far and that router had nowhere to send it next — and the source address of the complaint names the box that gave up. **Time exceeded** means the packet is going round in a loop.',
    '',
    '## What trips people up',
    '',
    'Reading a failed ping as "the network is down". A ping proves a round trip and cannot tell you which direction failed. A request that arrives perfectly and a reply with no way home look identical from where you are standing, so always check that the far host has a route back to you.',
    '',
    '## See it in NetForge',
    '',
    '- `ping 192.168.1.20` from a workstation shell, or from the **Command Prompt** app on the desktop.',
    '- Ping an address nobody owns and watch the request leave with nothing behind it in the **Packets** tab.',
    '- Turn on simulation mode and step the echo request forward one hop at a time to see exactly where it stops.',
  ),

  'ccna1-13-the-default-gateway': md(
    '## The idea in one breath',
    '',
    'A host can deliver a packet itself only when the destination is inside its own subnet. For everything else it wraps the packet in a frame addressed to its gateway and lets the router worry about the rest.',
    '',
    '## Why it exists',
    '',
    'A workstation cannot hold a map of the world. Giving it one address to hand the hard cases to keeps hosts simple: a host needs to know its own network and one way out, and nothing more than that. The router is the one box that has to be clever.',
    '',
    '## How it actually works',
    '',
    'Before sending, the host compares the destination with its own address through its own mask. Same network part, and the destination is a neighbour: ARP for it and send the frame straight there. Different, and the default gateway is used instead. In the lab PC1 is `192.168.20.10/24` with gateway `192.168.20.1`. A ping to `192.168.20.1` is local, so it is one ARP and one frame. A ping to `192.168.21.10` is not: the IP header still says `192.168.21.10`, but the frame is addressed to the adapter of the router, and the router builds a new frame for the next segment. The gateway must sit inside that same subnet, because the host has to reach it directly to hand anything over.',
    '',
    '## What trips people up',
    '',
    'Setting a gateway that is not in the same subnet as the host — usually the right router, the wrong interface. The host cannot ARP for it, so nothing leaves at all, and the symptom looks like a dead machine instead of a one-digit typo.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Static address and default gateway** and set PC1 with `ip address 192.168.20.10 255.255.255.0 192.168.20.1`.',
    '- `ipconfig /all` shows the gateway it accepted.',
    '- Ping `192.168.20.1`, then `192.168.21.10`, and compare what each one puts on the wire in **NetScope**.',
  ),

  'ccna1-14-splitting-a-network-into-subnets': md(
    '## The idea in one breath',
    '',
    'Subnetting is taking one block of addresses and moving the mask to the right, which chops the block into several smaller ones. You trade host addresses for separate networks.',
    '',
    '## Why it exists',
    '',
    'One flat network of 254 machines means every broadcast reaches all 254, and any machine can reach any other with nothing in between to stop it. Splitting the block gives each floor, department or lab a network of its own, with a router in between that contains the broadcasts and gives you somewhere to control traffic.',
    '',
    '## How it actually works',
    '',
    'Borrow bits from the host part. Start with `192.168.1.0/24`: eight host bits and one network. Borrow two, making `/26`, and you have four subnets with six host bits each — 64 addresses, 62 usable. The subnets begin where the borrowed bits count up: `192.168.1.0`, `.64`, `.128` and `.192`. Each one ends just before the next begins, so `192.168.1.64/26` runs from `.64` (the network) to `.127` (the broadcast), with `.65` through `.126` for machines. The jump between subnets, 64 here, is the block size, and it is always 256 minus the last byte of the mask. Borrow three bits instead and you get eight subnets of 32 addresses, 30 usable each. The arithmetic never changes; only the distance you move the boundary.',
    '',
    '## What trips people up',
    '',
    'Sizing a subnet by counting machines and forgetting the two addresses every subnet loses, plus the one the router interface takes. A department of 30 machines does not fit in a `/27`: 32 addresses, minus network and broadcast, minus the gateway, leaves 29.',
    '',
    '## See it in NetForge',
    '',
    '- Open the [subnetting view](concept:subnetting), enter `192.168.1.0/24` and move the mask to watch the blocks appear.',
    '- Then address two workstations in different blocks and watch the ping fail before a router exists to join them.',
  ),

  'ccna1-15-a-subnet-plan-in-practice': md(
    '## The idea in one breath',
    '',
    'A plan on paper becomes a network when every interface gets the right address out of the right block. This lesson is that translation, done once and carefully.',
    '',
    '## Why it exists',
    '',
    'Plans fail in the last ten metres. The arithmetic is right, and then someone types the mask of the old flat network onto one interface, and two machines that were meant to be separated decide they are neighbours after all. Typing the plan in is where subnetting either works or quietly does not.',
    '',
    '## How it actually works',
    '',
    'Work interface by interface, not machine by machine. In the lab, `192.168.60.0/24` is split four ways at `/26`, so the blocks start at `192.168.60.0`, `.64`, `.128` and `.192` and every one of them carries mask `255.255.255.192`. Block one gets the router at `.1` and two workstations at `.10` and `.11`. Block two gets the router at `.65` and a workstation at `.74`. Notice that `.74` belongs to the second block, because the first one ended at `.63`. The mask is a property of the subnet, not of the machine: one interface configured with a different mask breaks that subnet for everybody on it, not just for itself.',
    '',
    '## What trips people up',
    '',
    'Typing `255.255.255.0` out of habit on one device. It still sends. It simply decides that an address in the next block is a neighbour, ARPs for a machine that is not on its segment, gets no answer, and the frame never leaves — while every other device on the same subnet behaves perfectly.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Apply a subnetting plan** from the **Labs** tab; the [subnetting view](concept:subnetting) is one click away whenever a boundary looks wrong.',
    '- On the router: `interface GigabitEthernet0/0`, `ip address 192.168.60.1 255.255.255.192`, `no shutdown`, then the same on `GigabitEthernet0/1` with `192.168.60.65`.',
    '- `show ip route` then lists one connected network per addressed, enabled interface.',
  ),

  'ccna1-16-what-a-router-does': md(
    '## The idea in one breath',
    '',
    'A router joins networks. Each of its interfaces sits in a different subnet, and when a packet arrives the router reads the destination address, finds the line in its table that matches it, and sends the packet out of the interface that line names.',
    '',
    '## Why it exists',
    '',
    'A switch cannot join subnets. It never reads the IP header, so it cannot make a decision based on which network an address belongs to. Something has to keep a table that says this range of addresses is that way, and rebuild the frame for every cable the packet crosses.',
    '',
    '## How it actually works',
    '',
    'Give an interface an address and enable it, and the router writes a route for that whole network into its table by itself — the live interface is the proof that the network is directly attached. In the lab, `GigabitEthernet0/0` takes `192.168.11.1/24` and `GigabitEthernet0/1` takes `192.168.12.1/24`, and the table gains two connected networks. A packet from `192.168.11.10` to `192.168.12.10` now arrives on the first interface. The router drops the frame, matches `192.168.12.10` against the table, finds the connected network on the second interface, ARPs for the destination if it must, builds a fresh frame and sends it. The IP header is untouched apart from a hop counter one lower.',
    '',
    '## What trips people up',
    '',
    'Forgetting `no shutdown`. An interface with a perfect address that was never enabled produces no route whatsoever, so the table simply has nothing in it — which reads like a routing problem rather than a switched-off port.',
    '',
    '## See it in NetForge',
    '',
    '- Load **Join two subnets with a router**.',
    '- On R1: `configure terminal`, `interface GigabitEthernet0/0`, `ip address 192.168.11.1 255.255.255.0`, `no shutdown`, then `GigabitEthernet0/1` with `192.168.12.1`.',
    '- `show ip route` lists the two connected networks and `show ip interface brief` shows both interfaces up.',
    '- Ping across, then follow the packet through R1 in the **Provenance** tab.',
  ),
};
