/**
 * Identifier types shared by every engine module.
 *
 * Devices, ports and links use *stable string ids* so that a saved `.netforge`
 * file round-trips without renumbering (spec §13.2). Hot-path objects created
 * at simulation time (PDUs, scheduler events) use monotonic numbers.
 */

/** Stable device id, e.g. `"d_7f3a"`. Generated by the simulation, never by the UI. */
export type DeviceId = string;

/**
 * Canonical *long* port name, unique within a device,
 * e.g. `"GigabitEthernet0/0"`, `"FastEthernet0/1"`, `"Console"`.
 * Short forms (`Gi0/0`, `Fa0/1`) are only ever accepted at the CLI and are
 * expanded to the canonical name before touching the engine.
 */
export type PortId = string;

/** Stable link id, e.g. `"l_02c1"`. */
export type LinkId = string;

/** Monotonic per-simulation PDU number. Cloned PDUs get a fresh id and keep `meta.parent`. */
export type PduId = number;

/** CLI session id (console/vty), e.g. `"s_1"`. */
export type SessionId = string;

/** Name of a protocol daemon inside a device: `'arp' | 'ipv4' | 'icmpv4' | 'eth-switch' | 'host'`. */
export type ProcessName = string;

/** Fully-qualified reference to one port of one device. */
export interface PortRef {
  device: DeviceId;
  port: PortId;
}

/** Stable map key for a PortRef. */
export const portKey = (r: PortRef): string => `${r.device}/${r.port}`;

export const samePort = (a: PortRef, b: PortRef): boolean =>
  a.device === b.device && a.port === b.port;
