/**
 * P2 acceptance — the P1-profile golden (ARCHITECTURE-P2 §0 rule 5, §7 W0, §9.2 W0 item 3, §9.3, §10.1 row
 * `accept.p2.p1-digests`).
 *
 * The silence rule is proved by a golden, not by an argument: test/goldens/p1-profile-digests.json was recorded from
 * the UNCHANGED engine (commit 7e623b9, before any P2 code) and every later wave must reproduce it byte for byte. The
 * only changes ever allowed are the ones §9.3 lists, each regenerated by the architect.
 *
 * Worlds: every template and every CCNA 1 lab (`[...TEMPLATES, ...CCNA1_LABS]`, i.e. every `SCENARIOS` entry of
 * category 'template' or 'ccna1-lab' — CCNA 2 labs appended from W5 are P2-profile worlds and are not part of it).
 * Each world is loaded the way the worker's `loadScenario` loads it (the lab seed, else SCENARIO_SEED; the lab stamp
 * when the entry has tasks; its scheduled faults) into `createSimulation({seed})`, which is the P1 profile.
 *
 * The fixed script, at fixed sim times (runFor only, so a change shows up where it happens instead of shifting the
 * schedule):
 *   t = 0      load the world;                        runFor(60 s)  — every model boots (routers take 45 s)
 *   t = 60 s   the lab's reference solution through `Simulation.configure`, exactly as written (none for a template);
 *                                                     runFor(30 s)  — leases, SLAAC and Wi-Fi joins complete
 *   t = 90 s   one `ping` typed on a fresh console;  runFor(20 s)  — five echoes, 2 s timeouts, ARP/ND
 *   t = 110 s  one `show` typed on a fresh console;  runFor(600 s) — §10.1 `runFor(600 s)`; the world ends at 710 s
 *
 * What the golden holds per world, and how it is compared:
 *   • `events` — one `p0EventLine` per trace event of EVERY kind (debug and log included, nothing tolerated), in
 *     emission order: `<t>|<kind>|<first 16 hex digits of SHA-256 over the canonical JSON of the event>`, the event
 *     normalised by test/accept.p05.harness.ts `normalizeP0Event` (port MACs → owner tokens, FcsRecompute values
 *     masked, RouteRow.owner dropped). `eventsDigest` is the SHA-256 of those lines joined by '\n'.
 *   • `typed` — the CliResult of the ping and of the show (a synchronous `show` prints through its result, not the
 *     trace, so its text is kept verbatim here; the ping's report arrives as cliOutput events and is in `events`).
 *   • `snapshot` — SHA-256 of the canonical JSON of the final snapshot after the ONE fixed normalisation rule of §10.1
 *     (`normaliseSnapshot`): StateViews of daemons the P1 engine did not have, extra tables it did not have, and the
 *     members of the model-derived lists (capabilities, GUI panels, port allowedRoles) it did not have are removed.
 *     "What the P1 engine had" is `p1Vocabulary`, recorded with the golden and never re-recorded; a guard test proves
 *     that everything outside it is a P2 daemon (all its CAPABILITY_PROCESSES rows `since: 'P2'`) or a table whose
 *     descriptor is `since: 'P2'`. `snapshotParts` hashes each device and each other top-level member separately,
 *     so a mismatch names the device.
 * A mismatch fails with a readable report: the world, the first diverging event (golden line, fresh line and the
 * fresh event's normalised JSON), the per-kind counts that moved and a per-event diff.
 *
 * The SHA-256 is plain TypeScript (no dependency); a test proves it on known answers and proves that every event
 * line equals the harness `p0EventLine` exactly.
 *
 * Regenerating (the architect only, and only for a §9.3 change): `NF_RECORD_P1_DIGESTS=<world,world,…|all>` re-records
 * the named worlds, keeps every other entry and the P1 vocabulary as they are, prints the per-event diff of each
 * re-recorded world for the wave report, and refuses a world whose solution or typed lines were refused or whose
 * ping got no reply.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { assert, beforeAll, describe, expect, it } from 'vitest';
import { CAPABILITIES, CAPABILITY_PROCESSES, GUI_PANELS, PORT_ROLES, PROCESS_ORDER } from '../src/contracts/catalog.js';
import type { DeviceId, SessionId } from '../src/contracts/ids.js';
import type { ScenarioInfo } from '../src/contracts/scenario.js';
import type { Simulation } from '../src/contracts/simulation.js';
import type { SimSnapshot } from '../src/contracts/snapshot.js';
import { TABLE_DESCRIPTORS } from '../src/contracts/tables.js';
import { SEC } from '../src/contracts/time.js';
import type { TraceEvent } from '../src/contracts/trace.js';
import { CCNA1_LABS, SCENARIOS, SCENARIO_SEED, TEMPLATES } from '../src/sim/scenarios.js';
import { createSimulation } from '../src/sim/simulation.js';
import { canonicalJson, macOwners, normalizeP0Event, p0EventLine } from './accept.p05.harness.js';

// ── the fixed script ────────────────────────────────────────────────────────

/** Boot: every model of a template or lab is up (the router takes 45 s), as in the lab tests. */
const BOOT_NS = 60 * SEC;
/** After the solution: DHCP leases, SLAAC addresses and Wi-Fi joins complete well inside this. */
const SETTLE_NS = 30 * SEC;
/** After the ping: five echoes with 2 s timeouts, plus address resolution. */
const PING_NS = 20 * SEC;
/** §10.1: `runFor(600 s)` after the script. */
const RUN_NS = 600 * SEC;

/** The script timings as the golden records them (seconds). */
const SCRIPT_TIMES = { bootS: BOOT_NS / SEC, settleS: SETTLE_NS / SEC, pingS: PING_NS / SEC, runS: RUN_NS / SEC };

/** One line typed on a fresh console of the device with this topology name. */
type Typed = readonly [device: string, line: string];

/**
 * The ping and the show of each world. The ping crosses the world's switches, routers, hub, radios or air (the
 * lab's own reachability task where it has one); the show reads the state that ping built. Targets are the
 * addresses the world really has at t = 90 s (leases and SLAAC addresses included). No show is typed on a device
 * whose console the solution protects with a password.
 */
const SCRIPTS: Readonly<Record<string, { readonly ping: Typed; readonly show: Typed }>> = {
  'two-pcs-and-switch': { ping: ['PC1', 'ping 10.0.0.2'], show: ['SW1', 'show mac address-table'] },
  'pc-router-pc': { ping: ['PC1', 'ping 10.0.1.1'], show: ['R1', 'show ip route'] },
  'three-routers': { ping: ['PC1', 'ping 10.3.0.10'], show: ['R2', 'show ip route'] },
  'home-wifi': { ping: ['LAPTOP1', 'ping 192.168.1.10'], show: ['LAPTOP1', 'show wireless'] },
  'hub-collision': { ping: ['PC1', 'ping 10.0.0.3'], show: ['PC1', 'show arp'] },
  'serial-pair': { ping: ['PC1', 'ping 10.2.0.10'], show: ['R1', 'show interfaces Serial0/0/0'] },
  'multilayer-routed-port': { ping: ['PC1', 'ping 10.9.9.1'], show: ['MLS1', 'show ip route'] },
  'radio-bridge': { ping: ['PC1', 'ping 10.0.0.2'], show: ['SW2', 'show mac address-table'] },
  'cellular-phones': { ping: ['PHONE1', 'ping 10.20.0.100'], show: ['SRV1', 'show arp'] },
  'ccna1-switched-lan': { ping: ['PC1', 'ping 192.168.10.12'], show: ['SW1', 'show mac address-table'] },
  'ccna1-default-gateway': { ping: ['PC1', 'ping 192.168.21.10'], show: ['R1', 'show ip interface brief'] },
  'ccna1-device-hardening': { ping: ['ADMIN1', 'ping 192.168.50.2'], show: ['R1', 'show ip interface brief'] },
  'ccna1-subnetting-plan': { ping: ['PC1', 'ping 192.168.60.74'], show: ['R1', 'show ip route'] },
  'ccna1-two-subnets': { ping: ['PC1', 'ping 192.168.12.10'], show: ['R1', 'show ip route'] },
  'ccna1-static-routes': { ping: ['PC1', 'ping 10.3.0.10'], show: ['R2', 'show ip route'] },
  'ccna1-traceroute-path': { ping: ['PC1', 'ping 10.3.0.10'], show: ['R2', 'show ip route'] },
  'ccna1-dhcpv4-server': { ping: ['PC1', 'ping 192.168.15.12'], show: ['R1', 'show ip dhcp binding'] },
  'ccna1-dhcp-relay': { ping: ['PC1', 'ping 10.10.0.2'], show: ['R2', 'show ip dhcp binding'] },
  'ccna1-dns-records': { ping: ['PC1', 'ping www.lab.nf'], show: ['SW1', 'show mac address-table'] },
  'ccna1-web-server': { ping: ['PC1', 'ping www.lab.nf'], show: ['SW1', 'show mac address-table'] },
  'ccna1-ipv6-slaac': { ping: ['PC1', 'ping 2001:db8:2:0:e4:3eff:fe28:1c01'], show: ['R1', 'show ipv6 route'] },
  'ccna1-home-wifi': { ping: ['LAPTOP1', 'ping 192.168.1.10'], show: ['LAPTOP1', 'show wireless'] },
  'ccna1-troubleshoot-addressing': { ping: ['PC1', 'ping 192.168.31.10'], show: ['R1', 'show ip route'] },
  'ccna1-troubleshoot-ports': { ping: ['PC1', 'ping 192.168.35.12'], show: ['SW1', 'show interfaces FastEthernet0/1'] },
};

/** The P1-profile worlds, in golden order: the templates (menu order), then the CCNA 1 labs (course order). */
function worlds(): readonly ScenarioInfo[] {
  return [...TEMPLATES, ...CCNA1_LABS];
}

// ── the golden file ─────────────────────────────────────────────────────────

/** What the P1 engine knew; the snapshot normalisation removes anything outside it (§10.1). */
interface P1Vocabulary {
  readonly processes: readonly string[];
  readonly tables: readonly string[];
  readonly capabilities: readonly string[];
  readonly guiPanels: readonly string[];
  readonly portRoles: readonly string[];
}

/** One typed line and the CliResult it returned (JSON copy). */
interface TypedResult {
  readonly device: string;
  readonly line: string;
  readonly result: unknown;
}

/** The golden record of one world. */
interface WorldEntry {
  readonly seed: number;
  readonly endNs: number;
  readonly typed: readonly TypedResult[];
  readonly eventCount: number;
  readonly eventsDigest: string;
  readonly snapshot: string;
  readonly snapshotParts: Readonly<Record<string, string>>;
  readonly events: readonly string[];
}

/** Contents of test/goldens/p1-profile-digests.json. */
interface GoldenFile {
  readonly about: string;
  readonly script: typeof SCRIPT_TIMES;
  readonly p1Vocabulary: P1Vocabulary;
  readonly worlds: Readonly<Record<string, WorldEntry>>;
}

const GOLDEN_URL = new URL('./goldens/p1-profile-digests.json', import.meta.url);

const ABOUT =
  'P1-profile digests (ARCHITECTURE-P2 §0 rule 5, §9.3, §10.1 accept.p2.p1-digests), recorded from the unchanged engine ' +
  'at commit 7e623b9 before any P2 code. One entry per template and CCNA 1 lab: the fixed script of ' +
  'test/accept.p2.p1-digests.test.ts (boot, the reference solution, one ping, one show, runFor 600 s), the p0EventLine of ' +
  'every trace event of every kind, the typed CLI results, and hashes of the normalised end snapshot. Change it only as ' +
  '§9.3 allows, by re-recording the affected worlds with NF_RECORD_P1_DIGESTS.';

let goldenCache: GoldenFile | undefined;

/** The golden file (read once). */
function golden(): GoldenFile {
  if (goldenCache === undefined) {
    if (!existsSync(GOLDEN_URL)) throw new Error('test/goldens/p1-profile-digests.json is missing; it is recorded once, from the unchanged engine (§7 W0).');
    goldenCache = JSON.parse(readFileSync(GOLDEN_URL, 'utf8')) as GoldenFile;
  }
  return goldenCache;
}

/** The vocabulary of the engine as it is now (read at call time). */
function currentVocabulary(): P1Vocabulary {
  return {
    processes: [...PROCESS_ORDER],
    tables: Object.keys(TABLE_DESCRIPTORS),
    capabilities: [...CAPABILITIES],
    guiPanels: [...GUI_PANELS],
    portRoles: [...PORT_ROLES],
  };
}

/** The P1 vocabulary: the golden's, or (only when the golden is first recorded) the engine's own. */
function p1Vocabulary(): P1Vocabulary {
  return existsSync(GOLDEN_URL) ? golden().p1Vocabulary : currentVocabulary();
}

// ── SHA-256 (FIPS 180-4), plain TypeScript ──────────────────────────────────

const SHA256_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be,
  0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa,
  0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85,
  0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
  0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f,
  0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
] as const;
const SHA256_H0 = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19] as const;

const rotr = (x: number, n: number): number => (x >>> n) | (x << (32 - n));

/** Lower-case hex SHA-256 of the UTF-8 bytes of `text`. */
function sha256Hex(text: string): string {
  const data = new TextEncoder().encode(text);
  const blocks = Math.ceil((data.length + 9) / 64);
  const buf = new Uint8Array(blocks * 64);
  buf.set(data);
  buf[data.length] = 0x80;
  const view = new DataView(buf.buffer);
  view.setUint32(buf.length - 8, Math.floor(data.length / 0x20000000));
  view.setUint32(buf.length - 4, (data.length * 8) >>> 0);
  const h: number[] = [...SHA256_H0];
  const w: number[] = new Array<number>(64).fill(0);
  for (let base = 0; base < buf.length; base += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getInt32(base + i * 4);
    for (let i = 16; i < 64; i++) {
      const x = w[i - 15]!;
      const y = w[i - 2]!;
      const s0 = rotr(x, 7) ^ rotr(x, 18) ^ (x >>> 3);
      const s1 = rotr(y, 17) ^ rotr(y, 19) ^ (y >>> 10);
      w[i] = (w[i - 16]! + s0 + w[i - 7]! + s1) | 0;
    }
    let [a, b, c, d, e, f, g, hh] = h as [number, number, number, number, number, number, number, number];
    for (let i = 0; i < 64; i++) {
      const t1 = (hh + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA256_K[i]! + w[i]!) | 0;
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) | 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) | 0;
    }
    const out = [a, b, c, d, e, f, g, hh];
    for (let i = 0; i < 8; i++) h[i] = (h[i]! + out[i]!) | 0;
  }
  return h.map((x) => (x >>> 0).toString(16).padStart(8, '0')).join('');
}

/** `<t>|<kind>|<16 hex>` — byte-identical to the harness `p0EventLine`, with the SHA-256 above. */
function eventLine(ev: TraceEvent, owners: ReadonlyMap<string, string>): string {
  const normalized = normalizeP0Event(ev, owners);
  return `${String(normalized.t)}|${String(normalized.kind)}|${sha256Hex(canonicalJson(normalized)).slice(0, 16)}`;
}

// ── the snapshot normalisation (§10.1, written once in W0) ──────────────────

/** `value` as a list (empty when it is not one). */
function listOf(value: unknown): unknown[] {
  return Array.isArray(value) ? (value as unknown[]) : [];
}

/** A JSON object's members (an empty record when `value` is not an object). */
function recordOf(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

/**
 * THE fixed rule of §10.1: a JSON copy of `snapshot` without the StateViews of daemons outside `vocab.processes`
 * (P2 daemons), without extra tables outside `vocab.tables` (descriptors `since: 'P2'`; a list left empty is dropped,
 * as P1 never has an empty one), and without P2 members of the model-derived lists `capabilities`, `gui` and each
 * port's `allowedRoles`. Nothing else is touched.
 */
function normaliseSnapshot(snapshot: SimSnapshot, vocab: P1Vocabulary): Record<string, unknown> {
  const processes = new Set(vocab.processes);
  const tables = new Set(vocab.tables);
  const capabilities = new Set(vocab.capabilities);
  const guiPanels = new Set(vocab.guiPanels);
  const portRoles = new Set(vocab.portRoles);
  const copy = JSON.parse(JSON.stringify(snapshot)) as Record<string, unknown>;
  for (const d of listOf(copy['devices']).map(recordOf)) {
    if (Array.isArray(d['processes'])) d['processes'] = listOf(d['processes']).filter((v) => processes.has(String(recordOf(v)['process'])));
    const t = recordOf(d['tables']);
    if (Array.isArray(t['extra'])) {
      const kept = listOf(t['extra']).filter((x) => tables.has(String(recordOf(x)['name'])));
      if (kept.length === 0) delete t['extra'];
      else t['extra'] = kept;
    }
    if (Array.isArray(d['capabilities'])) d['capabilities'] = listOf(d['capabilities']).filter((c) => capabilities.has(String(c)));
    if (Array.isArray(d['gui'])) d['gui'] = listOf(d['gui']).filter((g) => guiPanels.has(String(g)));
    for (const p of listOf(d['ports']).map(recordOf)) {
      if (Array.isArray(p['allowedRoles'])) p['allowedRoles'] = listOf(p['allowedRoles']).filter((r) => portRoles.has(String(r)));
    }
  }
  return copy;
}

/** 16-hex hashes of each device (`devices/<id>`) and of every other top-level member of a normalised snapshot. */
function snapshotParts(normalised: Record<string, unknown>): Record<string, string> {
  const parts: Record<string, string> = {};
  for (const key of Object.keys(normalised).sort()) {
    if (key === 'devices') {
      for (const d of listOf(normalised[key]).map(recordOf)) parts[`devices/${String(d['id'])}`] = sha256Hex(canonicalJson(d)).slice(0, 16);
    } else {
      parts[key] = sha256Hex(canonicalJson(normalised[key])).slice(0, 16);
    }
  }
  return parts;
}

/** The part of a normalised snapshot a `snapshotParts` key names. */
function snapshotPart(normalised: Record<string, unknown>, key: string): unknown {
  if (!key.startsWith('devices/')) return normalised[key];
  const id = key.slice('devices/'.length);
  return listOf(normalised['devices']).find((d) => String(recordOf(d)['id']) === id);
}

// ── one run of a world ──────────────────────────────────────────────────────

/** One scripted run of a world: its golden entry plus what the reports need. */
interface WorldRun {
  readonly entry: WorldEntry;
  readonly events: readonly TraceEvent[];
  readonly owners: ReadonlyMap<string, string>;
  readonly normalised: Record<string, unknown>;
  /** Solution lines the CLI refused (`<device>: <line>: <message>`). */
  readonly refused: readonly string[];
  /** Trace events the ring evicted (must be 0: every event is digested). */
  readonly dropped: number;
  /** The ping job's report (cliOutput of its session). */
  readonly pingReport: string;
}

/** Device id of a topology name. */
function idOf(sim: Simulation, name: string): DeviceId {
  for (const d of sim.devices()) if (d.spec.name === name) return d.id;
  throw new Error(`no device called ${name} in this world`);
}

/** Type `line` on a fresh console of `name`, keeping a JSON copy of the result. */
function typeLine(sim: Simulation, [name, line]: Typed): { typed: TypedResult; session: SessionId } {
  const session = sim.cli.open(idOf(sim, name), 'console');
  const result = sim.cli.exec(session, line);
  return { typed: { device: name, line, result: JSON.parse(JSON.stringify(result)) as unknown }, session };
}

/** Run the fixed script on `sc` from a fresh simulation. */
function runWorld(sc: ScenarioInfo): WorldRun {
  const script = SCRIPTS[sc.name];
  if (script === undefined) throw new Error(`the P1 digest script has no entry for ${sc.name}`);
  const seed = sc.seed ?? SCENARIO_SEED;
  const sim = createSimulation({ seed });
  const topo = sc.build();
  sim.loadTopology((sc.tasks?.length ?? 0) > 0 ? { ...topo, lab: { name: sc.name, version: sc.version ?? 1 } } : topo);
  for (const f of sc.faults ?? []) sim.injectFault(f.at, f.fault);
  sim.runFor(BOOT_NS);

  const refused: string[] = [];
  for (const [name, lines] of Object.entries(sc.solution ?? {})) {
    const r = sim.configure(idOf(sim, name), lines);
    for (const l of r.lines) if (!l.ok) refused.push(`${name}: ${l.line}: ${l.error?.message ?? l.output}`);
  }
  sim.runFor(SETTLE_NS);

  const ping = typeLine(sim, script.ping);
  sim.runFor(PING_NS);
  const show = typeLine(sim, script.show);
  sim.runFor(RUN_NS);

  const trace = sim.trace(0);
  const snapshot = sim.snapshot();
  const owners = macOwners(snapshot);
  const events = trace.events;
  const lines = events.map((ev) => eventLine(ev, owners));
  const normalised = normaliseSnapshot(snapshot, p1Vocabulary());
  let pingReport = '';
  for (const ev of events) if (ev.kind === 'cliOutput' && ev.session === ping.session) pingReport += ev.text;
  const entry: WorldEntry = {
    seed,
    endNs: sim.now,
    typed: [ping.typed, show.typed],
    eventCount: lines.length,
    eventsDigest: sha256Hex(lines.join('\n')),
    snapshot: sha256Hex(canonicalJson(normalised)),
    snapshotParts: snapshotParts(normalised),
    events: lines,
  };
  return { entry, events, owners, normalised, refused, dropped: trace.dropped, pingReport };
}

const runCache = new Map<string, WorldRun>();

/** The scripted run of `sc` (once per test file run: the script is deterministic). */
function freshRun(sc: ScenarioInfo): WorldRun {
  let run = runCache.get(sc.name);
  if (run === undefined) {
    run = runWorld(sc);
    runCache.set(sc.name, run);
  }
  return run;
}

// ── readable reports ────────────────────────────────────────────────────────

/** `text` cut to `max` characters. */
function clip(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max)}… (${text.length - max} more characters)`;
}

/** The normalised JSON of the run's event `i`, clipped. */
function runEventJson(run: WorldRun, i: number, max: number): string {
  const ev = run.events[i];
  return ev === undefined ? '' : clip(canonicalJson(normalizeP0Event(ev, run.owners)), max);
}

/** Largest middle section the per-event diff aligns exactly (golden events × run events). */
const DIFF_CELLS = 4_000_000;

/**
 * Per-event diff of `expected` (golden lines) against the run's lines: `-` golden-only events, `+` run-only events
 * with their normalised JSON. A longest-common-subsequence alignment of the section between the common prefix and
 * suffix; at most `limit` changed events are listed.
 */
function eventDiff(expected: readonly string[], run: WorldRun, limit: number): string[] {
  const actual = run.entry.events;
  let lo = 0;
  while (lo < expected.length && lo < actual.length && expected[lo] === actual[lo]) lo++;
  let hiE = expected.length;
  let hiA = actual.length;
  while (hiE > lo && hiA > lo && expected[hiE - 1] === actual[hiA - 1]) {
    hiE--;
    hiA--;
  }
  const n = hiE - lo;
  const m = hiA - lo;
  const out: string[] = [];
  const minus = (i: number): void => void out.push(`  - golden #${i}  ${expected[i]}`);
  const plus = (j: number): void => void out.push(`  + run    #${j}  ${actual[j]}  ${runEventJson(run, j, 240)}`);
  if (n * m > DIFF_CELLS) {
    for (let k = 0; k < limit && (lo + k < hiE || lo + k < hiA); k++) {
      if (lo + k < hiE) minus(lo + k);
      if (lo + k < hiA) plus(lo + k);
    }
    out.push(`  (the differing sections are too long to align: ${n} golden and ${m} run events)`);
    return out;
  }
  // lcs[i][j] = longest common subsequence of expected[lo+i..hiE) and actual[lo+j..hiA).
  const width = m + 1;
  const lcs = new Uint32Array((n + 1) * width);
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      lcs[i * width + j] = expected[lo + i] === actual[lo + j] ? lcs[(i + 1) * width + j + 1]! + 1 : Math.max(lcs[(i + 1) * width + j]!, lcs[i * width + j + 1]!);
    }
  }
  let i = 0;
  let j = 0;
  let changes = 0;
  while ((i < n || j < m) && changes < limit) {
    if (i < n && j < m && expected[lo + i] === actual[lo + j]) {
      i++;
      j++;
    } else if (i < n && (j === m || lcs[(i + 1) * width + j]! >= lcs[i * width + j + 1]!)) {
      minus(lo + i++);
      changes++;
    } else {
      plus(lo + j++);
      changes++;
    }
  }
  if (i < n || j < m) out.push('  … (more changed events not listed)');
  return out;
}

/** Event kinds counted from `<t>|<kind>|<digest>` lines. */
function kindCounts(lines: readonly string[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const line of lines) {
    const kind = line.split('|')[1] ?? '?';
    counts.set(kind, (counts.get(kind) ?? 0) + 1);
  }
  return counts;
}

/** Empty when the run's events equal the golden's; otherwise a report naming the world and the first diverging event. */
function eventReport(name: string, expected: readonly string[], run: WorldRun): string {
  const actual = run.entry.events;
  let first = 0;
  while (first < expected.length && first < actual.length && expected[first] === actual[first]) first++;
  if (first === expected.length && first === actual.length) return '';
  const out = [
    `P1-profile trace of world "${name}" differs from test/goldens/p1-profile-digests.json (§9.3 lists the only allowed changes).`,
    `First diverging event: #${first} (the golden has ${expected.length} events, this run ${actual.length}).`,
    `  golden: ${expected[first] ?? '(no more events)'}`,
    `  run:    ${actual[first] ?? '(no more events)'}`,
  ];
  if (first < actual.length) out.push(`  run event #${first} (normalised): ${runEventJson(run, first, 1500)}`);
  const goldenAt = first < expected.length ? actual.indexOf(expected[first]!, first) : -1;
  if (first < expected.length) out.push(goldenAt < 0 ? '  the golden event does not occur later in this run' : `  the golden event occurs later in this run, at #${goldenAt}`);
  const before = kindCounts(expected);
  const after = kindCounts(actual);
  const moved = [...new Set([...before.keys(), ...after.keys()])]
    .sort()
    .filter((k) => before.get(k) !== after.get(k))
    .map((k) => `${k} ${before.get(k) ?? 0} → ${after.get(k) ?? 0}`);
  out.push(`Event counts that changed: ${moved.length === 0 ? 'none (same kinds and counts, different content or order)' : moved.join(', ')}.`);
  out.push('Per-event diff (golden → run, first 40 changes):', ...eventDiff(expected, run, 40));
  return out.join('\n');
}

/** Empty when the normalised snapshot equals the golden's; otherwise the parts that differ, with the run's JSON. */
function snapshotReport(name: string, expected: WorldEntry, run: WorldRun): string {
  if (expected.snapshot === run.entry.snapshot) return '';
  const got = run.entry.snapshotParts;
  const keys = [...new Set([...Object.keys(expected.snapshotParts), ...Object.keys(got)])].sort();
  const out = [`Normalised end snapshot of world "${name}" differs from the golden (hash ${expected.snapshot} → ${run.entry.snapshot}).`];
  for (const key of keys) {
    const was = expected.snapshotParts[key];
    const now = got[key];
    if (was === now) continue;
    if (was === undefined) out.push(`  ${key}: not in the golden; run: ${clip(canonicalJson(snapshotPart(run.normalised, key)), 1500)}`);
    else if (now === undefined) out.push(`  ${key}: in the golden, missing from this run`);
    else out.push(`  ${key}: differs; run: ${clip(canonicalJson(snapshotPart(run.normalised, key)), 1500)}`);
  }
  if (out.length === 1) out.push('  every part hashes the same: the device order changed');
  return out.join('\n');
}

// ── recording (the architect, §9.3) ─────────────────────────────────────────

const RECORD = (process.env['NF_RECORD_P1_DIGESTS'] ?? '').trim();

/** Re-record the worlds `RECORD` names (`all` = every world), keeping every other entry and the P1 vocabulary. */
function record(): void {
  const all = worlds();
  const names = RECORD === 'all' ? all.map((s) => s.name) : RECORD.split(',').map((s) => s.trim()).filter((s) => s !== '');
  for (const name of names) if (!all.some((s) => s.name === name)) throw new Error(`NF_RECORD_P1_DIGESTS names ${name}, which is not a P1-profile world`);
  const previous = existsSync(GOLDEN_URL) ? golden() : undefined;
  if (previous !== undefined && canonicalJson(previous.script) !== canonicalJson(SCRIPT_TIMES) && RECORD !== 'all') {
    throw new Error('the script timings changed: that re-records every world (NF_RECORD_P1_DIGESTS=all)');
  }
  const worldsOut: Record<string, WorldEntry> = {};
  for (const sc of all) {
    const old = previous?.worlds[sc.name];
    if (!names.includes(sc.name)) {
      if (old === undefined) throw new Error(`${sc.name} has no golden entry yet; re-record it too`);
      worldsOut[sc.name] = old;
      continue;
    }
    const run = freshRun(sc);
    const problems = [...run.refused];
    for (const t of run.entry.typed) {
      const error = recordOf(t.result)['error'];
      if (error !== undefined) problems.push(`${t.device}> ${t.line}: ${canonicalJson(error)}`);
    }
    if (!/received [1-9]/.test(run.pingReport)) problems.push(`the ping got no reply: ${JSON.stringify(run.pingReport)}`);
    if (run.dropped !== 0) problems.push(`the trace ring evicted ${run.dropped} events`);
    if (problems.length > 0) throw new Error(`refusing to record ${sc.name}:\n  ${problems.join('\n  ')}`);
    if (old !== undefined) {
      const report = [eventReport(sc.name, old.events, run), snapshotReport(sc.name, old, run)].filter((r) => r !== '').join('\n');
      console.log(report === '' ? `${sc.name}: unchanged` : `${sc.name}: re-recorded\n${report}`);
    }
    worldsOut[sc.name] = run.entry;
  }
  const file: GoldenFile = { about: ABOUT, script: SCRIPT_TIMES, p1Vocabulary: previous?.p1Vocabulary ?? currentVocabulary(), worlds: worldsOut };
  writeFileSync(GOLDEN_URL, `${JSON.stringify(file, null, 2)}\n`);
  goldenCache = file;
}

// ── the tests ───────────────────────────────────────────────────────────────

describe('accept P2: the P1-profile digests', () => {
  // Regeneration is a step before the comparison, not a test: an ordinary run neither records nor skips anything.
  beforeAll(() => {
    if (RECORD !== '') record();
  });

  it('covers every template and every CCNA 1 lab with the fixed script', () => {
    const names = worlds().map((s) => s.name);
    expect(SCENARIOS.filter((s) => s.category === 'template' || s.category === 'ccna1-lab').map((s) => s.name)).toEqual(names);
    expect(Object.keys(SCRIPTS)).toEqual(names);
    expect(Object.keys(golden().worlds)).toEqual(names);
    expect(golden().script).toEqual(SCRIPT_TIMES);
    expect(golden().about).toBe(ABOUT);
  });

  it('hashes with a plain TypeScript SHA-256 whose event lines are exactly the harness p0EventLine', () => {
    expect(sha256Hex('')).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
    expect(sha256Hex('abc')).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
    expect(sha256Hex('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')).toBe('248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1');
    expect(sha256Hex('a'.repeat(1_000_000))).toBe('cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0');
    for (const sc of worlds()) {
      const run = freshRun(sc);
      expect(run.entry.events, sc.name).toEqual(run.events.map((ev) => p0EventLine(ev, run.owners)));
    }
  });

  it('normalises the snapshot by removing only what P2 added (§10.1)', () => {
    const p1 = golden().p1Vocabulary;
    const now = currentVocabulary();
    // Nothing the P1 engine had is gone or reordered: P2 only inserts (PROCESS_ORDER) or appends.
    for (const key of ['processes', 'tables', 'capabilities', 'guiPanels', 'portRoles'] as const) {
      expect(now[key].filter((x) => p1[key].includes(x)), key).toEqual(p1[key]);
    }
    // Every daemon outside the P1 list is a P2 daemon: each of its CAPABILITY_PROCESSES rows is `since: 'P2'`.
    const rows = Object.values(CAPABILITY_PROCESSES).flat();
    for (const name of now.processes.filter((x) => !p1.processes.includes(x))) {
      expect(rows.filter((r) => r.process === name).map((r) => r.since as string).filter((s) => s !== 'P2'), name).toEqual([]);
    }
    // Every table outside the P1 list has a `since: 'P2'` descriptor.
    const descriptors: Readonly<Record<string, { readonly since: string }>> = TABLE_DESCRIPTORS;
    for (const name of now.tables.filter((x) => !p1.tables.includes(x))) expect(descriptors[name]?.since, name).toBe('P2');
  });

  for (const sc of worlds()) {
    it(`${sc.name}: every trace event, the typed results and the normalised snapshot equal the P1 golden`, () => {
      const expected = golden().worlds[sc.name];
      if (expected === undefined) return assert.fail(`${sc.name} has no entry in test/goldens/p1-profile-digests.json`);
      const run = freshRun(sc);
      expect(run.refused, `${sc.name}: solution lines the CLI refused`).toEqual([]);
      expect(run.dropped, `${sc.name}: trace events evicted before they were digested`).toBe(0);

      const events = eventReport(sc.name, expected.events, run);
      if (events !== '') assert.fail(events);
      expect(run.entry.typed, `${sc.name}: the typed ping and show`).toEqual(expected.typed);
      const snapshot = snapshotReport(sc.name, expected, run);
      if (snapshot !== '') assert.fail(snapshot);
      expect(run.entry).toEqual(expected);
    });
  }
});
