/**
 * test/p2-digests.harness.ts — the P2-profile golden (ARCHITECTURE-P3 §0 rules 5, 9, 14; D3; §4.6; §7 W0; §9.2 W0
 * item 6; §9.4; §10.1 rows `accept.p3.p2-digests-templates`, `-labs-a`, `-labs-b`, `-guards`). Not a test file: the
 * four shard files call `describeP2DigestShard` with their shard name.
 *
 * The silence rule of P3a is proved by goldens, not by an argument. test/goldens/p2-profile-digests.json was recorded
 * from the UNCHANGED engine (commit 5263f16, before any P3 code) and every later wave must reproduce it byte for byte;
 * the only changes ever allowed are the ones §9.4 lists, each regenerated by the architect.
 *
 * Worlds (32, D3), in golden order:
 *   • the 9 templates (menu order), each loaded as a P2 world: the template document with `profile: 'P2'` and the
 *     schema id that can express it (1.2), into `createSimulation({seed})` — shard `templates`;
 *   • the 20 CCNA 2 labs (course order), each loaded exactly as the worker's `loadScenario` loads it (the lab seed,
 *     else SCENARIO_SEED; the lab stamp; the scheduled faults injected right after the load) — the first ten in shard
 *     `labs-a`, the other ten in shard `labs-b`;
 *   • one P2 sandbox built through `addDevice` / `addLink` in `createSimulation({seed, profile: 'P2'})` (NF-C2960,
 *     NF-C3650-24, NF-2911, NF-AP-1832, NF-WLC-9800, two PCs), which pins the new-world `profileConfig` path — shard
 *     `labs-b`;
 *   • the two synthetic D22 guard worlds `guard-switch-svi/P1` and `guard-switch-svi/P2` (an NF-C2960 whose Vlan1 is
 *     addressed and up, an NF-2911 serving DHCP on that VLAN, two DHCP PCs, a router traceroute to the SVI and a
 *     browser fetch to the SVI), without which the D22 guard would measure nothing (no shipped world addresses a
 *     switch SVI in a VLAN that carries UDP or TCP) — shard `guards`.
 *
 * The fixed script (P1's, D3), at fixed sim times, runFor only (a change shows up where it happens instead of
 * shifting the schedule):
 *   t = 0      build the world;                                       runFor(60 s)  — every model boots
 *   t = 60 s   the setup lines through `Simulation.configure`, exactly as written: a lab's reference solution, the
 *              sandbox's two PC addresses, the guard PCs' `ip address dhcp` (none for a template);
 *                                                                     runFor(30 s)  — leases, SLAAC, joins, STP
 *   t = 90 s   the probes: one `ping` typed on a fresh console (the guard worlds instead: `traceroute` to the SVI
 *              typed on the router and a browser fetch of `http://<SVI>/` from a PC — their DHCP leases are the
 *              setup);                                                runFor(20 s)
 *   t = 110 s  one `show` typed on a fresh console (never one whose output a §9.2 item changes: never
 *              `show errdisable recovery`, never `show access-lists`); runFor(600 s) — the world ends at 710 s.
 *
 * What the golden holds per world (D3 "Storage": P2 worlds emit background BPDUs, so P1's one-line-per-event format
 * is used only for the events that matter):
 *   • `eventCount`, `eventsDigest` (SHA-256 of EVERY event line joined by '\n') and `kinds` (per-kind counts over
 *     every event, debug and log included, nothing tolerated);
 *   • `windows` — one `<count>:<16 hex>` per 10-second window of sim time (window k holds the events with
 *     k·10 s ≤ t < (k+1)·10 s), so a mismatch names its window;
 *   • `events` — the full event line of every event NOT attributable to a background PDU (`backgroundFlags`);
 *   • `typed` — the CliResult of each typed line (the ping and traceroute reports arrive as cliOutput events and are
 *     in the digests), and for a browser fetch its ticket and the tab the http-client daemon holds 20 s later;
 *   • `snapshot` / `snapshotParts` — SHA-256 of the canonical JSON of the end snapshot after the per-device
 *     normalisation of §4.6 item 2 (`normaliseSnapshot`), whole and per device.
 * An event line is P1's: `<t>|<kind>|<first 16 hex of SHA-256 over the canonical JSON of the event>`, the event
 * normalised by test/accept.p05.harness.ts `normalizeP0Event`; the SHA-256 is plain TypeScript (no dependency), proved
 * on known answers and against the harness `p0EventLine`.
 *
 * Background attribution (D3): an event is attributable to a background PDU when every PDU it references is
 * background. PDUs referenced: `pdu.id` of frameTx, frameRx, frameAbort, drop, pduCreated and pduConsumed; `pdu` of
 * mutation, backoff and carrierDefer; `pdus` of collision; `event.data.pdu` of debug. A PDU is background when a
 * frameTx or drop of it carries `background: true` (PduMeta.background), or when it is a clone (`PduSummary.parent`)
 * of a background PDU. Every other event (table writes, logs, port and link states, configuration, CLI, …) is kept.
 *
 * Normalisation (§4.6 item 2, one rule applied per device against the recorded `p2Vocabulary`): a device loses the
 * StateView and the owned tables (`PROCESS_TABLES`) of every process it runs that is outside the P2 vocabulary or that
 * it derives only through `CAPABILITY_PROCESSES` rows whose `since` is a stage the golden did not have (D22: `udp`,
 * `tcp`, `sockets` leave a managed switch, a router's `udp` stays); every extra table outside the P2 vocabulary or
 * whose descriptor `since` is such a stage; the members of `capabilities`, `gui` and each port's `allowedRoles` outside
 * the P2 vocabulary; and every port's `txBacklog` (the P3 FIFO view, D16, named by the W0 ruling R6; absent at
 * 5263f16, so on the unchanged engine the rule removes nothing). The P0 frame count `txQueue` is NOT part of the rule:
 * it is live engine data (`p.tx.queue`, shown by `show interfaces` and the port inspector; 22 of the 32 worlds end with
 * a count above 0). The snapshot hashes were re-recorded with `txQueue` kept on 2026-09-30 (ruling R13): only
 * `snapshot` / `snapshotParts` moved in the 32 worlds; every event, window, count and typed result stayed identical.
 * The P2 guard (every shard) proves that everything outside `p2Vocabulary` is of a later stage, and a synthetic case
 * proves the per-device rule.
 *
 * Recording (the architect only, and only for a §9.4 change): `NF_RECORD_P2_DIGESTS=<world,world,…|all>` re-records
 * the named worlds of the shard being run (`all` = every world of that shard), keeps every other entry and the P2
 * vocabulary, prints the per-event diff of each re-recorded world for the wave report, and refuses a world whose setup
 * or typed lines were refused, whose ping got no reply, whose trace ring evicted events, or (guards) whose guard facts
 * do not hold. Shards run in parallel may record together: the merge into the one golden file is done under a lock
 * file. An ordinary run never records.
 */
import { closeSync, existsSync, openSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { assert, beforeAll, describe, expect, it } from 'vitest';
import { BUILD_STAGES, CAPABILITIES, CAPABILITY_PROCESSES, GUI_PANELS, PORT_ROLES, PROCESS_ORDER } from '../src/contracts/catalog.js';
import type { DeviceId, SessionId } from '../src/contracts/ids.js';
import type { ScenarioInfo } from '../src/contracts/scenario.js';
import type { Simulation } from '../src/contracts/simulation.js';
import type { SimSnapshot } from '../src/contracts/snapshot.js';
import { PROCESS_TABLES, TABLE_DESCRIPTORS } from '../src/contracts/tables.js';
import { SEC } from '../src/contracts/time.js';
import type { TraceEvent } from '../src/contracts/trace.js';
import { TOPOLOGY_SCHEMA_ID_1_1, TOPOLOGY_SCHEMA_ID_1_2, type Topology } from '../src/contracts/topology.js';
import { CCNA2_LABS, SCENARIO_SEED, TEMPLATES } from '../src/sim/scenarios.js';
import { createSimulation } from '../src/sim/simulation.js';
import { canonicalJson, macOwners, normalizeP0Event, p0EventLine } from './accept.p05.harness.js';

// ── the fixed script ────────────────────────────────────────────────────────

/** Boot: every model is up (the router takes 45 s). */
const BOOT_NS = 60 * SEC;
/** After the setup lines: DHCP leases, SLAAC, Wi-Fi and CAPWAP joins, spanning tree. */
const SETTLE_NS = 30 * SEC;
/** After the probes: five echoes with 2 s timeouts, a traceroute, a page load. */
const PROBE_NS = 20 * SEC;
/** §10.1 `runFor(600 s)` after the script. */
const RUN_NS = 600 * SEC;
/** One digest window of sim time (D3: per-10-second-window digests). */
export const WINDOW_NS = 10 * SEC;

/**
 * Wall-clock budgets. A shard runs its worlds once (cached per test file) inside whichever case first needs them, in
 * well under a minute alone; the budgets leave room for a loaded machine running the whole slow project.
 */
const SHARD_CASE_TIMEOUT_MS = 180_000;
/** Recording re-runs a shard's worlds and waits for the golden's lock (at most 120 s). */
const RECORD_TIMEOUT_MS = 600_000;

/** The script timings as the golden records them (seconds). */
const SCRIPT_TIMES = { bootS: BOOT_NS / SEC, settleS: SETTLE_NS / SEC, probeS: PROBE_NS / SEC, runS: RUN_NS / SEC, windowS: WINDOW_NS / SEC };

/** A line typed on a fresh console of the device with this topology name. */
export type Typed = readonly [device: string, line: string];

/** What the script does at t = 90 s. */
export type Probe =
  /** A line typed on a fresh console (a ping, the guard's traceroute). */
  | { readonly kind: 'cli'; readonly device: string; readonly line: string }
  /** The Desktop browser's one call: `hostRequest(device, { app: 'http.get', url })`. */
  | { readonly kind: 'browse'; readonly device: string; readonly url: string };

/** The four shards (§10.1), each its own test file. */
export type P2DigestShard = 'templates' | 'labs-a' | 'labs-b' | 'guards';

/** One world of the P2 golden. */
export interface P2World {
  /** Golden key. */
  readonly name: string;
  readonly shard: P2DigestShard;
  readonly seed: number;
  /** The world at t = 0: loaded (and its faults injected), or built by addDevice / addLink. */
  build(): Simulation;
  /** Lines configured at t = 60 s through `Simulation.configure`, per device name, exactly as written. */
  readonly setup: Readonly<Record<string, readonly string[]>>;
  readonly probes: readonly Probe[];
  readonly show: Typed;
}

const ping = (device: string, target: string): Probe => ({ kind: 'cli', device, line: `ping ${target}` });

/**
 * The templates' ping and show — the P1 golden's choices (test/accept.p2.p1-digests.test.ts `SCRIPTS`), which hold in
 * the P2 profile too.
 */
const TEMPLATE_SCRIPTS: Readonly<Record<string, { readonly ping: Probe; readonly show: Typed }>> = {
  'two-pcs-and-switch': { ping: ping('PC1', '10.0.0.2'), show: ['SW1', 'show mac address-table'] },
  'pc-router-pc': { ping: ping('PC1', '10.0.1.1'), show: ['R1', 'show ip route'] },
  'three-routers': { ping: ping('PC1', '10.3.0.10'), show: ['R2', 'show ip route'] },
  'home-wifi': { ping: ping('LAPTOP1', '192.168.1.10'), show: ['LAPTOP1', 'show wireless'] },
  'hub-collision': { ping: ping('PC1', '10.0.0.3'), show: ['PC1', 'show arp'] },
  'serial-pair': { ping: ping('PC1', '10.2.0.10'), show: ['R1', 'show interfaces Serial0/0/0'] },
  'multilayer-routed-port': { ping: ping('PC1', '10.9.9.1'), show: ['MLS1', 'show ip route'] },
  'radio-bridge': { ping: ping('PC1', '10.0.0.2'), show: ['SW2', 'show mac address-table'] },
  'cellular-phones': { ping: ping('PHONE1', '10.20.0.100'), show: ['SRV1', 'show arp'] },
};

/**
 * The CCNA 2 labs' ping and show, in course order. The ping is the lab's own reachability task (from a host, to the
 * address the target really has at t = 90 s, SLAAC and DHCPv6 addresses included); the show reads the state the lab
 * is about. No lab solution protects a console with a password.
 */
const LAB_SCRIPTS: Readonly<Record<string, { readonly ping: Probe; readonly show: Typed }>> = {
  'ccna2-switch-management': { ping: ping('TECH1', '192.168.99.2'), show: ['SW1', 'show ip interface brief'] },
  'ccna2-vlan-access-ports': { ping: ping('PC1', '192.168.10.12'), show: ['SW1', 'show vlan brief'] },
  'ccna2-trunk-native-allowed': { ping: ping('PC1', '192.168.10.13'), show: ['SW1', 'show interfaces trunk'] },
  'ccna2-dtp-modes': { ping: ping('PC1', '192.168.10.13'), show: ['SW1', 'show interfaces trunk'] },
  'ccna2-router-on-a-stick': { ping: ping('PC1', '192.168.20.10'), show: ['R1', 'show ip route'] },
  'ccna2-l3-switch-svis': { ping: ping('PC2', '172.16.1.10'), show: ['MLS1', 'show ip route'] },
  'ccna2-troubleshoot-vlans': { ping: ping('PC1', '192.168.30.100'), show: ['SW1', 'show interfaces trunk'] },
  'ccna2-stp-root-placement': { ping: ping('PC1', '192.168.10.13'), show: ['AS1', 'show spanning-tree'] },
  'ccna2-rapid-stp': { ping: ping('PC1', '192.168.15.12'), show: ['SW1', 'show spanning-tree'] },
  'ccna2-stp-guards': { ping: ping('PC3', '192.168.16.100'), show: ['AS1', 'show spanning-tree'] },
  'ccna2-etherchannel-lacp': { ping: ping('PC1', '192.168.17.13'), show: ['SW1', 'show etherchannel summary'] },
  'ccna2-dhcpv6': { ping: ping('PC2', '2001:db8:a:0:56:45ff:fe97:5701'), show: ['R1', 'show ipv6 dhcp binding'] },
  'ccna2-hsrp-gateway': { ping: ping('PC1', '192.168.20.100'), show: ['R1', 'show standby brief'] },
  'ccna2-port-security': { ping: ping('PC2', '192.168.23.100'), show: ['SW1', 'show port-security'] },
  'ccna2-wlc-wlan': { ping: ping('LAPTOP1', '192.168.20.1'), show: ['R1', 'show ip route'] },
  'ccna2-static-routes': { ping: ping('PC1', '10.2.0.10'), show: ['R1', 'show ip route'] },
  'ccna2-floating-static': { ping: ping('PC1', '198.51.100.10'), show: ['R1', 'show ip route'] },
  'ccna2-ipv6-static': { ping: ping('PC1', '2001:db8:2:0:e4:3eff:fe28:1c01'), show: ['R1', 'show ipv6 route'] },
  'ccna2-nat-pat': { ping: ping('PC1', '198.51.100.10'), show: ['R1', 'show ip nat translations'] },
  'ccna2-troubleshoot-routing': { ping: ping('PC1', '192.168.20.100'), show: ['R1', 'show ip route'] },
};

/** The CCNA 2 labs of 5263f16, in course order: the first ten are shard `labs-a`, the rest `labs-b`. */
const CCNA2_LAB_NAMES: readonly string[] = Object.keys(LAB_SCRIPTS);
const LABS_A_COUNT = 10;

/** A template document as a P2 world: `profile: 'P2'` and the schema that can express it (1.2). */
function asP2Document(t: Topology): Topology {
  return { ...t, schema: TOPOLOGY_SCHEMA_ID_1_2, profile: 'P2' };
}

/** The world as the worker's `loadScenario` loads it: seed, lab stamp when the entry has tasks, scheduled faults. */
function loadLike(sc: ScenarioInfo, topo: Topology): Simulation {
  const sim = createSimulation({ seed: sc.seed ?? SCENARIO_SEED });
  sim.loadTopology((sc.tasks?.length ?? 0) > 0 ? { ...topo, lab: { name: sc.name, version: sc.version ?? 1 } } : topo);
  for (const f of sc.faults ?? []) sim.injectFault(f.at, f.fault);
  return sim;
}

function templateWorld(sc: ScenarioInfo): P2World {
  const script = TEMPLATE_SCRIPTS[sc.name];
  if (script === undefined) throw new Error(`the P2 digest script has no entry for template ${sc.name}`);
  return {
    name: sc.name,
    shard: 'templates',
    seed: sc.seed ?? SCENARIO_SEED,
    build: () => loadLike(sc, asP2Document(sc.build())),
    setup: {},
    probes: [script.ping],
    show: script.show,
  };
}

function labWorld(sc: ScenarioInfo, index: number): P2World {
  const script = LAB_SCRIPTS[sc.name];
  if (script === undefined) throw new Error(`the P2 digest script has no entry for lab ${sc.name}`);
  return {
    name: sc.name,
    shard: index < LABS_A_COUNT ? 'labs-a' : 'labs-b',
    seed: sc.seed ?? SCENARIO_SEED,
    build: () => loadLike(sc, sc.build()),
    setup: sc.solution ?? {},
    probes: [script.ping],
    show: script.show,
  };
}

// ── the P2 sandbox (addDevice) ──────────────────────────────────────────────

/** Golden key of the addDevice sandbox. */
export const SANDBOX_WORLD = 'p2-sandbox-add-device';
const SANDBOX_SEED = 1;

/** The sandbox a learner builds on an empty P2 canvas: seven devices placed, then cabled, nothing configured. */
function sandboxWorld(): P2World {
  return {
    name: SANDBOX_WORLD,
    shard: 'labs-b',
    seed: SANDBOX_SEED,
    build: () => {
      const sim = createSimulation({ seed: SANDBOX_SEED, profile: 'P2' });
      const add = (type: string, name: string, x: number, y: number): DeviceId => sim.addDevice({ type, name, position: { x, y } });
      const sw1 = add('switch.nfc2960', 'SW1', 300, 250);
      const mls1 = add('mlswitch.nfc3650-24', 'MLS1', 500, 150);
      const r1 = add('router.nf2911', 'R1', 700, 150);
      const ap1 = add('ap.nfap-lw', 'AP1', 150, 150);
      const wlc1 = add('wlc.nfwlc9800', 'WLC1', 500, 30);
      const pc1 = add('pc.nfpc', 'PC1', 150, 400);
      const pc2 = add('pc.nfpc', 'PC2', 450, 400);
      const cable = (a: DeviceId, ap: string, b: DeviceId, bp: string): void => void sim.addLink({ a: { device: a, port: ap }, b: { device: b, port: bp } });
      cable(pc1, 'GigabitEthernet0', sw1, 'FastEthernet0/1');
      cable(pc2, 'GigabitEthernet0', sw1, 'FastEthernet0/2');
      cable(ap1, 'GigabitEthernet0', sw1, 'FastEthernet0/3');
      cable(sw1, 'GigabitEthernet0/1', mls1, 'GigabitEthernet1/0/1');
      cable(mls1, 'GigabitEthernet1/0/2', r1, 'GigabitEthernet0/0');
      cable(wlc1, 'GigabitEthernet0/1', mls1, 'GigabitEthernet1/0/3');
      return sim;
    },
    setup: { PC1: ['ip address 10.0.0.1 255.255.255.0'], PC2: ['ip address 10.0.0.2 255.255.255.0'] },
    probes: [ping('PC1', '10.0.0.2')],
    show: ['SW1', 'show vlan brief'],
  };
}

// ── the synthetic D22 guard worlds ──────────────────────────────────────────

/** The switch SVI both guard worlds aim at. */
export const GUARD_SVI = '192.168.1.2';
const GUARD_SEED = 22;
/** Golden keys of the two guard worlds. */
export const GUARD_WORLDS = { P1: 'guard-switch-svi/P1', P2: 'guard-switch-svi/P2' } as const;

/** Startup text: each section's lines followed by `!`, then `end`. */
function startup(sections: readonly (readonly string[])[]): string {
  const out: string[] = [];
  for (const s of sections) out.push(...s, '!');
  out.push('end', '');
  return out.join('\n');
}

/**
 * PC1 and PC2 (DHCP) and R1 (the DHCP server, 192.168.1.1) on SW1, whose Vlan1 is 192.168.1.2/24 and up. The PCs'
 * DISCOVER and REQUEST broadcasts reach the SVI; R1 traceroutes to it and PC1's browser fetches `http://<SVI>/`.
 */
function guardDocument(profile: 'P1' | 'P2'): Topology {
  const at = (x: number, y: number): { logical: [number, number] } => ({ logical: [x, y] });
  const t: Topology = {
    schema: profile === 'P2' ? TOPOLOGY_SCHEMA_ID_1_2 : TOPOLOGY_SCHEMA_ID_1_1,
    seed: GUARD_SEED,
    devices: [
      {
        id: 'r1', type: 'router.nf2911', name: 'R1', position: at(500, 120), power: true,
        config: startup([
          ['hostname R1'],
          ['interface GigabitEthernet0/0', ' ip address 192.168.1.1 255.255.255.0', ' no shutdown'],
          ['ip dhcp excluded-address 192.168.1.1 192.168.1.10'],
          ['ip dhcp pool GUARD', ' network 192.168.1.0 255.255.255.0', ' default-router 192.168.1.1'],
        ]),
      },
      {
        id: 'sw1', type: 'switch.nfc2960', name: 'SW1', position: at(300, 220), power: true,
        config: startup([['hostname SW1'], ['interface Vlan1', ` ip address ${GUARD_SVI} 255.255.255.0`, ' no shutdown'], ['ip default-gateway 192.168.1.1']]),
      },
      { id: 'pc1', type: 'pc.nfpc', name: 'PC1', position: at(100, 340), power: true, config: startup([['hostname PC1']]) },
      { id: 'pc2', type: 'pc.nfpc', name: 'PC2', position: at(300, 400), power: true, config: startup([['hostname PC2']]) },
    ],
    links: [
      { id: 'l_pc1_sw1', a: { device: 'pc1', port: 'GigabitEthernet0' }, b: { device: 'sw1', port: 'FastEthernet0/1' }, media: 'auto', length_m: 3 },
      { id: 'l_pc2_sw1', a: { device: 'pc2', port: 'GigabitEthernet0' }, b: { device: 'sw1', port: 'FastEthernet0/2' }, media: 'auto', length_m: 3 },
      { id: 'l_r1_sw1', a: { device: 'r1', port: 'GigabitEthernet0/0' }, b: { device: 'sw1', port: 'GigabitEthernet0/1' }, media: 'auto', length_m: 3 },
    ],
  };
  return profile === 'P2' ? { ...t, profile: 'P2' } : t;
}

function guardWorld(profile: 'P1' | 'P2'): P2World {
  return {
    name: GUARD_WORLDS[profile],
    shard: 'guards',
    seed: GUARD_SEED,
    build: () => {
      const sim = createSimulation({ seed: GUARD_SEED });
      sim.loadTopology(guardDocument(profile));
      return sim;
    },
    setup: { PC1: ['ip address dhcp'], PC2: ['ip address dhcp'] },
    probes: [
      { kind: 'cli', device: 'R1', line: `traceroute ${GUARD_SVI}` },
      { kind: 'browse', device: 'PC1', url: `http://${GUARD_SVI}/` },
    ],
    show: ['R1', 'show ip dhcp binding'],
  };
}

/** Every world of the golden, in golden order (read at call time, rule 12). */
export function p2Worlds(): readonly P2World[] {
  return [
    ...TEMPLATES.map(templateWorld),
    ...CCNA2_LABS.map((sc, i) => labWorld(sc, i)),
    sandboxWorld(),
    guardWorld('P1'),
    guardWorld('P2'),
  ];
}

/** The worlds of one shard, in golden order. */
export function shardWorlds(shard: P2DigestShard): readonly P2World[] {
  return p2Worlds().filter((w) => w.shard === shard);
}

// ── the golden file ─────────────────────────────────────────────────────────

/** What the P2 engine knew; the snapshot normalisation removes what a later stage adds (§4.6). */
export interface P2Vocabulary {
  readonly stages: readonly string[];
  readonly processes: readonly string[];
  readonly tables: readonly string[];
  readonly capabilities: readonly string[];
  readonly guiPanels: readonly string[];
  readonly portRoles: readonly string[];
}

/** One typed line (or browser fetch) and what it returned (JSON copy). */
export interface TypedResult {
  readonly device: string;
  readonly line: string;
  readonly result: unknown;
}

/** The golden record of one world. */
export interface WorldEntry {
  readonly profile: string;
  readonly seed: number;
  readonly endNs: number;
  readonly typed: readonly TypedResult[];
  readonly eventCount: number;
  readonly eventsDigest: string;
  readonly kinds: Readonly<Record<string, number>>;
  readonly windows: readonly string[];
  readonly snapshot: string;
  readonly snapshotParts: Readonly<Record<string, string>>;
  /** Lines of the events not attributable to a background PDU, in emission order. */
  readonly events: readonly string[];
}

/** Contents of test/goldens/p2-profile-digests.json. */
interface GoldenFile {
  readonly about: string;
  readonly script: typeof SCRIPT_TIMES;
  readonly p2Vocabulary: P2Vocabulary;
  readonly worlds: Readonly<Record<string, WorldEntry>>;
}

const GOLDEN_URL = new URL('./goldens/p2-profile-digests.json', import.meta.url);
const LOCK_PATH = `${fileURLToPath(GOLDEN_URL)}.lock`;

const ABOUT =
  'P2-profile digests (ARCHITECTURE-P3 §0 rule 5, D3, §4.6, §9.4, §10.1 accept.p3.p2-digests-*), recorded from the ' +
  'unchanged engine at commit 5263f16 before any P3 code. One entry per P2 world (the 9 templates as P2 worlds, the 20 ' +
  'CCNA 2 labs, the addDevice sandbox, the two D22 guard worlds): the fixed script of test/p2-digests.harness.ts ' +
  '(boot, the setup lines, the probes, one show, runFor 600 s), per-kind counts and the digest of every trace event, ' +
  'per-10-second-window digests, the event lines not attributable to a background PDU, the typed results, and hashes ' +
  'of the normalised end snapshot. Change it only as §9.4 allows, by re-recording the affected worlds with ' +
  'NF_RECORD_P2_DIGESTS.';

let goldenCache: GoldenFile | undefined;

/** The golden file (read once per test file). */
function golden(): GoldenFile {
  if (goldenCache === undefined) {
    if (!existsSync(GOLDEN_URL)) throw new Error('test/goldens/p2-profile-digests.json is missing; it is recorded once, from the unchanged engine (P3 §7 W0).');
    goldenCache = JSON.parse(readFileSync(GOLDEN_URL, 'utf8')) as GoldenFile;
  }
  return goldenCache;
}

/** The vocabulary of the engine as it is now (read at call time). */
export function currentVocabulary(): P2Vocabulary {
  return {
    stages: [...BUILD_STAGES],
    processes: [...PROCESS_ORDER],
    tables: Object.keys(TABLE_DESCRIPTORS),
    capabilities: [...CAPABILITIES],
    guiPanels: [...GUI_PANELS],
    portRoles: [...PORT_ROLES],
  };
}

/** The P2 vocabulary: the golden's, or (only when the golden is first recorded) the engine's own. */
function p2Vocabulary(): P2Vocabulary {
  return existsSync(GOLDEN_URL) ? golden().p2Vocabulary : currentVocabulary();
}

// ── SHA-256 (FIPS 180-4), plain TypeScript (the P1 golden's) ────────────────

const SHA256_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be,
  0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa,
  0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85,
  0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
  0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f,
  0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
] as const;
const SHA256_H0 = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19] as const;

const rotr = (x: number, n: number): number => (x >>> n) | (x << (32 - n));

/** Lower-case hex SHA-256 of the UTF-8 bytes of `text`. */
export function sha256Hex(text: string): string {
  const data = new TextEncoder().encode(text);
  const blocks = Math.ceil((data.length + 9) / 64);
  const buf = new Uint8Array(blocks * 64);
  buf.set(data);
  buf[data.length] = 0x80;
  const view = new DataView(buf.buffer);
  view.setUint32(buf.length - 8, Math.floor(data.length / 0x20000000));
  view.setUint32(buf.length - 4, (data.length * 8) >>> 0);
  const h: number[] = [...SHA256_H0];
  const w: number[] = new Array<number>(64).fill(0);
  for (let base = 0; base < buf.length; base += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getInt32(base + i * 4);
    for (let i = 16; i < 64; i++) {
      const x = w[i - 15]!;
      const y = w[i - 2]!;
      const s0 = rotr(x, 7) ^ rotr(x, 18) ^ (x >>> 3);
      const s1 = rotr(y, 17) ^ rotr(y, 19) ^ (y >>> 10);
      w[i] = (w[i - 16]! + s0 + w[i - 7]! + s1) | 0;
    }
    let [a, b, c, d, e, f, g, hh] = h as [number, number, number, number, number, number, number, number];
    for (let i = 0; i < 64; i++) {
      const t1 = (hh + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA256_K[i]! + w[i]!) | 0;
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) | 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) | 0;
    }
    const out = [a, b, c, d, e, f, g, hh];
    for (let i = 0; i < 8; i++) h[i] = (h[i]! + out[i]!) | 0;
  }
  return h.map((x) => (x >>> 0).toString(16).padStart(8, '0')).join('');
}

/** `<t>|<kind>|<16 hex>` — byte-identical to the harness `p0EventLine`, with the SHA-256 above. */
export function eventLine(ev: TraceEvent, owners: ReadonlyMap<string, string>): string {
  const normalized = normalizeP0Event(ev, owners);
  return `${String(normalized.t)}|${String(normalized.kind)}|${sha256Hex(canonicalJson(normalized)).slice(0, 16)}`;
}

// ── background attribution (D3) ─────────────────────────────────────────────

/** A JSON object's members (an empty record when `value` is not an object). */
function recordOf(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

/** `value` as a list (empty when it is not one). */
function listOf(value: unknown): unknown[] {
  return Array.isArray(value) ? (value as unknown[]) : [];
}

/** A PDU id as a map key (ids are numbers; a string id is accepted too). */
function pduKey(value: unknown): string | undefined {
  return typeof value === 'number' || typeof value === 'string' ? String(value) : undefined;
}

/** The PDUs an event references (empty for events about no PDU). */
export function referencedPdus(ev: TraceEvent): string[] {
  const e = ev as unknown as Record<string, unknown>;
  const keys: (string | undefined)[] = [];
  switch (ev.kind) {
    case 'frameTx':
    case 'frameRx':
    case 'frameAbort':
    case 'drop':
    case 'pduCreated':
    case 'pduConsumed':
      keys.push(pduKey(recordOf(e['pdu'])['id']));
      break;
    case 'mutation':
    case 'backoff':
    case 'carrierDefer':
      keys.push(pduKey(e['pdu']));
      break;
    case 'collision':
      for (const id of listOf(e['pdus'])) keys.push(pduKey(id));
      break;
    case 'debug':
      keys.push(pduKey(recordOf(ev.event.data)['pdu']));
      break;
    default:
      break;
  }
  return keys.filter((k): k is string => k !== undefined);
}

/** Per event: true when it is attributable to a background PDU (every PDU it references is background). */
export function backgroundFlags(events: readonly TraceEvent[]): boolean[] {
  const background = new Set<string>();
  const parentOf = new Map<string, string>();
  for (const ev of events) {
    const e = ev as unknown as Record<string, unknown>;
    const summary = recordOf(e['pdu']);
    const id = pduKey(summary['id']);
    if (id === undefined) continue;
    const parent = pduKey(summary['parent']);
    if (parent !== undefined) parentOf.set(id, parent);
    if ((ev.kind === 'frameTx' || ev.kind === 'drop') && e['background'] === true) background.add(id);
  }
  // a clone of a background PDU is background (clone chains are short; iterate to the fixpoint)
  for (let changed = true; changed; ) {
    changed = false;
    for (const [child, parent] of parentOf) {
      if (!background.has(child) && background.has(parent)) {
        background.add(child);
        changed = true;
      }
    }
  }
  return events.map((ev) => {
    const refs = referencedPdus(ev);
    return refs.length > 0 && refs.every((r) => background.has(r));
  });
}

// ── the snapshot normalisation (§4.6 item 2) ────────────────────────────────

/** The contract data the normalisation reads (the real contracts, read at call time; a test passes its own). */
export interface NormalisationContracts {
  readonly capabilityProcesses: Readonly<Record<string, readonly { readonly process: string; readonly since: string }[]>>;
  readonly processTables: Readonly<Record<string, readonly string[] | undefined>>;
  readonly tableDescriptors: Readonly<Record<string, { readonly since: string } | undefined>>;
}

function realContracts(): NormalisationContracts {
  return {
    capabilityProcesses: CAPABILITY_PROCESSES as unknown as NormalisationContracts['capabilityProcesses'],
    processTables: PROCESS_TABLES as unknown as NormalisationContracts['processTables'],
    tableDescriptors: TABLE_DESCRIPTORS as unknown as NormalisationContracts['tableDescriptors'],
  };
}

/**
 * THE rule of §4.6 item 2: a JSON copy of `snapshot` where each device loses the StateViews and owned tables of the
 * processes it runs outside `vocab.processes` or derives only through capability rows of a stage the golden did not
 * have, every extra table outside `vocab.tables` or whose descriptor is of such a stage (a list left empty is
 * dropped), the members of `capabilities`, `gui` and `allowedRoles` outside the vocabulary, and every port's P3
 * display member `txBacklog` (the FIFO view, D16, ruling R6). The P0 frame count `txQueue` is kept. Nothing else
 * is touched.
 */
export function normaliseSnapshot(snapshot: SimSnapshot, vocab: P2Vocabulary, contracts: NormalisationContracts = realContracts()): Record<string, unknown> {
  const stages = new Set(vocab.stages);
  const processes = new Set(vocab.processes);
  const tables = new Set(vocab.tables);
  const capabilities = new Set(vocab.capabilities);
  const guiPanels = new Set(vocab.guiPanels);
  const portRoles = new Set(vocab.portRoles);
  const copy = JSON.parse(JSON.stringify(snapshot)) as Record<string, unknown>;
  for (const d of listOf(copy['devices']).map(recordOf)) {
    const caps = listOf(d['capabilities']).map(String);
    const rowsOf = (process: string): { readonly since: string }[] => caps.flatMap((c) => (contracts.capabilityProcesses[c] ?? []).filter((r) => r.process === process));
    const laterOnly = (process: string): boolean => {
      const rows = rowsOf(process);
      return rows.length > 0 && rows.every((r) => !stages.has(r.since));
    };
    const running = listOf(d['processes']).map((v) => String(recordOf(v)['process']));
    const dropped = new Set(running.filter((p) => !processes.has(p) || laterOnly(p)));
    const kept = running.filter((p) => !dropped.has(p));
    const keptTables = new Set(kept.flatMap((p) => contracts.processTables[p] ?? []));
    const droppedTables = new Set([...dropped].flatMap((p) => contracts.processTables[p] ?? []).filter((t) => !keptTables.has(t)));
    if (Array.isArray(d['processes'])) d['processes'] = listOf(d['processes']).filter((v) => !dropped.has(String(recordOf(v)['process'])));
    const t = recordOf(d['tables']);
    if (Array.isArray(t['extra'])) {
      const keep = (name: string): boolean => {
        const since = contracts.tableDescriptors[name]?.since;
        return tables.has(name) && (since === undefined || stages.has(since)) && !droppedTables.has(name);
      };
      const extra = listOf(t['extra']).filter((x) => keep(String(recordOf(x)['name'])));
      if (extra.length === 0) delete t['extra'];
      else t['extra'] = extra;
    }
    if (Array.isArray(d['capabilities'])) d['capabilities'] = listOf(d['capabilities']).filter((c) => capabilities.has(String(c)));
    if (Array.isArray(d['gui'])) d['gui'] = listOf(d['gui']).filter((g) => guiPanels.has(String(g)));
    for (const p of listOf(d['ports']).map(recordOf)) {
      if (Array.isArray(p['allowedRoles'])) p['allowedRoles'] = listOf(p['allowedRoles']).filter((r) => portRoles.has(String(r)));
      delete p['txBacklog'];
    }
  }
  return copy;
}

/** 16-hex hashes of each device (`devices/<id>`) and of every other top-level member of a normalised snapshot. */
function snapshotParts(normalised: Record<string, unknown>): Record<string, string> {
  const parts: Record<string, string> = {};
  for (const key of Object.keys(normalised).sort()) {
    if (key === 'devices') {
      for (const d of listOf(normalised[key]).map(recordOf)) parts[`devices/${String(d['id'])}`] = sha256Hex(canonicalJson(d)).slice(0, 16);
    } else {
      parts[key] = sha256Hex(canonicalJson(normalised[key])).slice(0, 16);
    }
  }
  return parts;
}

/** The part of a normalised snapshot a `snapshotParts` key names. */
function snapshotPart(normalised: Record<string, unknown>, key: string): unknown {
  if (!key.startsWith('devices/')) return normalised[key];
  const id = key.slice('devices/'.length);
  return listOf(normalised['devices']).find((d) => String(recordOf(d)['id']) === id);
}

// ── one run of a world ──────────────────────────────────────────────────────

/** One scripted run of a world: its golden entry plus what the reports and the guard facts need. */
export interface WorldRun {
  readonly world: P2World;
  readonly entry: WorldEntry;
  readonly events: readonly TraceEvent[];
  /** The line of every event (the golden stores only the non-background ones). */
  readonly lines: readonly string[];
  readonly background: readonly boolean[];
  readonly owners: ReadonlyMap<string, string>;
  readonly normalised: Record<string, unknown>;
  /** Setup lines the CLI refused (`<device>: <line>: <message>`). */
  readonly refused: readonly string[];
  /** Trace events the ring evicted (must be 0: every event is digested). */
  readonly dropped: number;
  /** Per probe, the cliOutput text of its session (empty for a browser fetch). */
  readonly reports: readonly string[];
  /** Device name → id in this world. */
  readonly ids: ReadonlyMap<string, DeviceId>;
}

/** Device id of a topology name. */
function idOf(sim: Simulation, name: string): DeviceId {
  for (const d of sim.devices()) if (d.spec.name === name) return d.id;
  throw new Error(`no device called ${name} in this world`);
}

/** Type `line` on a fresh console of `name`, keeping a JSON copy of the result. */
function typeLine(sim: Simulation, name: string, line: string): { typed: TypedResult; session: SessionId } {
  const session = sim.cli.open(idOf(sim, name), 'console');
  const result = sim.cli.exec(session, line);
  return { typed: { device: name, line, result: JSON.parse(JSON.stringify(result)) as unknown }, session };
}

/** The http-client tab a browser ticket owns. */
function browserTab(sim: Simulation, device: DeviceId, token: string): unknown {
  const state = sim.device(device)?.processes.get('http-client')?.stateSnapshot().state;
  const tabs = recordOf(state?.['tabs']);
  return JSON.parse(JSON.stringify(tabs[token] ?? {})) as unknown;
}

/** Start a probe at t = 90 s; `finish` (at 110 s) gives its typed record. */
function startProbe(sim: Simulation, p: Probe): { finish(): TypedResult; session?: SessionId } {
  if (p.kind === 'cli') {
    const { typed, session } = typeLine(sim, p.device, p.line);
    return { finish: () => typed, session };
  }
  const device = idOf(sim, p.device);
  const ticket = JSON.parse(JSON.stringify(sim.hostRequest(device, { app: 'http.get', url: p.url }))) as Record<string, unknown>;
  return { finish: () => ({ device: p.device, line: `browse ${p.url}`, result: { ticket, tab: browserTab(sim, device, String(ticket['requestId'])) } }) };
}

/** Per-kind counts, keys sorted. */
function countKinds(events: readonly TraceEvent[]): Record<string, number> {
  const counts = new Map<string, number>();
  for (const ev of events) counts.set(ev.kind, (counts.get(ev.kind) ?? 0) + 1);
  const out: Record<string, number> = {};
  for (const k of [...counts.keys()].sort()) out[k] = counts.get(k)!;
  return out;
}

/** Window index of an event line (`<t>|…`). */
function windowOf(line: string): number {
  return Math.floor(Number(line.slice(0, line.indexOf('|'))) / WINDOW_NS);
}

/** `<count>:<16 hex>` of each 10-second window up to the one holding `endNs`. */
function windowDigests(lines: readonly string[], endNs: number): string[] {
  const buckets: string[][] = Array.from({ length: Math.floor(endNs / WINDOW_NS) + 1 }, () => []);
  for (const line of lines) {
    const w = windowOf(line);
    while (buckets.length <= w) buckets.push([]);
    buckets[w]!.push(line);
  }
  return buckets.map((b) => `${b.length}:${sha256Hex(b.join('\n')).slice(0, 16)}`);
}

/** Run the fixed script on `w` from a fresh simulation. */
function runWorld(w: P2World): WorldRun {
  const sim = w.build();
  sim.runFor(BOOT_NS);

  const refused: string[] = [];
  for (const [name, lines] of Object.entries(w.setup)) {
    const r = sim.configure(idOf(sim, name), lines);
    for (const l of r.lines) if (!l.ok) refused.push(`${name}: ${l.line}: ${l.error?.message ?? l.output}`);
  }
  sim.runFor(SETTLE_NS);

  const probes = w.probes.map((p) => startProbe(sim, p));
  sim.runFor(PROBE_NS);
  const typed = probes.map((p) => p.finish());
  typed.push(typeLine(sim, w.show[0], w.show[1]).typed);
  sim.runFor(RUN_NS);

  const trace = sim.trace(0);
  const snapshot = sim.snapshot();
  const owners = macOwners(snapshot);
  const events = trace.events;
  const lines = events.map((ev) => eventLine(ev, owners));
  const background = backgroundFlags(events);
  const normalised = normaliseSnapshot(snapshot, p2Vocabulary());
  const reports = probes.map((p) => {
    let text = '';
    if (p.session !== undefined) for (const ev of events) if (ev.kind === 'cliOutput' && ev.session === p.session) text += ev.text;
    return text;
  });
  const ids = new Map<string, DeviceId>();
  for (const d of sim.devices()) ids.set(d.spec.name, d.id);
  const entry: WorldEntry = {
    profile: sim.profile,
    seed: sim.seed,
    endNs: sim.now,
    typed,
    eventCount: lines.length,
    eventsDigest: sha256Hex(lines.join('\n')),
    kinds: countKinds(events),
    windows: windowDigests(lines, sim.now),
    snapshot: sha256Hex(canonicalJson(normalised)),
    snapshotParts: snapshotParts(normalised),
    events: lines.filter((_, i) => !background[i]),
  };
  return { world: w, entry, events, lines, background, owners, normalised, refused, dropped: trace.dropped, reports, ids };
}

const runCache = new Map<string, WorldRun>();

/** The scripted run of `w` (once per test file run: the script is deterministic). */
export function freshRun(w: P2World): WorldRun {
  let run = runCache.get(w.name);
  if (run === undefined) {
    run = runWorld(w);
    runCache.set(w.name, run);
  }
  return run;
}

// ── the guard facts (D22) ───────────────────────────────────────────────────

/**
 * What the two guard worlds must show for the D22 guard to measure something (§10.1 `-guards`): every DISCOVER and
 * REQUEST that reaches the switch SVI dies in ipv4 as `unsupported-protocol`, the switch answers the traceroute and
 * the fetch with ICMP protocol unreachable and delivers nothing to udp or tcp, the traceroute stops on the
 * protocol-unreachable flag `!2` (ICMP code 2), and the fetch ends in an error tab. Returns the facts that do not hold.
 */
export function guardProblems(run: WorldRun): string[] {
  const sw = run.ids.get('SW1');
  const problems: string[] = [];
  const drops = run.events.filter((ev): ev is Extract<TraceEvent, { kind: 'drop' }> => ev.kind === 'drop' && ev.device === sw);
  const dhcpDrops = drops.filter((ev) => ev.pdu.proto === 'dhcp');
  for (const tag of ['dhcp-discover', 'dhcp-request']) {
    const seen = dhcpDrops.filter((ev) => ev.pdu.tag === tag);
    const clients = new Set(seen.map((ev) => ev.pdu.summary.replace(/^.* xid=/, '')));
    if (clients.size < 2) problems.push(`expected a ${tag} from each PC to die at the switch SVI, saw ${seen.length} from ${clients.size} client(s)`);
  }
  const wrong = dhcpDrops.filter((ev) => ev.reason !== 'unsupported-protocol');
  if (wrong.length > 0) problems.push(`DHCP broadcasts dropped at the switch for another reason: ${wrong.map((ev) => ev.reason).join(', ')}`);
  const upper = run.events.filter((ev) => (ev.kind === 'pduConsumed' || ev.kind === 'pduCreated') && ev.device === sw && (ev.process === 'udp' || ev.process === 'tcp'));
  if (upper.length > 0) problems.push(`udp or tcp on the switch handled ${upper.length} PDUs`);
  // ICMP 3/2 from the switch: three for the traceroute's UDP probes, one for the fetch's SYN
  const unreachable = run.events.filter(
    (ev): ev is Extract<TraceEvent, { kind: 'pduCreated' }> => ev.kind === 'pduCreated' && ev.device === sw && ev.process === 'icmpv4' && ev.pdu.summary === 'ICMP destination unreachable (protocol)',
  );
  const answered = (proto: string): number => unreachable.filter((ev) => (ev.pdu.flow ?? '').endsWith(`:${proto}`)).length;
  if (answered('udp') < 3) problems.push(`expected ICMP protocol unreachable for each traceroute probe, saw ${answered('udp')}`);
  if (answered('tcp') < 1) problems.push(`expected ICMP protocol unreachable for the fetch's SYN, saw ${answered('tcp')}`);
  for (const ev of drops.filter((d) => d.pdu.proto === 'udp' || d.pdu.proto === 'tcp')) {
    if (ev.reason !== 'unsupported-protocol') problems.push(`a ${ev.pdu.proto} packet died at the switch as ${ev.reason}, not unsupported-protocol`);
  }
  // the router's report: every probe of hop 1 answered with the protocol-unreachable flag (ICMP code 2), then stop
  const trace = run.reports[0] ?? '';
  if (!trace.includes(`1 ${GUARD_SVI} !2 !2 !2\n`) || !trace.includes(`Stopped at hop 1: ${GUARD_SVI} is unreachable.`)) {
    problems.push(`the traceroute did not stop on the protocol-unreachable flag: ${JSON.stringify(trace)}`);
  }
  const fetch = recordOf(recordOf(run.entry.typed[1]?.result)['tab']);
  if (fetch['phase'] !== 'error' || fetch['error'] !== 'The connection failed (proto-unreachable).') {
    problems.push(`the browser fetch did not fail on protocol unreachable: ${JSON.stringify(fetch)}`);
  }
  return problems;
}

// ── readable reports ────────────────────────────────────────────────────────

/** `text` cut to `max` characters. */
function clip(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max)}… (${text.length - max} more characters)`;
}

/** The normalised JSON of the run's event `i`, clipped. */
function runEventJson(run: WorldRun, i: number, max: number): string {
  const ev = run.events[i];
  return ev === undefined ? '' : clip(canonicalJson(normalizeP0Event(ev, run.owners)), max);
}

/** Indices (into `run.events`) of the run's stored (non-background) events. */
function storedIndices(run: WorldRun): number[] {
  const out: number[] = [];
  run.background.forEach((bg, i) => {
    if (!bg) out.push(i);
  });
  return out;
}

/** Largest middle section the per-event diff aligns exactly (golden events × run events). */
const DIFF_CELLS = 4_000_000;

/**
 * Per-event diff of the golden's stored lines against the run's: `-` golden-only events, `+` run-only events with
 * their normalised JSON. A longest-common-subsequence alignment of the section between the common prefix and suffix;
 * at most `limit` changed events are listed.
 */
function eventDiff(expected: readonly string[], run: WorldRun, limit: number): string[] {
  const actual = run.entry.events;
  const index = storedIndices(run);
  let lo = 0;
  while (lo < expected.length && lo < actual.length && expected[lo] === actual[lo]) lo++;
  let hiE = expected.length;
  let hiA = actual.length;
  while (hiE > lo && hiA > lo && expected[hiE - 1] === actual[hiA - 1]) {
    hiE--;
    hiA--;
  }
  const n = hiE - lo;
  const m = hiA - lo;
  const out: string[] = [];
  const minus = (i: number): void => void out.push(`  - golden #${i}  ${expected[i]}`);
  const plus = (j: number): void => void out.push(`  + run    #${j}  ${actual[j]}  ${runEventJson(run, index[j] ?? -1, 240)}`);
  if (n * m > DIFF_CELLS) {
    for (let k = 0; k < limit && (lo + k < hiE || lo + k < hiA); k++) {
      if (lo + k < hiE) minus(lo + k);
      if (lo + k < hiA) plus(lo + k);
    }
    out.push(`  (the differing sections are too long to align: ${n} golden and ${m} run events)`);
    return out;
  }
  const width = m + 1;
  const lcs = new Uint32Array((n + 1) * width);
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      lcs[i * width + j] = expected[lo + i] === actual[lo + j] ? lcs[(i + 1) * width + j + 1]! + 1 : Math.max(lcs[(i + 1) * width + j]!, lcs[i * width + j + 1]!);
    }
  }
  let i = 0;
  let j = 0;
  let changes = 0;
  while ((i < n || j < m) && changes < limit) {
    if (i < n && j < m && expected[lo + i] === actual[lo + j]) {
      i++;
      j++;
    } else if (i < n && (j === m || lcs[(i + 1) * width + j]! >= lcs[i * width + j + 1]!)) {
      minus(lo + i++);
      changes++;
    } else {
      plus(lo + j++);
      changes++;
    }
  }
  if (i < n || j < m) out.push('  … (more changed events not listed)');
  return out;
}

/** The kinds whose counts moved, as `kind a → b`. */
function movedKinds(before: Readonly<Record<string, number>>, after: Readonly<Record<string, number>>): string[] {
  return [...new Set([...Object.keys(before), ...Object.keys(after)])]
    .sort()
    .filter((k) => before[k] !== after[k])
    .map((k) => `${k} ${before[k] ?? 0} → ${after[k] ?? 0}`);
}

/**
 * Empty when the run's events equal the golden's (every digest, count, window and stored line); otherwise a report
 * naming the world, the windows that differ, the first diverging stored event and the per-kind counts that moved.
 */
function eventReport(name: string, expected: WorldEntry, run: WorldRun): string {
  const got = run.entry;
  const same =
    expected.eventCount === got.eventCount &&
    expected.eventsDigest === got.eventsDigest &&
    canonicalJson(expected.kinds) === canonicalJson(got.kinds) &&
    canonicalJson(expected.windows) === canonicalJson(got.windows) &&
    canonicalJson(expected.events) === canonicalJson(got.events);
  if (same) return '';
  const out = [
    `P2-profile trace of world "${name}" differs from test/goldens/p2-profile-digests.json (§9.4 lists the only allowed changes).`,
    `Events: the golden has ${expected.eventCount}, this run ${got.eventCount}; digest ${expected.eventsDigest.slice(0, 16)} → ${got.eventsDigest.slice(0, 16)}.`,
  ];
  const moved = movedKinds(expected.kinds, got.kinds);
  out.push(`Event counts that changed: ${moved.length === 0 ? 'none (same kinds and counts, different content or order)' : moved.join(', ')}.`);
  const windows: string[] = [];
  for (let k = 0; k < Math.max(expected.windows.length, got.windows.length); k++) {
    if (expected.windows[k] !== got.windows[k]) windows.push(`[${k * (WINDOW_NS / SEC)} s, ${(k + 1) * (WINDOW_NS / SEC)} s) ${expected.windows[k] ?? '(none)'} → ${got.windows[k] ?? '(none)'}`);
  }
  out.push(`Windows that differ (count:digest, golden → run): ${windows.length === 0 ? 'none' : ''}`, ...windows.slice(0, 20).map((w) => `  ${w}`));
  if (windows.length > 20) out.push(`  … and ${windows.length - 20} more windows`);
  const firstWindow = expected.windows.findIndex((w, k) => w !== got.windows[k]);
  const e = expected.events;
  const a = got.events;
  let first = 0;
  while (first < e.length && first < a.length && e[first] === a[first]) first++;
  if (first === e.length && first === a.length) {
    out.push('Every stored (non-background) event is unchanged: the change is in events attributable to a background PDU.');
    if (firstWindow >= 0) {
      const inWindow = run.lines.map((l, i) => ({ l, i })).filter(({ l, i }) => run.background[i] && windowOf(l) === firstWindow);
      out.push(`This run's background events in the first differing window [${firstWindow * (WINDOW_NS / SEC)} s, ${(firstWindow + 1) * (WINDOW_NS / SEC)} s) (first 20):`);
      for (const { l, i } of inWindow.slice(0, 20)) out.push(`  #${i}  ${l}  ${runEventJson(run, i, 240)}`);
    }
  } else {
    const index = storedIndices(run);
    out.push(
      `First diverging stored event: #${first} (the golden stores ${e.length} events, this run ${a.length}).`,
      `  golden: ${e[first] ?? '(no more events)'}`,
      `  run:    ${a[first] ?? '(no more events)'}`,
    );
    if (first < a.length) out.push(`  run event (normalised): ${runEventJson(run, index[first] ?? -1, 1500)}`);
    out.push('Per-event diff of the stored events (golden → run, first 40 changes):', ...eventDiff(e, run, 40));
  }
  return out.join('\n');
}

/** Empty when the normalised snapshot equals the golden's; otherwise the parts that differ, with the run's JSON. */
function snapshotReport(name: string, expected: WorldEntry, run: WorldRun): string {
  if (expected.snapshot === run.entry.snapshot) return '';
  const got = run.entry.snapshotParts;
  const keys = [...new Set([...Object.keys(expected.snapshotParts), ...Object.keys(got)])].sort();
  const out = [`Normalised end snapshot of world "${name}" differs from the golden (hash ${expected.snapshot} → ${run.entry.snapshot}).`];
  for (const key of keys) {
    const was = expected.snapshotParts[key];
    const now = got[key];
    if (was === now) continue;
    if (was === undefined) out.push(`  ${key}: not in the golden; run: ${clip(canonicalJson(snapshotPart(run.normalised, key)), 1500)}`);
    else if (now === undefined) out.push(`  ${key}: in the golden, missing from this run`);
    else out.push(`  ${key}: differs; run: ${clip(canonicalJson(snapshotPart(run.normalised, key)), 1500)}`);
  }
  if (out.length === 1) out.push('  every part hashes the same: the device order changed');
  return out.join('\n');
}

// ── recording (the architect, §9.4) ─────────────────────────────────────────

/** Names the recording switch asks for (read at call time). */
function recordSwitch(): string {
  return (process.env['NF_RECORD_P2_DIGESTS'] ?? '').trim();
}

/** Why a fresh run may not be recorded (empty when it may). */
function recordProblems(run: WorldRun): string[] {
  const problems = [...run.refused];
  for (const t of run.entry.typed) {
    const error = recordOf(t.result)['error'];
    if (error !== undefined) problems.push(`${t.device}> ${t.line}: ${canonicalJson(error)}`);
  }
  run.world.probes.forEach((p, i) => {
    if (p.kind === 'cli' && p.line.startsWith('ping ') && !/received [1-9]|Received = [1-9]|Success rate is [1-9]/.test(run.reports[i] ?? '')) {
      problems.push(`the ping got no reply: ${JSON.stringify(run.reports[i])}`);
    }
  });
  if (run.dropped !== 0) problems.push(`the trace ring evicted ${run.dropped} events`);
  if (run.world.shard === 'guards') problems.push(...guardProblems(run));
  return problems;
}

/** Sleep `ms` milliseconds synchronously (the lock wait). */
function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/** Run `fn` holding the golden's lock file, so shards recording in parallel merge instead of overwriting each other. */
function withGoldenLock<T>(fn: () => T): T {
  const deadline = Date.now() + 120_000;
  let fd: number | undefined;
  while (fd === undefined) {
    try {
      fd = openSync(LOCK_PATH, 'wx');
    } catch (e) {
      if (Date.now() > deadline) throw new Error(`could not take ${LOCK_PATH} within 120 s (a recording crashed? delete the file): ${String(e)}`);
      sleepSync(50);
    }
  }
  try {
    return fn();
  } finally {
    closeSync(fd);
    unlinkSync(LOCK_PATH);
  }
}

/** Re-record the worlds of `shard` the switch names, merging them into the golden file under its lock. */
function record(shard: P2DigestShard): void {
  const all = p2Worlds();
  const wanted = recordSwitch();
  const names = wanted === 'all' ? all.filter((w) => w.shard === shard).map((w) => w.name) : wanted.split(',').map((s) => s.trim()).filter((s) => s !== '');
  for (const name of names) if (!all.some((w) => w.name === name)) throw new Error(`NF_RECORD_P2_DIGESTS names ${name}, which is not a P2-profile golden world`);
  const mine = all.filter((w) => w.shard === shard && names.includes(w.name));
  if (mine.length === 0) return;
  const runs = mine.map((w) => {
    const run = freshRun(w);
    const problems = recordProblems(run);
    if (problems.length > 0) throw new Error(`refusing to record ${w.name}:\n  ${problems.join('\n  ')}`);
    return run;
  });
  withGoldenLock(() => {
    const previous = existsSync(GOLDEN_URL) ? (JSON.parse(readFileSync(GOLDEN_URL, 'utf8')) as GoldenFile) : undefined;
    if (previous !== undefined && canonicalJson(previous.script) !== canonicalJson(SCRIPT_TIMES) && wanted !== 'all') {
      throw new Error('the script timings changed: that re-records every world (NF_RECORD_P2_DIGESTS=all, every shard)');
    }
    const fresh = new Map(runs.map((r) => [r.world.name, r.entry]));
    const worldsOut: Record<string, WorldEntry> = {};
    for (const w of all) {
      const old = previous?.worlds[w.name];
      const now = fresh.get(w.name);
      if (now === undefined) {
        if (old !== undefined) worldsOut[w.name] = old;
        continue;
      }
      if (old !== undefined) {
        const run = runs.find((r) => r.world.name === w.name)!;
        const report = [eventReport(w.name, old, run), snapshotReport(w.name, old, run)].filter((r) => r !== '').join('\n');
        console.log(report === '' && canonicalJson(old) === canonicalJson(now) ? `${w.name}: unchanged` : `${w.name}: re-recorded\n${report}`);
      }
      worldsOut[w.name] = now;
    }
    const file: GoldenFile = { about: ABOUT, script: SCRIPT_TIMES, p2Vocabulary: previous?.p2Vocabulary ?? currentVocabulary(), worlds: worldsOut };
    writeFileSync(GOLDEN_URL, `${JSON.stringify(file, null, 2)}\n`);
    // read back from disk at the next use: shards recording in parallel merge their own entries after this one
    goldenCache = undefined;
  });
}

// ── the shard suite ─────────────────────────────────────────────────────────

/** The synthetic §4.6 case: a later-stage transport on a managed switch goes, a router's P1 transport stays. */
function normalisationCase(): { input: SimSnapshot; vocab: P2Vocabulary; contracts: NormalisationContracts; expected: unknown } {
  const vocab: P2Vocabulary = {
    stages: ['P0', 'P0.5', 'P1', 'P2'],
    processes: ['eth-switch', 'ipv4', 'udp', 'tcp', 'stp'],
    tables: ['cam', 'arp', 'rib', 'sockets', 'stp'],
    capabilities: ['switching', 'managed-switch', 'routing'],
    guiPanels: ['config'],
    portRoles: ['switchport', 'l3'],
  };
  const contracts: NormalisationContracts = {
    capabilityProcesses: {
      switching: [{ process: 'eth-switch', since: 'P0' }, { process: 'ipv4', since: 'P1' }],
      'managed-switch': [{ process: 'stp', since: 'P2' }, { process: 'udp', since: 'P3' }, { process: 'tcp', since: 'P3' }, { process: 'cdp', since: 'P3' }],
      routing: [{ process: 'ipv4', since: 'P0' }, { process: 'udp', since: 'P1' }, { process: 'tcp', since: 'P1' }, { process: 'cdp', since: 'P3' }],
      programmable: [],
    },
    processTables: { udp: ['sockets'], tcp: ['sockets'], stp: ['stp'], cdp: ['cdp'] },
    tableDescriptors: { cam: { since: 'P0' }, sockets: { since: 'P1' }, stp: { since: 'P2' }, cdp: { since: 'P3' }, 'dhcp-snooping': { since: 'P3' } },
  };
  const views = (names: readonly string[]): { process: string; state: Record<string, unknown> }[] => names.map((process) => ({ process, state: { n: 1 } }));
  const extra = (names: readonly string[]): { name: string; rows: unknown[] }[] => names.map((name) => ({ name, rows: [] }));
  const port = { id: 'Gi0/1', allowedRoles: ['switchport', 'l3', 'wan-p3'], txQueue: 0, mac: '02:00:00:00:00:01' };
  const input = {
    now: 1,
    devices: [
      {
        id: 'sw1', capabilities: ['switching', 'managed-switch', 'programmable'], gui: ['config', 'desktop.traffic'],
        processes: views(['eth-switch', 'ipv4', 'stp', 'udp', 'tcp', 'cdp']), tables: { cam: [], extra: extra(['sockets', 'stp', 'cdp', 'dhcp-snooping']) },
        ports: [port],
      },
      {
        id: 'r1', capabilities: ['routing'], gui: ['config'], processes: views(['ipv4', 'udp', 'tcp', 'cdp']), tables: { cam: [], extra: extra(['sockets', 'cdp']) },
        ports: [{ ...port, txQueue: 3, txBacklog: { depth: 2, frames: [] } }],
      },
    ],
  } as unknown as SimSnapshot;
  // The P3 display member `txBacklog` goes; the P0 frame count `txQueue` stays with its value.
  const kept = (txQueue: number): Record<string, unknown> => ({ id: 'Gi0/1', allowedRoles: ['switchport', 'l3'], txQueue, mac: '02:00:00:00:00:01' });
  const expected = {
    now: 1,
    devices: [
      { id: 'sw1', capabilities: ['switching', 'managed-switch'], gui: ['config'], processes: views(['eth-switch', 'ipv4', 'stp']), tables: { cam: [], extra: extra(['stp']) }, ports: [kept(0)] },
      { id: 'r1', capabilities: ['routing'], gui: ['config'], processes: views(['ipv4', 'udp', 'tcp']), tables: { cam: [], extra: extra(['sockets']) }, ports: [kept(3)] },
    ],
  };
  return { input, vocab, contracts, expected };
}

/**
 * The suite of one shard: coverage, the SHA-256 and background proofs, the P2 guard of the normalisation, and one
 * case per world comparing every digest, count, window, stored line, typed result and the normalised snapshot.
 */
export function describeP2DigestShard(shard: P2DigestShard, title: string): void {
  describe(title, () => {
    // Regeneration is a step before the comparison, not a test: an ordinary run neither records nor skips anything.
    beforeAll(() => {
      if (recordSwitch() !== '') record(shard);
    }, RECORD_TIMEOUT_MS);

    it('covers its worlds of the 32-world P2 golden with the fixed script', () => {
      const all = p2Worlds();
      expect(all.map((w) => w.name)).toEqual([
        ...TEMPLATES.map((s) => s.name),
        ...CCNA2_LAB_NAMES,
        SANDBOX_WORLD,
        GUARD_WORLDS.P1,
        GUARD_WORLDS.P2,
      ]);
      expect(all).toHaveLength(32);
      expect(CCNA2_LABS.map((s) => s.name)).toEqual(CCNA2_LAB_NAMES);
      expect(Object.keys(TEMPLATE_SCRIPTS)).toEqual(TEMPLATES.map((s) => s.name));
      const counts = { templates: 9, 'labs-a': 10, 'labs-b': 11, guards: 2 } as const;
      expect(shardWorlds(shard)).toHaveLength(counts[shard]);
      const keys = Object.keys(golden().worlds);
      // golden order is world order; in a recording run the other shards may still be merging their own entries
      expect(keys).toEqual(all.map((w) => w.name).filter((n) => keys.includes(n)));
      if (recordSwitch() === '') expect(keys).toEqual(all.map((w) => w.name));
      else for (const w of shardWorlds(shard)) expect(keys, w.name).toContain(w.name);
      expect(golden().script).toEqual(SCRIPT_TIMES);
      expect(golden().about).toBe(ABOUT);
    });

    it('hashes with a plain TypeScript SHA-256 whose event lines are exactly the harness p0EventLine', () => {
      expect(sha256Hex('')).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
      expect(sha256Hex('abc')).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
      expect(sha256Hex('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')).toBe('248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1');
      for (const w of shardWorlds(shard)) {
        const run = freshRun(w);
        expect(run.lines, w.name).toEqual(run.events.map((ev) => p0EventLine(ev, run.owners)));
      }
    }, SHARD_CASE_TIMEOUT_MS);

    it('stores every event not attributable to a background PDU, and only those', () => {
      for (const w of shardWorlds(shard)) {
        const run = freshRun(w);
        // every event that references no PDU is stored; a frameTx or drop flagged background never is
        run.events.forEach((ev, i) => {
          if (referencedPdus(ev).length === 0) expect(run.background[i], `${w.name} #${i} ${ev.kind}`).toBe(false);
          const flagged = (ev.kind === 'frameTx' || ev.kind === 'drop') && (ev as unknown as { background?: boolean }).background === true;
          if (flagged) expect(run.background[i], `${w.name} #${i} ${ev.kind}`).toBe(true);
        });
        expect(run.entry.events.length, w.name).toBe(run.background.filter((b) => !b).length);
      }
    }, SHARD_CASE_TIMEOUT_MS);

    it('normalises the snapshot by removing only what a later stage adds (§4.6)', () => {
      const p2 = golden().p2Vocabulary;
      const now = currentVocabulary();
      // Nothing the P2 engine had is gone or reordered: a later stage only inserts or appends.
      for (const key of ['stages', 'processes', 'tables', 'capabilities', 'guiPanels', 'portRoles'] as const) {
        expect(now[key].filter((x) => p2[key].includes(x)), key).toEqual(p2[key]);
      }
      const later = now.stages.filter((s) => !p2.stages.includes(s));
      // Every daemon outside the P2 list is of a later stage: each of its CAPABILITY_PROCESSES rows has a later `since`.
      const rows = Object.values(CAPABILITY_PROCESSES).flat();
      for (const name of now.processes.filter((x) => !p2.processes.includes(x))) {
        const since = rows.filter((r) => r.process === name).map((r) => String(r.since));
        expect(since.filter((s) => !later.includes(s)), name).toEqual([]);
      }
      // Every table outside the P2 list has a later-stage descriptor.
      const descriptors = TABLE_DESCRIPTORS as unknown as Readonly<Record<string, { readonly since: string }>>;
      for (const name of now.tables.filter((x) => !p2.tables.includes(x))) expect(later, name).toContain(descriptors[name]?.since);
      // The per-device rule itself, on a synthetic P3-shaped snapshot (D22: a managed switch loses the later-stage
      // udp/tcp and their sockets table; a router keeps its P1 udp/tcp; later-stage tables and members go).
      const c = normalisationCase();
      expect(normaliseSnapshot(c.input, c.vocab, c.contracts)).toEqual(c.expected);
    });

    for (const w of shardWorlds(shard)) {
      it(`${w.name}: every event digest, window and stored line, the typed results and the normalised snapshot equal the P2 golden`, () => {
        const expected = golden().worlds[w.name];
        if (expected === undefined) return assert.fail(`${w.name} has no entry in test/goldens/p2-profile-digests.json`);
        const run = freshRun(w);
        expect(run.refused, `${w.name}: setup lines the CLI refused`).toEqual([]);
        expect(run.dropped, `${w.name}: trace events evicted before they were digested`).toBe(0);

        const events = eventReport(w.name, expected, run);
        if (events !== '') assert.fail(events);
        expect(run.entry.typed, `${w.name}: the typed results`).toEqual(expected.typed);
        const snapshot = snapshotReport(w.name, expected, run);
        if (snapshot !== '') assert.fail(snapshot);
        expect(run.entry).toEqual(expected);
      }, SHARD_CASE_TIMEOUT_MS);
    }
  });
}
